/**
 * AUTO-GENERATED by tools/lama/backtest-distribution.py — do not edit by hand.
 *
 * Match rate нашего auto-distribute алгоритма vs реальная LAMA-история.
 * Per shop: сколько из всех задач shop'а наш алгоритм поручил бы тому
 * же сотруднику что и LAMA фактически выбрала. Median по shop'ам —
 * эталонная метрика «насколько мы попадаем в ground truth».
 *
 * Built at: 2026-05-11T19:44:44Z
 */

export interface BacktestShopMatch {
  shop_code: string;
  total_tasks: number;
  matched: number;
  match_pct: number;
}

export const BACKTEST_SHOP_MATCH: readonly BacktestShopMatch[] = [
  { shop_code: "0096", total_tasks: 31, matched: 31, match_pct: 100.0 },
  { shop_code: "0035", total_tasks: 26, matched: 24, match_pct: 92.3 },
  { shop_code: "0129", total_tasks: 25, matched: 22, match_pct: 88.0 },
  { shop_code: "0127", total_tasks: 12, matched: 10, match_pct: 83.3 },
  { shop_code: "0052", total_tasks: 22, matched: 17, match_pct: 77.3 },
  { shop_code: "0032", total_tasks: 30, matched: 23, match_pct: 76.7 },
  { shop_code: "0039", total_tasks: 41, matched: 31, match_pct: 75.6 },
  { shop_code: "0100", total_tasks: 24, matched: 18, match_pct: 75.0 },
  { shop_code: "0024", total_tasks: 19, matched: 14, match_pct: 73.7 },
  { shop_code: "0034", total_tasks: 25, matched: 18, match_pct: 72.0 },
  { shop_code: "0019", total_tasks: 34, matched: 24, match_pct: 70.6 },
  { shop_code: "0117", total_tasks: 33, matched: 23, match_pct: 69.7 },
  { shop_code: "0105", total_tasks: 35, matched: 24, match_pct: 68.6 },
  { shop_code: "0144", total_tasks: 19, matched: 13, match_pct: 68.4 },
  { shop_code: "0029", total_tasks: 31, matched: 21, match_pct: 67.7 },
  { shop_code: "0018", total_tasks: 12, matched: 8, match_pct: 66.7 },
  { shop_code: "0118", total_tasks: 27, matched: 18, match_pct: 66.7 },
  { shop_code: "0036", total_tasks: 42, matched: 28, match_pct: 66.7 },
  { shop_code: "0015", total_tasks: 26, matched: 17, match_pct: 65.4 },
  { shop_code: "0040", total_tasks: 23, matched: 15, match_pct: 65.2 },
  { shop_code: "0138", total_tasks: 31, matched: 20, match_pct: 64.5 },
  { shop_code: "0037", total_tasks: 44, matched: 28, match_pct: 63.6 },
  { shop_code: "0116", total_tasks: 27, matched: 17, match_pct: 63.0 },
  { shop_code: "0062", total_tasks: 47, matched: 29, match_pct: 61.7 },
  { shop_code: "0012", total_tasks: 50, matched: 30, match_pct: 60.0 },
  { shop_code: "0120", total_tasks: 20, matched: 12, match_pct: 60.0 },
  { shop_code: "0142", total_tasks: 30, matched: 18, match_pct: 60.0 },
  { shop_code: "0041", total_tasks: 42, matched: 25, match_pct: 59.5 },
  { shop_code: "0050", total_tasks: 34, matched: 20, match_pct: 58.8 },
  { shop_code: "0150", total_tasks: 36, matched: 21, match_pct: 58.3 },
  { shop_code: "0047", total_tasks: 31, matched: 18, match_pct: 58.1 },
  { shop_code: "0136", total_tasks: 30, matched: 17, match_pct: 56.7 },
  { shop_code: "0048", total_tasks: 46, matched: 26, match_pct: 56.5 },
  { shop_code: "0016", total_tasks: 50, matched: 28, match_pct: 56.0 },
  { shop_code: "0006", total_tasks: 44, matched: 24, match_pct: 54.5 },
  { shop_code: "0013", total_tasks: 22, matched: 12, match_pct: 54.5 },
  { shop_code: "0154", total_tasks: 22, matched: 12, match_pct: 54.5 },
  { shop_code: "0042", total_tasks: 30, matched: 16, match_pct: 53.3 },
  { shop_code: "0133", total_tasks: 30, matched: 16, match_pct: 53.3 },
  { shop_code: "0094", total_tasks: 40, matched: 21, match_pct: 52.5 },
  { shop_code: "0008", total_tasks: 37, matched: 19, match_pct: 51.4 },
  { shop_code: "0017", total_tasks: 43, matched: 22, match_pct: 51.2 },
  { shop_code: "0043", total_tasks: 49, matched: 25, match_pct: 51.0 },
  { shop_code: "0031", total_tasks: 44, matched: 22, match_pct: 50.0 },
  { shop_code: "0101", total_tasks: 16, matched: 8, match_pct: 50.0 },
  { shop_code: "0044", total_tasks: 29, matched: 14, match_pct: 48.3 },
  { shop_code: "0102", total_tasks: 46, matched: 22, match_pct: 47.8 },
  { shop_code: "0170", total_tasks: 45, matched: 21, match_pct: 46.7 },
  { shop_code: "0055", total_tasks: 28, matched: 13, match_pct: 46.4 },
  { shop_code: "0081", total_tasks: 28, matched: 13, match_pct: 46.4 },
  { shop_code: "0045", total_tasks: 39, matched: 18, match_pct: 46.2 },
  { shop_code: "0175", total_tasks: 35, matched: 16, match_pct: 45.7 },
  { shop_code: "0069", total_tasks: 31, matched: 14, match_pct: 45.2 },
  { shop_code: "0026", total_tasks: 52, matched: 23, match_pct: 44.2 },
  { shop_code: "0065", total_tasks: 25, matched: 11, match_pct: 44.0 },
  { shop_code: "0121", total_tasks: 51, matched: 22, match_pct: 43.1 },
  { shop_code: "0023", total_tasks: 33, matched: 14, match_pct: 42.4 },
  { shop_code: "0033", total_tasks: 52, matched: 22, match_pct: 42.3 },
  { shop_code: "0104", total_tasks: 31, matched: 13, match_pct: 41.9 },
  { shop_code: "0145", total_tasks: 34, matched: 13, match_pct: 38.2 },
  { shop_code: "0030", total_tasks: 32, matched: 12, match_pct: 37.5 },
  { shop_code: "0020", total_tasks: 59, matched: 22, match_pct: 37.3 },
  { shop_code: "0028", total_tasks: 28, matched: 8, match_pct: 28.6 },
  { shop_code: "0134", total_tasks: 21, matched: 6, match_pct: 28.6 },
];

export const BACKTEST_OVERALL_MATCH_PCT = 56.4;
export const BACKTEST_MEDIAN_MATCH_PCT = 56.6;
export const BACKTEST_SUMMARY_BUILT_AT = "2026-05-11T19:44:44Z";
