/**
 * AUTO-GENERATED by tools/lama/backtest-distribution.py — do not edit by hand.
 *
 * Match rate нашего auto-distribute алгоритма vs реальная LAMA-история.
 * Per shop: сколько из всех задач shop'а наш алгоритм поручил бы тому
 * же сотруднику что и LAMA фактически выбрала. Median по shop'ам —
 * эталонная метрика «насколько мы попадаем в ground truth».
 *
 * Built at: 2026-05-10T17:19:53Z
 */

export interface BacktestShopMatch {
  shop_code: string;
  total_tasks: number;
  matched: number;
  match_pct: number;
}

export const BACKTEST_SHOP_MATCH: readonly BacktestShopMatch[] = [
  { shop_code: "0010", total_tasks: 21, matched: 15, match_pct: 71.4 },
  { shop_code: "0134", total_tasks: 44, matched: 29, match_pct: 65.9 },
  { shop_code: "0035", total_tasks: 74, matched: 47, match_pct: 63.5 },
  { shop_code: "0138", total_tasks: 49, matched: 30, match_pct: 61.2 },
  { shop_code: "0094", total_tasks: 79, matched: 48, match_pct: 60.8 },
  { shop_code: "0100", total_tasks: 33, matched: 20, match_pct: 60.6 },
  { shop_code: "0052", total_tasks: 39, matched: 23, match_pct: 59.0 },
  { shop_code: "0101", total_tasks: 34, matched: 20, match_pct: 58.8 },
  { shop_code: "0102", total_tasks: 70, matched: 41, match_pct: 58.6 },
  { shop_code: "0104", total_tasks: 95, matched: 55, match_pct: 57.9 },
  { shop_code: "0045", total_tasks: 82, matched: 46, match_pct: 56.1 },
  { shop_code: "0181", total_tasks: 25, matched: 14, match_pct: 56.0 },
  { shop_code: "0038", total_tasks: 77, matched: 43, match_pct: 55.8 },
  { shop_code: "0030", total_tasks: 103, matched: 57, match_pct: 55.3 },
  { shop_code: "0127", total_tasks: 29, matched: 16, match_pct: 55.2 },
  { shop_code: "0095", total_tasks: 91, matched: 50, match_pct: 54.9 },
  { shop_code: "0032", total_tasks: 46, matched: 25, match_pct: 54.3 },
  { shop_code: "0154", total_tasks: 77, matched: 41, match_pct: 53.2 },
  { shop_code: "0013", total_tasks: 109, matched: 58, match_pct: 53.2 },
  { shop_code: "0048", total_tasks: 143, matched: 76, match_pct: 53.1 },
  { shop_code: "0037", total_tasks: 108, matched: 57, match_pct: 52.8 },
  { shop_code: "0018", total_tasks: 77, matched: 40, match_pct: 51.9 },
  { shop_code: "0019", total_tasks: 76, matched: 39, match_pct: 51.3 },
  { shop_code: "0136", total_tasks: 94, matched: 48, match_pct: 51.1 },
  { shop_code: "0044", total_tasks: 46, matched: 23, match_pct: 50.0 },
  { shop_code: "0144", total_tasks: 28, matched: 14, match_pct: 50.0 },
  { shop_code: "0029", total_tasks: 139, matched: 69, match_pct: 49.6 },
  { shop_code: "0033", total_tasks: 142, matched: 70, match_pct: 49.3 },
  { shop_code: "0175", total_tasks: 63, matched: 31, match_pct: 49.2 },
  { shop_code: "0116", total_tasks: 47, matched: 23, match_pct: 48.9 },
  { shop_code: "0040", total_tasks: 66, matched: 32, match_pct: 48.5 },
  { shop_code: "0118", total_tasks: 64, matched: 31, match_pct: 48.4 },
  { shop_code: "0016", total_tasks: 50, matched: 24, match_pct: 48.0 },
  { shop_code: "0055", total_tasks: 82, matched: 38, match_pct: 46.3 },
  { shop_code: "0043", total_tasks: 105, matched: 48, match_pct: 45.7 },
  { shop_code: "0096", total_tasks: 57, matched: 26, match_pct: 45.6 },
  { shop_code: "0062", total_tasks: 150, matched: 67, match_pct: 44.7 },
  { shop_code: "0041", total_tasks: 84, matched: 37, match_pct: 44.0 },
  { shop_code: "0042", total_tasks: 78, matched: 34, match_pct: 43.6 },
  { shop_code: "0145", total_tasks: 117, matched: 51, match_pct: 43.6 },
  { shop_code: "0142", total_tasks: 84, matched: 36, match_pct: 42.9 },
  { shop_code: "0150", total_tasks: 92, matched: 39, match_pct: 42.4 },
  { shop_code: "0050", total_tasks: 97, matched: 41, match_pct: 42.3 },
  { shop_code: "0133", total_tasks: 62, matched: 26, match_pct: 41.9 },
  { shop_code: "0012", total_tasks: 187, matched: 76, match_pct: 40.6 },
  { shop_code: "0008", total_tasks: 116, matched: 47, match_pct: 40.5 },
  { shop_code: "0129", total_tasks: 40, matched: 16, match_pct: 40.0 },
  { shop_code: "0034", total_tasks: 46, matched: 18, match_pct: 39.1 },
  { shop_code: "0015", total_tasks: 114, matched: 44, match_pct: 38.6 },
  { shop_code: "0081", total_tasks: 65, matched: 25, match_pct: 38.5 },
  { shop_code: "0024", total_tasks: 81, matched: 31, match_pct: 38.3 },
  { shop_code: "0065", total_tasks: 82, matched: 31, match_pct: 37.8 },
  { shop_code: "0117", total_tasks: 92, matched: 34, match_pct: 37.0 },
  { shop_code: "0025", total_tasks: 11, matched: 4, match_pct: 36.4 },
  { shop_code: "0039", total_tasks: 99, matched: 35, match_pct: 35.4 },
  { shop_code: "0006", total_tasks: 167, matched: 59, match_pct: 35.3 },
  { shop_code: "0023", total_tasks: 129, matched: 45, match_pct: 34.9 },
  { shop_code: "0047", total_tasks: 61, matched: 21, match_pct: 34.4 },
  { shop_code: "0031", total_tasks: 149, matched: 51, match_pct: 34.2 },
  { shop_code: "0170", total_tasks: 138, matched: 46, match_pct: 33.3 },
  { shop_code: "0105", total_tasks: 72, matched: 24, match_pct: 33.3 },
  { shop_code: "0028", total_tasks: 119, matched: 39, match_pct: 32.8 },
  { shop_code: "0120", total_tasks: 80, matched: 26, match_pct: 32.5 },
  { shop_code: "0026", total_tasks: 195, matched: 63, match_pct: 32.3 },
  { shop_code: "0121", total_tasks: 155, matched: 48, match_pct: 31.0 },
  { shop_code: "0069", total_tasks: 92, matched: 27, match_pct: 29.3 },
  { shop_code: "0020", total_tasks: 136, matched: 39, match_pct: 28.7 },
  { shop_code: "0017", total_tasks: 99, matched: 20, match_pct: 20.2 },
];

export const BACKTEST_OVERALL_MATCH_PCT = 43.9;
export const BACKTEST_MEDIAN_MATCH_PCT = 46.0;
export const BACKTEST_SUMMARY_BUILT_AT = "2026-05-10T17:19:53Z";
