/**
 * AUTO-GENERATED by tools/lama/backtest-distribution.py — do not edit by hand.
 *
 * Match rate нашего auto-distribute алгоритма vs реальная LAMA-история.
 * Per shop: сколько из всех задач shop'а наш алгоритм поручил бы тому
 * же сотруднику что и LAMA фактически выбрала. Median по shop'ам —
 * эталонная метрика «насколько мы попадаем в ground truth».
 *
 * Built at: 2026-05-11T19:40:58Z
 */

export interface BacktestShopMatch {
  shop_code: string;
  total_tasks: number;
  matched: number;
  match_pct: number;
}

export const BACKTEST_SHOP_MATCH: readonly BacktestShopMatch[] = [
  { shop_code: "0038", total_tasks: 77, matched: 60, match_pct: 77.9 },
  { shop_code: "0032", total_tasks: 76, matched: 57, match_pct: 75.0 },
  { shop_code: "0127", total_tasks: 41, matched: 30, match_pct: 73.2 },
  { shop_code: "0052", total_tasks: 61, matched: 44, match_pct: 72.1 },
  { shop_code: "0035", total_tasks: 100, matched: 69, match_pct: 69.0 },
  { shop_code: "0116", total_tasks: 74, matched: 50, match_pct: 67.6 },
  { shop_code: "0096", total_tasks: 88, matched: 59, match_pct: 67.0 },
  { shop_code: "0010", total_tasks: 21, matched: 14, match_pct: 66.7 },
  { shop_code: "0138", total_tasks: 80, matched: 52, match_pct: 65.0 },
  { shop_code: "0036", total_tasks: 42, matched: 27, match_pct: 64.3 },
  { shop_code: "0018", total_tasks: 89, matched: 56, match_pct: 62.9 },
  { shop_code: "0040", total_tasks: 89, matched: 53, match_pct: 59.6 },
  { shop_code: "0154", total_tasks: 99, matched: 56, match_pct: 56.6 },
  { shop_code: "0042", total_tasks: 108, matched: 61, match_pct: 56.5 },
  { shop_code: "0095", total_tasks: 91, matched: 51, match_pct: 56.0 },
  { shop_code: "0025", total_tasks: 11, matched: 6, match_pct: 54.5 },
  { shop_code: "0048", total_tasks: 189, matched: 102, match_pct: 54.0 },
  { shop_code: "0044", total_tasks: 75, matched: 40, match_pct: 53.3 },
  { shop_code: "0104", total_tasks: 126, matched: 67, match_pct: 53.2 },
  { shop_code: "0094", total_tasks: 119, matched: 63, match_pct: 52.9 },
  { shop_code: "0039", total_tasks: 140, matched: 74, match_pct: 52.9 },
  { shop_code: "0150", total_tasks: 128, matched: 67, match_pct: 52.3 },
  { shop_code: "0175", total_tasks: 98, matched: 51, match_pct: 52.0 },
  { shop_code: "0144", total_tasks: 47, matched: 24, match_pct: 51.1 },
  { shop_code: "0055", total_tasks: 110, matched: 56, match_pct: 50.9 },
  { shop_code: "0041", total_tasks: 126, matched: 64, match_pct: 50.8 },
  { shop_code: "0037", total_tasks: 152, matched: 77, match_pct: 50.7 },
  { shop_code: "0118", total_tasks: 91, matched: 46, match_pct: 50.5 },
  { shop_code: "0043", total_tasks: 154, matched: 77, match_pct: 50.0 },
  { shop_code: "0034", total_tasks: 71, matched: 35, match_pct: 49.3 },
  { shop_code: "0015", total_tasks: 140, matched: 69, match_pct: 49.3 },
  { shop_code: "0100", total_tasks: 57, matched: 28, match_pct: 49.1 },
  { shop_code: "0019", total_tasks: 110, matched: 54, match_pct: 49.1 },
  { shop_code: "0101", total_tasks: 50, matched: 24, match_pct: 48.0 },
  { shop_code: "0181", total_tasks: 25, matched: 12, match_pct: 48.0 },
  { shop_code: "0133", total_tasks: 92, matched: 44, match_pct: 47.8 },
  { shop_code: "0030", total_tasks: 135, matched: 64, match_pct: 47.4 },
  { shop_code: "0050", total_tasks: 131, matched: 62, match_pct: 47.3 },
  { shop_code: "0081", total_tasks: 93, matched: 44, match_pct: 47.3 },
  { shop_code: "0033", total_tasks: 194, matched: 91, match_pct: 46.9 },
  { shop_code: "0065", total_tasks: 107, matched: 50, match_pct: 46.7 },
  { shop_code: "0136", total_tasks: 124, matched: 57, match_pct: 46.0 },
  { shop_code: "0142", total_tasks: 114, matched: 52, match_pct: 45.6 },
  { shop_code: "0045", total_tasks: 121, matched: 55, match_pct: 45.5 },
  { shop_code: "0120", total_tasks: 100, matched: 45, match_pct: 45.0 },
  { shop_code: "0129", total_tasks: 65, matched: 29, match_pct: 44.6 },
  { shop_code: "0016", total_tasks: 100, matched: 44, match_pct: 44.0 },
  { shop_code: "0170", total_tasks: 183, matched: 80, match_pct: 43.7 },
  { shop_code: "0028", total_tasks: 147, matched: 63, match_pct: 42.9 },
  { shop_code: "0012", total_tasks: 237, matched: 101, match_pct: 42.6 },
  { shop_code: "0013", total_tasks: 131, matched: 54, match_pct: 41.2 },
  { shop_code: "0006", total_tasks: 211, matched: 85, match_pct: 40.3 },
  { shop_code: "0047", total_tasks: 92, matched: 37, match_pct: 40.2 },
  { shop_code: "0029", total_tasks: 170, matched: 68, match_pct: 40.0 },
  { shop_code: "0031", total_tasks: 193, matched: 77, match_pct: 39.9 },
  { shop_code: "0023", total_tasks: 162, matched: 64, match_pct: 39.5 },
  { shop_code: "0105", total_tasks: 107, matched: 42, match_pct: 39.3 },
  { shop_code: "0069", total_tasks: 123, matched: 48, match_pct: 39.0 },
  { shop_code: "0102", total_tasks: 116, matched: 44, match_pct: 37.9 },
  { shop_code: "0062", total_tasks: 197, matched: 74, match_pct: 37.6 },
  { shop_code: "0026", total_tasks: 247, matched: 91, match_pct: 36.8 },
  { shop_code: "0117", total_tasks: 125, matched: 46, match_pct: 36.8 },
  { shop_code: "0008", total_tasks: 153, matched: 55, match_pct: 35.9 },
  { shop_code: "0017", total_tasks: 142, matched: 51, match_pct: 35.9 },
  { shop_code: "0145", total_tasks: 151, matched: 54, match_pct: 35.8 },
  { shop_code: "0134", total_tasks: 65, matched: 23, match_pct: 35.4 },
  { shop_code: "0024", total_tasks: 100, matched: 35, match_pct: 35.0 },
  { shop_code: "0121", total_tasks: 206, matched: 59, match_pct: 28.6 },
  { shop_code: "0020", total_tasks: 195, matched: 55, match_pct: 28.2 },
];

export const BACKTEST_OVERALL_MATCH_PCT = 46.6;
export const BACKTEST_MEDIAN_MATCH_PCT = 48.0;
export const BACKTEST_SUMMARY_BUILT_AT = "2026-05-11T19:40:58Z";
