/**
 * AUTO-GENERATED by tools/lama/build-backtest-baseline.py — do not edit by hand.
 *
 * 30-day rolling history of LAMA distribution outcomes — compact id-only.
 * Used by tools/lama/backtest-distribution.py to compare our algo vs reality.
 *
 * Storage layout: per-date arrays of int tuples + 4 string-tables
 * (shop_code / work_type / zone / status) → ~6x compression vs flat array.
 * Use {@link LAMA_BACKTEST_BASELINE} to materialize records as objects.
 *
 * Built at: 2026-10-09T22:05:51Z
 * Date range: 2026-09-11 to 2026-10-10 (30 day(s))
 *
 * 0 records, 0 shops, 0 work_types,
 * 0 zones, 0 statuses.
 */

export interface BacktestTaskRecord {
  /** "YYYY-MM-DD" — день LAMA-снимка. */
  date: string;
  task_id: number;
  /** shop_code (4-digit), не shop_name — резолвить через _lama-real.ts. */
  shop_code: string;
  /** Ground truth — кто реально получил task в LAMA. */
  employee_id: number;
  eis_id: number;
  shift_id: number;
  /** operation_work из снапшота, like "Касса", "Выкладка: Бакалея". */
  work_type: string;
  /** operation_zone (null если задача без зоны). */
  zone: string | null;
  /** Минуты (округлено вниз из секунд снапшота). */
  duration: number;
  /** "Completed" / "Accepted" / "Suspended" / "InProgress" / "Created". */
  status: string;
}

/**
 * Compact tuple — фиксированный layout:
 *   [task_id, shop_idx, employee_id, eis_id, shift_id,
 *    work_type_idx, zone_idx, duration_min, status_idx]
 * `zone_idx === -1` означает `zone: null`.
 */
export type BacktestTuple = [
  number, number, number, number, number, number, number, number, number, number,
];

export const BACKTEST_SHOPS: readonly string[] = [];

export const BACKTEST_WORK_TYPES: readonly string[] = [];

export const BACKTEST_ZONES: readonly string[] = [];

export const BACKTEST_STATUSES: readonly string[] = [];

/** date → tuples (compact storage; используйте {@link LAMA_BACKTEST_BASELINE}). */
export const BACKTEST_BY_DATE: Readonly<Record<string, readonly BacktestTuple[]>> = {
  "2026-09-11": [
  ],
  "2026-09-12": [
  ],
  "2026-09-13": [
  ],
  "2026-09-14": [
  ],
  "2026-09-15": [
  ],
  "2026-09-16": [
  ],
  "2026-09-17": [
  ],
  "2026-09-18": [
  ],
  "2026-09-19": [
  ],
  "2026-09-20": [
  ],
  "2026-09-21": [
  ],
  "2026-09-22": [
  ],
  "2026-09-23": [
  ],
  "2026-09-24": [
  ],
  "2026-09-25": [
  ],
  "2026-09-26": [
  ],
  "2026-09-27": [
  ],
  "2026-09-28": [
  ],
  "2026-09-29": [
  ],
  "2026-09-30": [
  ],
  "2026-10-01": [
  ],
  "2026-10-02": [
  ],
  "2026-10-03": [
  ],
  "2026-10-04": [
  ],
  "2026-10-05": [
  ],
  "2026-10-06": [
  ],
  "2026-10-07": [
  ],
  "2026-10-08": [
  ],
  "2026-10-09": [
  ],
  "2026-10-10": [
  ],
};

function _materializeBacktestBaseline(): BacktestTaskRecord[] {
  const out: BacktestTaskRecord[] = [];
  for (const date of Object.keys(BACKTEST_BY_DATE)) {
    const recs = BACKTEST_BY_DATE[date];
    for (const t of recs) {
      const zoneIdx = t[6];
      out.push({
        date,
        task_id: t[0],
        shop_code: BACKTEST_SHOPS[t[1]] ?? "",
        employee_id: t[2],
        eis_id: t[3],
        shift_id: t[4],
        work_type: BACKTEST_WORK_TYPES[t[5]] ?? "",
        zone: zoneIdx === -1 ? null : (BACKTEST_ZONES[zoneIdx] ?? null),
        duration: t[7],
        status: BACKTEST_STATUSES[t[8]] ?? "",
      });
    }
  }
  return out;
}

/** Полностью развёрнутый массив записей (декодирован из {@link BACKTEST_BY_DATE}). */
export const LAMA_BACKTEST_BASELINE: readonly BacktestTaskRecord[] = _materializeBacktestBaseline();

export const BACKTEST_BUILT_AT = "2026-10-09T22:05:51Z";
export const BACKTEST_DATE_RANGE: { from: string; to: string; days: number } = { from: "2026-09-11", to: "2026-10-10", days: 30 };
export const BACKTEST_TOTAL_RECORDS = 0;
