/**
 * РЕАЛЬНЫЕ операции LAMA (источник: prod БД).
 *
 * 270 записей в таблице operation_work_type_zone (many-to-many).
 * Один op_id может быть привязан к нескольким (wt_id, zone) комбинациям.
 *
 * Используется для:
 *  - генерации subtasks для каждой LAMA задачи (см. _lama-real-subtasks.ts)
 *  - валидации создаваемых задач (work_type должен иметь операции в зоне)
 */

export interface LamaOperation {
  /** work_type_id (1-8 из LAMA таксономии) */
  wt_id: number;
  /** zone_id в LAMA БД (1-32) — НЕ mock zone.id */
  lama_z_id: number;
  /** operation_id из LAMA */
  op_id: number;
  /** название операции */
  name: string;
}

export const LAMA_OPERATIONS: LamaOperation[] = [
  { wt_id: 4, lama_z_id: 11, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 11, op_id: 7, name: "Выкладка товара" },
  { wt_id: 4, lama_z_id: 11, op_id: 5, name: "Набор товара с паллеты" },
  { wt_id: 4, lama_z_id: 11, op_id: 1, name: "Проверить ценники сканером (ТСД)" },
  { wt_id: 4, lama_z_id: 11, op_id: 3, name: "Проверка сроков годности" },
  { wt_id: 4, lama_z_id: 11, op_id: 4, name: "Старый товар вперёд (по сроку годности)" },
  { wt_id: 4, lama_z_id: 11, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 11, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 13, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 13, op_id: 7, name: "Выкладка товара" },
  { wt_id: 4, lama_z_id: 13, op_id: 5, name: "Набор товара с паллеты" },
  { wt_id: 4, lama_z_id: 13, op_id: 1, name: "Проверить ценники сканером (ТСД)" },
  { wt_id: 4, lama_z_id: 13, op_id: 3, name: "Проверка сроков годности" },
  { wt_id: 4, lama_z_id: 13, op_id: 4, name: "Старый товар вперёд (по сроку годности)" },
  { wt_id: 4, lama_z_id: 13, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 13, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 6, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 6, op_id: 7, name: "Выкладка товара" },
  { wt_id: 4, lama_z_id: 6, op_id: 5, name: "Набор товара с паллеты" },
  { wt_id: 4, lama_z_id: 6, op_id: 1, name: "Проверить ценники сканером (ТСД)" },
  { wt_id: 4, lama_z_id: 6, op_id: 3, name: "Проверка сроков годности" },
  { wt_id: 4, lama_z_id: 6, op_id: 4, name: "Старый товар вперёд (по сроку годности)" },
  { wt_id: 4, lama_z_id: 6, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 6, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 10, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 10, op_id: 7, name: "Выкладка товара" },
  { wt_id: 4, lama_z_id: 10, op_id: 5, name: "Набор товара с паллеты" },
  { wt_id: 4, lama_z_id: 10, op_id: 1, name: "Проверить ценники сканером (ТСД)" },
  { wt_id: 4, lama_z_id: 10, op_id: 3, name: "Проверка сроков годности" },
  { wt_id: 4, lama_z_id: 10, op_id: 4, name: "Старый товар вперёд (по сроку годности)" },
  { wt_id: 4, lama_z_id: 10, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 10, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 9, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 9, op_id: 7, name: "Выкладка товара" },
  { wt_id: 4, lama_z_id: 9, op_id: 5, name: "Набор товара с паллеты" },
  { wt_id: 4, lama_z_id: 9, op_id: 1, name: "Проверить ценники сканером (ТСД)" },
  { wt_id: 4, lama_z_id: 9, op_id: 3, name: "Проверка сроков годности" },
  { wt_id: 4, lama_z_id: 9, op_id: 4, name: "Старый товар вперёд (по сроку годности)" },
  { wt_id: 4, lama_z_id: 9, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 9, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 14, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 14, op_id: 7, name: "Выкладка товара" },
  { wt_id: 4, lama_z_id: 14, op_id: 5, name: "Набор товара с паллеты" },
  { wt_id: 4, lama_z_id: 14, op_id: 1, name: "Проверить ценники сканером (ТСД)" },
  { wt_id: 4, lama_z_id: 14, op_id: 3, name: "Проверка сроков годности" },
  { wt_id: 4, lama_z_id: 14, op_id: 4, name: "Старый товар вперёд (по сроку годности)" },
  { wt_id: 4, lama_z_id: 14, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 14, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 19, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 5, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 5, op_id: 7, name: "Выкладка товара" },
  { wt_id: 4, lama_z_id: 5, op_id: 5, name: "Набор товара с паллеты" },
  { wt_id: 4, lama_z_id: 5, op_id: 1, name: "Проверить ценники сканером (ТСД)" },
  { wt_id: 4, lama_z_id: 5, op_id: 3, name: "Проверка сроков годности" },
  { wt_id: 4, lama_z_id: 5, op_id: 4, name: "Старый товар вперёд (по сроку годности)" },
  { wt_id: 4, lama_z_id: 5, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 5, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 22, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 3, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 3, op_id: 7, name: "Выкладка товара" },
  { wt_id: 4, lama_z_id: 3, op_id: 5, name: "Набор товара с паллеты" },
  { wt_id: 4, lama_z_id: 3, op_id: 1, name: "Проверить ценники сканером (ТСД)" },
  { wt_id: 4, lama_z_id: 3, op_id: 3, name: "Проверка сроков годности" },
  { wt_id: 4, lama_z_id: 3, op_id: 4, name: "Старый товар вперёд (по сроку годности)" },
  { wt_id: 4, lama_z_id: 3, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 3, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 4, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 4, op_id: 7, name: "Выкладка товара" },
  { wt_id: 4, lama_z_id: 4, op_id: 5, name: "Набор товара с паллеты" },
  { wt_id: 4, lama_z_id: 4, op_id: 1, name: "Проверить ценники сканером (ТСД)" },
  { wt_id: 4, lama_z_id: 4, op_id: 3, name: "Проверка сроков годности" },
  { wt_id: 4, lama_z_id: 4, op_id: 4, name: "Старый товар вперёд (по сроку годности)" },
  { wt_id: 4, lama_z_id: 4, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 4, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 25, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 25, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 26, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 29, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 1, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 1, op_id: 7, name: "Выкладка товара" },
  { wt_id: 4, lama_z_id: 1, op_id: 5, name: "Набор товара с паллеты" },
  { wt_id: 4, lama_z_id: 1, op_id: 1, name: "Проверить ценники сканером (ТСД)" },
  { wt_id: 4, lama_z_id: 1, op_id: 3, name: "Проверка сроков годности" },
  { wt_id: 4, lama_z_id: 1, op_id: 4, name: "Старый товар вперёд (по сроку годности)" },
  { wt_id: 4, lama_z_id: 1, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 1, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 2, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 2, op_id: 7, name: "Выкладка товара" },
  { wt_id: 4, lama_z_id: 2, op_id: 5, name: "Набор товара с паллеты" },
  { wt_id: 4, lama_z_id: 2, op_id: 1, name: "Проверить ценники сканером (ТСД)" },
  { wt_id: 4, lama_z_id: 2, op_id: 3, name: "Проверка сроков годности" },
  { wt_id: 4, lama_z_id: 2, op_id: 4, name: "Старый товар вперёд (по сроку годности)" },
  { wt_id: 4, lama_z_id: 2, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 2, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 12, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 4, lama_z_id: 12, op_id: 7, name: "Выкладка товара" },
  { wt_id: 4, lama_z_id: 12, op_id: 5, name: "Набор товара с паллеты" },
  { wt_id: 4, lama_z_id: 12, op_id: 1, name: "Проверить ценники сканером (ТСД)" },
  { wt_id: 4, lama_z_id: 12, op_id: 3, name: "Проверка сроков годности" },
  { wt_id: 4, lama_z_id: 12, op_id: 4, name: "Старый товар вперёд (по сроку годности)" },
  { wt_id: 4, lama_z_id: 12, op_id: 13, name: "Установить или обновить промо-материалы" },
  { wt_id: 4, lama_z_id: 12, op_id: 8, name: "Подровнять товар на полке" },
  { wt_id: 4, lama_z_id: 31, op_id: 6, name: "Вывезти товар со склада" },
  { wt_id: 7, lama_z_id: 15, op_id: 276, name: "Выкладка Дмп" },
  { wt_id: 7, lama_z_id: 15, op_id: 271, name: "Работа с категорией колбаса" },
  { wt_id: 7, lama_z_id: 15, op_id: 270, name: "Работа с категорией молоко" },
  { wt_id: 7, lama_z_id: 15, op_id: 267, name: "Передача зоны" },
  { wt_id: 7, lama_z_id: 15, op_id: 272, name: "Работа на складе" },
  { wt_id: 7, lama_z_id: 11, op_id: 11, name: "Вернуть на склад невыложенный товар" },
  { wt_id: 7, lama_z_id: 11, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 11, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 11, op_id: 9, name: "Уборка на полках" },
  { wt_id: 7, lama_z_id: 13, op_id: 11, name: "Вернуть на склад невыложенный товар" },
  { wt_id: 7, lama_z_id: 13, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 13, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 13, op_id: 9, name: "Уборка на полках" },
  { wt_id: 7, lama_z_id: 6, op_id: 11, name: "Вернуть на склад невыложенный товар" },
  { wt_id: 7, lama_z_id: 6, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 6, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 6, op_id: 9, name: "Уборка на полках" },
  { wt_id: 7, lama_z_id: 10, op_id: 11, name: "Вернуть на склад невыложенный товар" },
  { wt_id: 7, lama_z_id: 10, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 10, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 10, op_id: 9, name: "Уборка на полках" },
  { wt_id: 7, lama_z_id: 16, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 16, op_id: 223, name: "Уборка пола и проходов" },
  { wt_id: 7, lama_z_id: 16, op_id: 224, name: "Уборка санузлов" },
  { wt_id: 7, lama_z_id: 9, op_id: 11, name: "Вернуть на склад невыложенный товар" },
  { wt_id: 7, lama_z_id: 9, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 9, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 9, op_id: 9, name: "Уборка на полках" },
  { wt_id: 7, lama_z_id: 14, op_id: 11, name: "Вернуть на склад невыложенный товар" },
  { wt_id: 7, lama_z_id: 14, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 14, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 14, op_id: 9, name: "Уборка на полках" },
  { wt_id: 7, lama_z_id: 18, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 18, op_id: 223, name: "Уборка пола и проходов" },
  { wt_id: 7, lama_z_id: 18, op_id: 224, name: "Уборка санузлов" },
  { wt_id: 7, lama_z_id: 19, op_id: 173, name: "Перенести товар между зонами" },
  { wt_id: 7, lama_z_id: 19, op_id: 174, name: "Подготовить возврат поставщику" },
  { wt_id: 7, lama_z_id: 19, op_id: 169, name: "Приёмка товара (документы, качество, количество)" },
  { wt_id: 7, lama_z_id: 19, op_id: 170, name: "Разгрузка и погрузка на рампе" },
  { wt_id: 7, lama_z_id: 19, op_id: 171, name: "Расставить товар на складских местах" },
  { wt_id: 7, lama_z_id: 19, op_id: 175, name: "Помыть и обработать оборудование" },
  { wt_id: 7, lama_z_id: 5, op_id: 11, name: "Вернуть на склад невыложенный товар" },
  { wt_id: 7, lama_z_id: 5, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 5, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 5, op_id: 9, name: "Уборка на полках" },
  { wt_id: 7, lama_z_id: 21, op_id: 7, name: "Выкладка товара" },
  { wt_id: 7, lama_z_id: 21, op_id: 190, name: "Проверить температуру в витринах и камерах" },
  { wt_id: 7, lama_z_id: 21, op_id: 175, name: "Помыть и обработать оборудование" },
  { wt_id: 7, lama_z_id: 21, op_id: 209, name: "Фасовка и маркировка (вес, этикетка)" },
  { wt_id: 7, lama_z_id: 22, op_id: 190, name: "Проверить температуру в витринах и камерах" },
  { wt_id: 7, lama_z_id: 22, op_id: 171, name: "Расставить товар на складских местах" },
  { wt_id: 7, lama_z_id: 23, op_id: 7, name: "Выкладка товара" },
  { wt_id: 7, lama_z_id: 23, op_id: 190, name: "Проверить температуру в витринах и камерах" },
  { wt_id: 7, lama_z_id: 23, op_id: 175, name: "Помыть и обработать оборудование" },
  { wt_id: 7, lama_z_id: 23, op_id: 209, name: "Фасовка и маркировка (вес, этикетка)" },
  { wt_id: 7, lama_z_id: 3, op_id: 11, name: "Вернуть на склад невыложенный товар" },
  { wt_id: 7, lama_z_id: 3, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 3, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 3, op_id: 9, name: "Уборка на полках" },
  { wt_id: 7, lama_z_id: 24, op_id: 7, name: "Выкладка товара" },
  { wt_id: 7, lama_z_id: 24, op_id: 175, name: "Помыть и обработать оборудование" },
  { wt_id: 7, lama_z_id: 24, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 24, op_id: 209, name: "Фасовка и маркировка (вес, этикетка)" },
  { wt_id: 7, lama_z_id: 4, op_id: 11, name: "Вернуть на склад невыложенный товар" },
  { wt_id: 7, lama_z_id: 4, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 4, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 4, op_id: 9, name: "Уборка на полках" },
  { wt_id: 7, lama_z_id: 26, op_id: 173, name: "Перенести товар между зонами" },
  { wt_id: 7, lama_z_id: 26, op_id: 174, name: "Подготовить возврат поставщику" },
  { wt_id: 7, lama_z_id: 26, op_id: 169, name: "Приёмка товара (документы, качество, количество)" },
  { wt_id: 7, lama_z_id: 26, op_id: 170, name: "Разгрузка и погрузка на рампе" },
  { wt_id: 7, lama_z_id: 26, op_id: 171, name: "Расставить товар на складских местах" },
  { wt_id: 7, lama_z_id: 26, op_id: 175, name: "Помыть и обработать оборудование" },
  { wt_id: 7, lama_z_id: 27, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 27, op_id: 223, name: "Уборка пола и проходов" },
  { wt_id: 7, lama_z_id: 27, op_id: 224, name: "Уборка санузлов" },
  { wt_id: 7, lama_z_id: 28, op_id: 206, name: "Выдача онлайн-заказов" },
  { wt_id: 7, lama_z_id: 28, op_id: 198, name: "Оформить возврат покупателю" },
  { wt_id: 7, lama_z_id: 28, op_id: 207, name: "Сборка онлайн-заказов" },
  { wt_id: 7, lama_z_id: 29, op_id: 173, name: "Перенести товар между зонами" },
  { wt_id: 7, lama_z_id: 29, op_id: 174, name: "Подготовить возврат поставщику" },
  { wt_id: 7, lama_z_id: 29, op_id: 169, name: "Приёмка товара (документы, качество, количество)" },
  { wt_id: 7, lama_z_id: 29, op_id: 170, name: "Разгрузка и погрузка на рампе" },
  { wt_id: 7, lama_z_id: 29, op_id: 171, name: "Расставить товар на складских местах" },
  { wt_id: 7, lama_z_id: 29, op_id: 175, name: "Помыть и обработать оборудование" },
  { wt_id: 7, lama_z_id: 1, op_id: 11, name: "Вернуть на склад невыложенный товар" },
  { wt_id: 7, lama_z_id: 1, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 1, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 1, op_id: 9, name: "Уборка на полках" },
  { wt_id: 7, lama_z_id: 2, op_id: 11, name: "Вернуть на склад невыложенный товар" },
  { wt_id: 7, lama_z_id: 2, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 2, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 2, op_id: 9, name: "Уборка на полках" },
  { wt_id: 7, lama_z_id: 12, op_id: 11, name: "Вернуть на склад невыложенный товар" },
  { wt_id: 7, lama_z_id: 12, op_id: 10, name: "Вынести мусор из зоны" },
  { wt_id: 7, lama_z_id: 12, op_id: 12, name: "Списание просрочки и брака" },
  { wt_id: 7, lama_z_id: 12, op_id: 9, name: "Уборка на полках" },
  { wt_id: 7, lama_z_id: 31, op_id: 190, name: "Проверить температуру в витринах и камерах" },
  { wt_id: 7, lama_z_id: 31, op_id: 171, name: "Расставить товар на складских местах" },
  { wt_id: 6, lama_z_id: 11, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 11, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 6, lama_z_id: 13, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 13, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 6, lama_z_id: 6, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 6, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 6, lama_z_id: 10, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 10, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 6, lama_z_id: 9, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 9, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 6, lama_z_id: 14, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 14, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 6, lama_z_id: 5, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 5, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 6, lama_z_id: 3, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 3, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 6, lama_z_id: 4, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 4, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 6, lama_z_id: 29, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 29, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 6, lama_z_id: 1, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 1, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 6, lama_z_id: 2, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 2, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 6, lama_z_id: 12, op_id: 233, name: "Подготовка к полной инвентаризации" },
  { wt_id: 6, lama_z_id: 12, op_id: 232, name: "Точечная инвентаризация" },
  { wt_id: 2, lama_z_id: 20, op_id: 197, name: "Обслуживание покупателя на кассе" },
  { wt_id: 2, lama_z_id: 20, op_id: 196, name: "Открыть или закрыть кассовую смену" },
  { wt_id: 2, lama_z_id: 20, op_id: 198, name: "Оформить возврат покупателю" },
  { wt_id: 2, lama_z_id: 20, op_id: 199, name: "Сверка кассы" },
  { wt_id: 3, lama_z_id: 17, op_id: 202, name: "Помочь покупателю на КСО" },
  { wt_id: 3, lama_z_id: 17, op_id: 203, name: "Пополнить расходники на КСО" },
  { wt_id: 1, lama_z_id: 11, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 13, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 6, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 10, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 16, op_id: 201, name: "Планёрка со сменой" },
  { wt_id: 1, lama_z_id: 16, op_id: 261, name: "Заказ товара для пополнения" },
  { wt_id: 1, lama_z_id: 16, op_id: 204, name: "Проверка от воровства" },
  { wt_id: 1, lama_z_id: 16, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 9, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 14, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 20, op_id: 201, name: "Планёрка со сменой" },
  { wt_id: 1, lama_z_id: 20, op_id: 200, name: "Инкассация (выемка наличных)" },
  { wt_id: 1, lama_z_id: 5, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 3, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 4, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 30, op_id: 201, name: "Планёрка со сменой" },
  { wt_id: 1, lama_z_id: 30, op_id: 261, name: "Заказ товара для пополнения" },
  { wt_id: 1, lama_z_id: 30, op_id: 204, name: "Проверка от воровства" },
  { wt_id: 1, lama_z_id: 30, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 1, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 2, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 1, lama_z_id: 12, op_id: 14, name: "Проверить выкладку по планограмме" },
  { wt_id: 5, lama_z_id: 11, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 5, lama_z_id: 13, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 5, lama_z_id: 6, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 5, lama_z_id: 10, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 5, lama_z_id: 9, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 5, lama_z_id: 14, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 5, lama_z_id: 5, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 5, lama_z_id: 3, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 5, lama_z_id: 4, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 5, lama_z_id: 25, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 5, lama_z_id: 1, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 5, lama_z_id: 2, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 5, lama_z_id: 12, op_id: 2, name: "Печать и замена ценников" },
  { wt_id: 8, lama_z_id: 18, op_id: 266, name: "Перерыв" },
];

/** Lookup: операции по (wt_id, lama_z_id). */
export function getOperationsForWtZone(wt_id: number, lama_z_id: number): LamaOperation[] {
  return LAMA_OPERATIONS.filter((o) => o.wt_id === wt_id && o.lama_z_id === lama_z_id);
}