/**
 * AUTO-GENERATED by tools/lama/build-review-tasks.py — do not edit by hand.
 *
 * Реальные LAMA-задачи которые сейчас в очереди на проверку менеджером
 * (status="Completed" → review_state="ON_REVIEW") + история принятых /
 * отклонённых. Подключается в `lib/mock-data/tasks.ts` через spread,
 * поэтому `getTasks({review_state: "ON_REVIEW"})` сразу видит их.
 *
 * Source snapshot: 2026-05-19
 * Built at: 2026-05-19T00:03:12Z
 *
 * 2 ON_REVIEW + 0 ACCEPTED + 0 REJECTED across 1 shops.
 *
 * Регенерируется:
 *   - daily (cron-daily.sh) после fetch-snapshot-async.py
 *   - hourly (refresh-review-statuses.sh) после refresh статусов task'ов
 */
import type { Task } from "@/lib/types";

export const REAL_LAMA_REVIEW_TASKS: Task[] = [
  { id: "task-lama-review-316294", external_id: 316294, title: "Переоценка", description: "Переоценка", type: "PLANNED", kind: "SINGLE", source: "PLANNED", store_id: 211, store_name: "У-03 Фрунзе 120 (ИР)", zone_id: 112, zone_name: "Без зоны", work_type_id: 5, work_type_name: "Переоценка", priority: 1, editable_by_store: false, creator_id: 1, creator_name: "Директор магазина", assignee_id: 437, assignee_name: "Райхе Наталья Анатольевна", assigned_to_permission: null, state: "COMPLETED", review_state: "ON_REVIEW", acceptance_policy: "MANUAL", requires_photo: false, archived: false, planned_minutes: 20, time_start: "07:00:00", time_end: "07:20:00", shift_id: 5728172, created_at: "2026-05-19T07:00:00+07:00", updated_at: "2026-05-19T07:20:00+07:00" },
  { id: "task-lama-review-316295", external_id: 316295, title: "Выкладка: Фреш 1", description: "Выкладка в зоне «Фреш 1»", type: "PLANNED", kind: "SINGLE", source: "PLANNED", store_id: 211, store_name: "У-03 Фрунзе 120 (ИР)", zone_id: 100, zone_name: "Фреш 1", work_type_id: 4, work_type_name: "Выкладка", priority: 2, editable_by_store: false, creator_id: 1, creator_name: "Директор магазина", assignee_id: 437, assignee_name: "Райхе Наталья Анатольевна", assigned_to_permission: null, state: "COMPLETED", review_state: "ON_REVIEW", acceptance_policy: "MANUAL", requires_photo: false, archived: false, planned_minutes: 30, time_start: "07:20:00", time_end: "07:50:00", shift_id: 5728172, created_at: "2026-05-19T07:20:00+07:00", updated_at: "2026-05-19T07:50:00+07:00" },
];

export const REVIEW_TASKS_BUILT_AT = "2026-05-19T00:03:12Z";
export const REVIEW_TASKS_SOURCE_DATE = "2026-05-19";
