/**
 * AUTO-GENERATED by tools/lama/build-planning-pool.py — do not edit by hand.
 *
 * Daily reverse-distribution: today's LAMA tasks без assignee, готовые для
 * нашего auto-distribute UI demo. Берём задачи которые сегодня уже были
 * распределены LAMA (status ∈ {Created, InProgress, Suspended}), стрипаем
 * employee_id / employee_name / eis_id и группируем по магазину. Сравнить
 * с реальным распределением можно через `_lama-real.ts` и связанные моки.
 *
 * Source snapshot: 2026-09-04
 * Built at: 2026-09-03T22:05:27Z
 *
 * 0 shops, 0 tasks-to-distribute, 0 available-employees.
 */

export interface PlanningTask {
  id: number;
  priority: number;
  operation_work: string;
  operation_zone: string | null;
  category: string | null;
  duration: number;
  time_start: string;
  time_end: string;
  status: string;
  shop_code: string;
  shop_name: string;
  shift_id: number | null;
}

export interface PlanningEmployee {
  employee_id: number;
  name: string;
  eis_id: number | null;
  position_role: string;
  position_name: string;
  rank: string;
}

export interface ShopPlanningPool {
  shop_name: string;
  tasks_to_distribute: PlanningTask[];
  available_employees: PlanningEmployee[];
}

export const LAMA_PLANNING_POOL: Record<string, ShopPlanningPool> = {
};

export const PLANNING_POOL_BUILT_AT = "2026-09-03T22:05:27Z";
export const PLANNING_POOL_SOURCE_DATE = "2026-09-04";
