/**
 * РЕАЛЬНЫЕ подсказки LAMA (источник: prod БД).
 *
 * 522 подсказок keyed by (wt_id, lama_z_id).
 * Hint ID = orig_hint_id + 1000 чтоб не пересекаться с base MOCK_HINTS (1-30).
 *
 * Используется как spread в lib/mock-data/hints.ts → MOCK_HINTS.
 */

import type { Hint } from "@/lib/types";

const LAMA_HINT_DATE = "2026-05-07T06:00:00+07:00";

export const REAL_LAMA_HINTS: Hint[] = [
  { id: 1019, work_type_id: 4, zone_id: 105, text: "В ТСД «Контроль ценников» отсканируй товар прямо на полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1022, work_type_id: 4, zone_id: 105, text: "Если есть маркировка партии, убедись, что она рядом и соответствует товару", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1023, work_type_id: 4, zone_id: 105, text: "Если ценник пропал или повреждён, сразу распечатай новый и замени", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1024, work_type_id: 4, zone_id: 105, text: "После замены пересканируй несколько товаров, чтобы проверить совпадение", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1020, work_type_id: 4, zone_id: 105, text: "Проверь, что ценник стоит под тем же товаром и не перепутан", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1021, work_type_id: 4, zone_id: 105, text: "Сверь обычную цену и цену по карте, если она есть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1007, work_type_id: 4, zone_id: 106, text: "В ТСД «Контроль ценников» отсканируй товар прямо на полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1010, work_type_id: 4, zone_id: 106, text: "Если есть маркировка партии, убедись, что она рядом и соответствует товару", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1011, work_type_id: 4, zone_id: 106, text: "Если ценник пропал или повреждён, сразу распечатай новый и замени", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1012, work_type_id: 4, zone_id: 106, text: "После замены пересканируй несколько товаров, чтобы проверить совпадение", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1008, work_type_id: 4, zone_id: 106, text: "Проверь, что ценник стоит под тем же товаром и не перепутан", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1009, work_type_id: 4, zone_id: 106, text: "Сверь обычную цену и цену по карте, если она есть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1037, work_type_id: 4, zone_id: 102, text: "В ТСД «Контроль ценников» отсканируй товар прямо на полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1040, work_type_id: 4, zone_id: 102, text: "Если есть маркировка партии, убедись, что она рядом и соответствует товару", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1041, work_type_id: 4, zone_id: 102, text: "Если ценник пропал или повреждён, сразу распечатай новый и замени", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1042, work_type_id: 4, zone_id: 102, text: "После замены пересканируй несколько товаров, чтобы проверить совпадение", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1038, work_type_id: 4, zone_id: 102, text: "Проверь, что ценник стоит под тем же товаром и не перепутан", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1039, work_type_id: 4, zone_id: 102, text: "Сверь обычную цену и цену по карте, если она есть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1025, work_type_id: 4, zone_id: 104, text: "В ТСД «Контроль ценников» отсканируй товар прямо на полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1028, work_type_id: 4, zone_id: 104, text: "Если есть маркировка партии, убедись, что она рядом и соответствует товару", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1029, work_type_id: 4, zone_id: 104, text: "Если ценник пропал или повреждён, сразу распечатай новый и замени", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1030, work_type_id: 4, zone_id: 104, text: "После замены пересканируй несколько товаров, чтобы проверить совпадение", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1026, work_type_id: 4, zone_id: 104, text: "Проверь, что ценник стоит под тем же товаром и не перепутан", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1027, work_type_id: 4, zone_id: 104, text: "Сверь обычную цену и цену по карте, если она есть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1031, work_type_id: 4, zone_id: 103, text: "В ТСД «Контроль ценников» отсканируй товар прямо на полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1034, work_type_id: 4, zone_id: 103, text: "Если есть маркировка партии, убедись, что она рядом и соответствует товару", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1035, work_type_id: 4, zone_id: 103, text: "Если ценник пропал или повреждён, сразу распечатай новый и замени", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1036, work_type_id: 4, zone_id: 103, text: "После замены пересканируй несколько товаров, чтобы проверить совпадение", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1032, work_type_id: 4, zone_id: 103, text: "Проверь, что ценник стоит под тем же товаром и не перепутан", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1033, work_type_id: 4, zone_id: 103, text: "Сверь обычную цену и цену по карте, если она есть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1001, work_type_id: 4, zone_id: 107, text: "В ТСД «Контроль ценников» отсканируй товар прямо на полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1004, work_type_id: 4, zone_id: 107, text: "Если есть маркировка партии, убедись, что она рядом и соответствует товару", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1005, work_type_id: 4, zone_id: 107, text: "Если ценник пропал или повреждён, сразу распечатай новый и замени", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1006, work_type_id: 4, zone_id: 107, text: "После замены пересканируй несколько товаров, чтобы проверить совпадение", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1002, work_type_id: 4, zone_id: 107, text: "Проверь, что ценник стоит под тем же товаром и не перепутан", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1003, work_type_id: 4, zone_id: 107, text: "Сверь обычную цену и цену по карте, если она есть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1175, work_type_id: 4, zone_id: 116, text: "Бери товар со своего места хранения, перед выходом проверь качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1180, work_type_id: 4, zone_id: 116, text: "Порченный товар рядом с хорошим не держи", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1176, work_type_id: 4, zone_id: 116, text: "Нежный товар переноси небольшими партиями, чтобы не помять", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1179, work_type_id: 4, zone_id: 116, text: "Остатки верни в подсобку, соблюдай условия хранения", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1177, work_type_id: 4, zone_id: 116, text: "Пополни лотки равномерно, верхний слой не перегружай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1178, work_type_id: 4, zone_id: 116, text: "Старый товар вперёд, новый сзади. Партии не смешивай, если запрещено", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1043, work_type_id: 4, zone_id: 108, text: "В ТСД «Контроль ценников» отсканируй товар прямо на полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1046, work_type_id: 4, zone_id: 108, text: "Если есть маркировка партии, убедись, что она рядом и соответствует товару", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1047, work_type_id: 4, zone_id: 108, text: "Если ценник пропал или повреждён, сразу распечатай новый и замени", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1048, work_type_id: 4, zone_id: 108, text: "После замены пересканируй несколько товаров, чтобы проверить совпадение", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1044, work_type_id: 4, zone_id: 108, text: "Проверь, что ценник стоит под тем же товаром и не перепутан", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1045, work_type_id: 4, zone_id: 108, text: "Сверь обычную цену и цену по карте, если она есть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1169, work_type_id: 4, zone_id: 119, text: "Бери товар со своего места хранения, перед выходом проверь качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1174, work_type_id: 4, zone_id: 119, text: "Порченный товар рядом с хорошим не держи", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1170, work_type_id: 4, zone_id: 119, text: "Нежный товар переноси небольшими партиями, чтобы не помять", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1173, work_type_id: 4, zone_id: 119, text: "Остатки верни в подсобку, соблюдай условия хранения", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1171, work_type_id: 4, zone_id: 119, text: "Пополни лотки равномерно, верхний слой не перегружай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1172, work_type_id: 4, zone_id: 119, text: "Старый товар вперёд, новый сзади. Партии не смешивай, если запрещено", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1055, work_type_id: 4, zone_id: 110, text: "В ТСД «Контроль ценников» отсканируй товар прямо на полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1058, work_type_id: 4, zone_id: 110, text: "Если есть маркировка партии, убедись, что она рядом и соответствует товару", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1059, work_type_id: 4, zone_id: 110, text: "Если ценник пропал или повреждён, сразу распечатай новый и замени", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1060, work_type_id: 4, zone_id: 110, text: "После замены пересканируй несколько товаров, чтобы проверить совпадение", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1056, work_type_id: 4, zone_id: 110, text: "Проверь, что ценник стоит под тем же товаром и не перепутан", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1057, work_type_id: 4, zone_id: 110, text: "Сверь обычную цену и цену по карте, если она есть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1049, work_type_id: 4, zone_id: 109, text: "В ТСД «Контроль ценников» отсканируй товар прямо на полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1052, work_type_id: 4, zone_id: 109, text: "Если есть маркировка партии, убедись, что она рядом и соответствует товару", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1053, work_type_id: 4, zone_id: 109, text: "Если ценник пропал или повреждён, сразу распечатай новый и замени", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1054, work_type_id: 4, zone_id: 109, text: "После замены пересканируй несколько товаров, чтобы проверить совпадение", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1050, work_type_id: 4, zone_id: 109, text: "Проверь, что ценник стоит под тем же товаром и не перепутан", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1051, work_type_id: 4, zone_id: 109, text: "Сверь обычную цену и цену по карте, если она есть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1204, work_type_id: 4, zone_id: 122, text: "В конце быстро перебери верхний слой и сними брак", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1199, work_type_id: 4, zone_id: 122, text: "Подвинь товар к краю и выровняй передний ряд по всей полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1203, work_type_id: 4, zone_id: 122, text: "Проверь, что ценники читаются и стоят под правильным товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1202, work_type_id: 4, zone_id: 122, text: "Убери грязную тару и замени её на чистую", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1200, work_type_id: 4, zone_id: 122, text: "Убери пустоты подтоваркой и равномерной раскладкой", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1201, work_type_id: 4, zone_id: 122, text: "С нежным товаром не дави сильно при выравнивании", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1163, work_type_id: 4, zone_id: 123, text: "Бери товар со своего места хранения, перед выходом проверь качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1168, work_type_id: 4, zone_id: 123, text: "Порченный товар рядом с хорошим не держи", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1164, work_type_id: 4, zone_id: 123, text: "Нежный товар переноси небольшими партиями, чтобы не помять", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1167, work_type_id: 4, zone_id: 123, text: "Остатки верни в подсобку, соблюдай условия хранения", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1165, work_type_id: 4, zone_id: 123, text: "Пополни лотки равномерно, верхний слой не перегружай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1166, work_type_id: 4, zone_id: 123, text: "Старый товар вперёд, новый сзади. Партии не смешивай, если запрещено", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1157, work_type_id: 4, zone_id: 126, text: "Бери товар со своего места хранения, перед выходом проверь качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1162, work_type_id: 4, zone_id: 126, text: "Порченный товар рядом с хорошим не держи", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1158, work_type_id: 4, zone_id: 126, text: "Нежный товар переноси небольшими партиями, чтобы не помять", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1161, work_type_id: 4, zone_id: 126, text: "Остатки верни в подсобку, соблюдай условия хранения", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1159, work_type_id: 4, zone_id: 126, text: "Пополни лотки равномерно, верхний слой не перегружай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1160, work_type_id: 4, zone_id: 126, text: "Старый товар вперёд, новый сзади. Партии не смешивай, если запрещено", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1067, work_type_id: 4, zone_id: 100, text: "В ТСД «Контроль ценников» отсканируй товар прямо на полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1070, work_type_id: 4, zone_id: 100, text: "Если есть маркировка партии, убедись, что она рядом и соответствует товару", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1071, work_type_id: 4, zone_id: 100, text: "Если ценник пропал или повреждён, сразу распечатай новый и замени", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1072, work_type_id: 4, zone_id: 100, text: "После замены пересканируй несколько товаров, чтобы проверить совпадение", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1068, work_type_id: 4, zone_id: 100, text: "Проверь, что ценник стоит под тем же товаром и не перепутан", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1069, work_type_id: 4, zone_id: 100, text: "Сверь обычную цену и цену по карте, если она есть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1061, work_type_id: 4, zone_id: 101, text: "В ТСД «Контроль ценников» отсканируй товар прямо на полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1064, work_type_id: 4, zone_id: 101, text: "Если есть маркировка партии, убедись, что она рядом и соответствует товару", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1065, work_type_id: 4, zone_id: 101, text: "Если ценник пропал или повреждён, сразу распечатай новый и замени", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1066, work_type_id: 4, zone_id: 101, text: "После замены пересканируй несколько товаров, чтобы проверить совпадение", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1062, work_type_id: 4, zone_id: 101, text: "Проверь, что ценник стоит под тем же товаром и не перепутан", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1063, work_type_id: 4, zone_id: 101, text: "Сверь обычную цену и цену по карте, если она есть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1013, work_type_id: 4, zone_id: 111, text: "В ТСД «Контроль ценников» отсканируй товар прямо на полке", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1016, work_type_id: 4, zone_id: 111, text: "Если есть маркировка партии, убедись, что она рядом и соответствует товару", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1017, work_type_id: 4, zone_id: 111, text: "Если ценник пропал или повреждён, сразу распечатай новый и замени", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1018, work_type_id: 4, zone_id: 111, text: "После замены пересканируй несколько товаров, чтобы проверить совпадение", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1014, work_type_id: 4, zone_id: 111, text: "Проверь, что ценник стоит под тем же товаром и не перепутан", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1015, work_type_id: 4, zone_id: 111, text: "Сверь обычную цену и цену по карте, если она есть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1151, work_type_id: 4, zone_id: 128, text: "Бери товар со своего места хранения, перед выходом проверь качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1156, work_type_id: 4, zone_id: 128, text: "Порченный товар рядом с хорошим не держи", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1152, work_type_id: 4, zone_id: 128, text: "Нежный товар переноси небольшими партиями, чтобы не помять", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1155, work_type_id: 4, zone_id: 128, text: "Остатки верни в подсобку, соблюдай условия хранения", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1153, work_type_id: 4, zone_id: 128, text: "Пополни лотки равномерно, верхний слой не перегружай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1154, work_type_id: 4, zone_id: 128, text: "Старый товар вперёд, новый сзади. Партии не смешивай, если запрещено", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1518, work_type_id: 7, zone_id: 112, text: "Передай ключи, доступы и инвентарь, если это нужно", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1519, work_type_id: 7, zone_id: 112, text: "Покажи проблемные места: просрочка, брак, пустоты", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1522, work_type_id: 7, zone_id: 112, text: "После передачи убедись, что зона под контролем", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1517, work_type_id: 7, zone_id: 112, text: "Сообщи коллеге, что уже сделано и что осталось", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1520, work_type_id: 7, zone_id: 112, text: "Укажи, где лежит подтоварка и что нужно пополнить", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1521, work_type_id: 7, zone_id: 112, text: "Уточни, кто отвечает за клиентов и кассы на время передачи", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1223, work_type_id: 7, zone_id: 105, text: "Выкладывай по планограмме, в одном ящике разные размеры лотков не смешивай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1225, work_type_id: 7, zone_id: 105, text: "Держи фронт полки ровным, чтобы товар был виден покупателю", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1228, work_type_id: 7, zone_id: 105, text: "Если есть пустоты, добавь товар или подтяни вперёд", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1227, work_type_id: 7, zone_id: 105, text: "На промо местах тоже соблюдай ротацию и качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1226, work_type_id: 7, zone_id: 105, text: "Ценник ставь строго под этот товар, штрихкод не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1224, work_type_id: 7, zone_id: 105, text: "Ящики ставь ровно, чтобы не помялся товар", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1211, work_type_id: 7, zone_id: 106, text: "Выкладывай по планограмме, в одном ящике разные размеры лотков не смешивай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1213, work_type_id: 7, zone_id: 106, text: "Держи фронт полки ровным, чтобы товар был виден покупателю", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1216, work_type_id: 7, zone_id: 106, text: "Если есть пустоты, добавь товар или подтяни вперёд", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1215, work_type_id: 7, zone_id: 106, text: "На промо местах тоже соблюдай ротацию и качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1214, work_type_id: 7, zone_id: 106, text: "Ценник ставь строго под этот товар, штрихкод не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1212, work_type_id: 7, zone_id: 106, text: "Ящики ставь ровно, чтобы не помялся товар", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1241, work_type_id: 7, zone_id: 102, text: "Выкладывай по планограмме, в одном ящике разные размеры лотков не смешивай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1243, work_type_id: 7, zone_id: 102, text: "Держи фронт полки ровным, чтобы товар был виден покупателю", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1246, work_type_id: 7, zone_id: 102, text: "Если есть пустоты, добавь товар или подтяни вперёд", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1245, work_type_id: 7, zone_id: 102, text: "На промо местах тоже соблюдай ротацию и качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1244, work_type_id: 7, zone_id: 102, text: "Ценник ставь строго под этот товар, штрихкод не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1242, work_type_id: 7, zone_id: 102, text: "Ящики ставь ровно, чтобы не помялся товар", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1229, work_type_id: 7, zone_id: 104, text: "Выкладывай по планограмме, в одном ящике разные размеры лотков не смешивай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1231, work_type_id: 7, zone_id: 104, text: "Держи фронт полки ровным, чтобы товар был виден покупателю", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1234, work_type_id: 7, zone_id: 104, text: "Если есть пустоты, добавь товар или подтяни вперёд", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1233, work_type_id: 7, zone_id: 104, text: "На промо местах тоже соблюдай ротацию и качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1232, work_type_id: 7, zone_id: 104, text: "Ценник ставь строго под этот товар, штрихкод не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1230, work_type_id: 7, zone_id: 104, text: "Ящики ставь ровно, чтобы не помялся товар", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1293, work_type_id: 7, zone_id: 113, text: "В конце осмотри зону и убери мелкий мусор", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1291, work_type_id: 7, zone_id: 113, text: "Вывези мусор в служебную зону и поставь новый пакет", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1290, work_type_id: 7, zone_id: 113, text: "Мусор на полу и в проходах не оставляй", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1294, work_type_id: 7, zone_id: 113, text: "Помой руки после работы с мусором", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1289, work_type_id: 7, zone_id: 113, text: "Сразу убирай короб и плёнку, чтобы не было бардака", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1292, work_type_id: 7, zone_id: 113, text: "Убери плёнку и картон из тары, чтобы тара была чистой", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1235, work_type_id: 7, zone_id: 103, text: "Выкладывай по планограмме, в одном ящике разные размеры лотков не смешивай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1237, work_type_id: 7, zone_id: 103, text: "Держи фронт полки ровным, чтобы товар был виден покупателю", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1240, work_type_id: 7, zone_id: 103, text: "Если есть пустоты, добавь товар или подтяни вперёд", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1239, work_type_id: 7, zone_id: 103, text: "На промо местах тоже соблюдай ротацию и качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1238, work_type_id: 7, zone_id: 103, text: "Ценник ставь строго под этот товар, штрихкод не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1236, work_type_id: 7, zone_id: 103, text: "Ящики ставь ровно, чтобы не помялся товар", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1205, work_type_id: 7, zone_id: 107, text: "Выкладывай по планограмме, в одном ящике разные размеры лотков не смешивай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1207, work_type_id: 7, zone_id: 107, text: "Держи фронт полки ровным, чтобы товар был виден покупателю", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1210, work_type_id: 7, zone_id: 107, text: "Если есть пустоты, добавь товар или подтяни вперёд", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1209, work_type_id: 7, zone_id: 107, text: "На промо местах тоже соблюдай ротацию и качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1208, work_type_id: 7, zone_id: 107, text: "Ценник ставь строго под этот товар, штрихкод не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1206, work_type_id: 7, zone_id: 107, text: "Ящики ставь ровно, чтобы не помялся товар", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1287, work_type_id: 7, zone_id: 115, text: "В конце осмотри зону и убери мелкий мусор", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1285, work_type_id: 7, zone_id: 115, text: "Вывези мусор в служебную зону и поставь новый пакет", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1284, work_type_id: 7, zone_id: 115, text: "Мусор на полу и в проходах не оставляй", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1288, work_type_id: 7, zone_id: 115, text: "Помой руки после работы с мусором", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1283, work_type_id: 7, zone_id: 115, text: "Сразу убирай короб и плёнку, чтобы не было бардака", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1286, work_type_id: 7, zone_id: 115, text: "Убери плёнку и картон из тары, чтобы тара была чистой", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1395, work_type_id: 7, zone_id: 116, text: "Если есть дефект, сделай фото и передай по регламенту", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1394, work_type_id: 7, zone_id: 116, text: "Если есть массовый дефект, составь акт и товар не выгружай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1393, work_type_id: 7, zone_id: 116, text: "Осмотри паллеты, нет ли завалов и массовых замятий", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1396, work_type_id: 7, zone_id: 116, text: "После фиксации расхождений подпиши документы и поставь печать", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1391, work_type_id: 7, zone_id: 116, text: "Прими у водителя накладные и путевой лист", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1392, work_type_id: 7, zone_id: 116, text: "Сверь адрес на паллете с адресом магазина", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1247, work_type_id: 7, zone_id: 108, text: "Выкладывай по планограмме, в одном ящике разные размеры лотков не смешивай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1249, work_type_id: 7, zone_id: 108, text: "Держи фронт полки ровным, чтобы товар был виден покупателю", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1252, work_type_id: 7, zone_id: 108, text: "Если есть пустоты, добавь товар или подтяни вперёд", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1251, work_type_id: 7, zone_id: 108, text: "На промо местах тоже соблюдай ротацию и качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1250, work_type_id: 7, zone_id: 108, text: "Ценник ставь строго под этот товар, штрихкод не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1248, work_type_id: 7, zone_id: 108, text: "Ящики ставь ровно, чтобы не помялся товар", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1197, work_type_id: 7, zone_id: 118, text: "Акционный товар выделяй жёлтым ценником, если нужно ставь на ДМП", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1195, work_type_id: 7, zone_id: 118, text: "Заполняй лотки минимум на три четверти, чтобы полка выглядела полной", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1194, work_type_id: 7, zone_id: 118, text: "Используй подходящую тару, держи её чистой", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1193, work_type_id: 7, zone_id: 118, text: "Ориентируйся на сезонную планограмму своей зоны", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1198, work_type_id: 7, zone_id: 118, text: "Соблюдай ротацию, брак убирай каждый день", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1196, work_type_id: 7, zone_id: 118, text: "Ценник ставь под товаром и проверяй соответствие", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1405, work_type_id: 7, zone_id: 119, text: "Бытовую химию рядом с продуктами не ставь", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1407, work_type_id: 7, zone_id: 119, text: "Проходы оставь свободными, пути эвакуации не перекрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1408, work_type_id: 7, zone_id: 119, text: "Повреждённую упаковку убери отдельно и сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1403, work_type_id: 7, zone_id: 119, text: "Разложи товар по складским местам, как принято на складе", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1404, work_type_id: 7, zone_id: 119, text: "Режимный товар сразу перенеси в нужную камеру", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1406, work_type_id: 7, zone_id: 119, text: "Тяжёлое ставь вниз, лёгкое сверху", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1191, work_type_id: 7, zone_id: 120, text: "Акционный товар выделяй жёлтым ценником, если нужно ставь на ДМП", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1189, work_type_id: 7, zone_id: 120, text: "Заполняй лотки минимум на три четверти, чтобы полка выглядела полной", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1188, work_type_id: 7, zone_id: 120, text: "Используй подходящую тару, держи её чистой", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1187, work_type_id: 7, zone_id: 120, text: "Ориентируйся на сезонную планограмму своей зоны", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1192, work_type_id: 7, zone_id: 120, text: "Соблюдай ротацию, брак убирай каждый день", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1190, work_type_id: 7, zone_id: 120, text: "Ценник ставь под товаром и проверяй соответствие", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1259, work_type_id: 7, zone_id: 110, text: "Выкладывай по планограмме, в одном ящике разные размеры лотков не смешивай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1261, work_type_id: 7, zone_id: 110, text: "Держи фронт полки ровным, чтобы товар был виден покупателю", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1264, work_type_id: 7, zone_id: 110, text: "Если есть пустоты, добавь товар или подтяни вперёд", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1263, work_type_id: 7, zone_id: 110, text: "На промо местах тоже соблюдай ротацию и качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1262, work_type_id: 7, zone_id: 110, text: "Ценник ставь строго под этот товар, штрихкод не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1260, work_type_id: 7, zone_id: 110, text: "Ящики ставь ровно, чтобы не помялся товар", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1185, work_type_id: 7, zone_id: 121, text: "Акционный товар выделяй жёлтым ценником, если нужно ставь на ДМП", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1183, work_type_id: 7, zone_id: 121, text: "Заполняй лотки минимум на три четверти, чтобы полка выглядела полной", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1182, work_type_id: 7, zone_id: 121, text: "Используй подходящую тару, держи её чистой", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1181, work_type_id: 7, zone_id: 121, text: "Ориентируйся на сезонную планограмму своей зоны", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1186, work_type_id: 7, zone_id: 121, text: "Соблюдай ротацию, брак убирай каждый день", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1184, work_type_id: 7, zone_id: 121, text: "Ценник ставь под товаром и проверяй соответствие", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1253, work_type_id: 7, zone_id: 109, text: "Выкладывай по планограмме, в одном ящике разные размеры лотков не смешивай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1255, work_type_id: 7, zone_id: 109, text: "Держи фронт полки ровным, чтобы товар был виден покупателю", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1258, work_type_id: 7, zone_id: 109, text: "Если есть пустоты, добавь товар или подтяни вперёд", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1257, work_type_id: 7, zone_id: 109, text: "На промо местах тоже соблюдай ротацию и качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1256, work_type_id: 7, zone_id: 109, text: "Ценник ставь строго под этот товар, штрихкод не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1254, work_type_id: 7, zone_id: 109, text: "Ящики ставь ровно, чтобы не помялся товар", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1389, work_type_id: 7, zone_id: 123, text: "Если есть дефект, сделай фото и передай по регламенту", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1388, work_type_id: 7, zone_id: 123, text: "Если есть массовый дефект, составь акт и товар не выгружай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1387, work_type_id: 7, zone_id: 123, text: "Осмотри паллеты, нет ли завалов и массовых замятий", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1390, work_type_id: 7, zone_id: 123, text: "После фиксации расхождений подпиши документы и поставь печать", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1385, work_type_id: 7, zone_id: 123, text: "Прими у водителя накладные и путевой лист", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1386, work_type_id: 7, zone_id: 123, text: "Сверь адрес на паллете с адресом магазина", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1281, work_type_id: 7, zone_id: 124, text: "В конце осмотри зону и убери мелкий мусор", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1279, work_type_id: 7, zone_id: 124, text: "Вывези мусор в служебную зону и поставь новый пакет", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1278, work_type_id: 7, zone_id: 124, text: "Мусор на полу и в проходах не оставляй", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1282, work_type_id: 7, zone_id: 124, text: "Помой руки после работы с мусором", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1277, work_type_id: 7, zone_id: 124, text: "Сразу убирай короб и плёнку, чтобы не было бардака", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1280, work_type_id: 7, zone_id: 124, text: "Убери плёнку и картон из тары, чтобы тара была чистой", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1419, work_type_id: 7, zone_id: 125, text: "Возвратный товар передай в зону возвратов", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1418, work_type_id: 7, zone_id: 125, text: "Деньги возвращай только через кассу, по процедуре", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1420, work_type_id: 7, zone_id: 125, text: "Если сомневаешься, зови старшего кассира", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1417, work_type_id: 7, zone_id: 125, text: "Оформи документы в системе, как требует правило магазина", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1415, work_type_id: 7, zone_id: 125, text: "Проверь чек и товар перед оформлением возврата или обмена", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1416, work_type_id: 7, zone_id: 125, text: "Сверь состояние товара и причину возврата", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1383, work_type_id: 7, zone_id: 126, text: "Если есть дефект, сделай фото и передай по регламенту", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1382, work_type_id: 7, zone_id: 126, text: "Если есть массовый дефект, составь акт и товар не выгружай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1381, work_type_id: 7, zone_id: 126, text: "Осмотри паллеты, нет ли завалов и массовых замятий", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1384, work_type_id: 7, zone_id: 126, text: "После фиксации расхождений подпиши документы и поставь печать", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1379, work_type_id: 7, zone_id: 126, text: "Прими у водителя накладные и путевой лист", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1380, work_type_id: 7, zone_id: 126, text: "Сверь адрес на паллете с адресом магазина", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1271, work_type_id: 7, zone_id: 100, text: "Выкладывай по планограмме, в одном ящике разные размеры лотков не смешивай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1273, work_type_id: 7, zone_id: 100, text: "Держи фронт полки ровным, чтобы товар был виден покупателю", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1276, work_type_id: 7, zone_id: 100, text: "Если есть пустоты, добавь товар или подтяни вперёд", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1275, work_type_id: 7, zone_id: 100, text: "На промо местах тоже соблюдай ротацию и качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1274, work_type_id: 7, zone_id: 100, text: "Ценник ставь строго под этот товар, штрихкод не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1272, work_type_id: 7, zone_id: 100, text: "Ящики ставь ровно, чтобы не помялся товар", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1265, work_type_id: 7, zone_id: 101, text: "Выкладывай по планограмме, в одном ящике разные размеры лотков не смешивай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1267, work_type_id: 7, zone_id: 101, text: "Держи фронт полки ровным, чтобы товар был виден покупателю", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1270, work_type_id: 7, zone_id: 101, text: "Если есть пустоты, добавь товар или подтяни вперёд", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1269, work_type_id: 7, zone_id: 101, text: "На промо местах тоже соблюдай ротацию и качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1268, work_type_id: 7, zone_id: 101, text: "Ценник ставь строго под этот товар, штрихкод не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1266, work_type_id: 7, zone_id: 101, text: "Ящики ставь ровно, чтобы не помялся товар", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1217, work_type_id: 7, zone_id: 111, text: "Выкладывай по планограмме, в одном ящике разные размеры лотков не смешивай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1219, work_type_id: 7, zone_id: 111, text: "Держи фронт полки ровным, чтобы товар был виден покупателю", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1222, work_type_id: 7, zone_id: 111, text: "Если есть пустоты, добавь товар или подтяни вперёд", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1221, work_type_id: 7, zone_id: 111, text: "На промо местах тоже соблюдай ротацию и качество", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1220, work_type_id: 7, zone_id: 111, text: "Ценник ставь строго под этот товар, штрихкод не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1218, work_type_id: 7, zone_id: 111, text: "Ящики ставь ровно, чтобы не помялся товар", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1399, work_type_id: 7, zone_id: 128, text: "Бытовую химию рядом с продуктами не ставь", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1401, work_type_id: 7, zone_id: 128, text: "Проходы оставь свободными, пути эвакуации не перекрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1402, work_type_id: 7, zone_id: 128, text: "Повреждённую упаковку убери отдельно и сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1397, work_type_id: 7, zone_id: 128, text: "Разложи товар по складским местам, как принято на складе", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1398, work_type_id: 7, zone_id: 128, text: "Режимный товар сразу перенеси в нужную камеру", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1400, work_type_id: 7, zone_id: 128, text: "Тяжёлое ставь вниз, лёгкое сверху", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1457, work_type_id: 6, zone_id: 105, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1462, work_type_id: 6, zone_id: 105, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1460, work_type_id: 6, zone_id: 105, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1459, work_type_id: 6, zone_id: 105, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1458, work_type_id: 6, zone_id: 105, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1461, work_type_id: 6, zone_id: 105, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1445, work_type_id: 6, zone_id: 106, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1450, work_type_id: 6, zone_id: 106, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1448, work_type_id: 6, zone_id: 106, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1447, work_type_id: 6, zone_id: 106, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1446, work_type_id: 6, zone_id: 106, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1449, work_type_id: 6, zone_id: 106, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1475, work_type_id: 6, zone_id: 102, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1480, work_type_id: 6, zone_id: 102, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1478, work_type_id: 6, zone_id: 102, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1477, work_type_id: 6, zone_id: 102, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1476, work_type_id: 6, zone_id: 102, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1479, work_type_id: 6, zone_id: 102, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1463, work_type_id: 6, zone_id: 104, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1468, work_type_id: 6, zone_id: 104, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1466, work_type_id: 6, zone_id: 104, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1465, work_type_id: 6, zone_id: 104, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1464, work_type_id: 6, zone_id: 104, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1467, work_type_id: 6, zone_id: 104, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1469, work_type_id: 6, zone_id: 103, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1474, work_type_id: 6, zone_id: 103, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1472, work_type_id: 6, zone_id: 103, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1471, work_type_id: 6, zone_id: 103, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1470, work_type_id: 6, zone_id: 103, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1473, work_type_id: 6, zone_id: 103, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1439, work_type_id: 6, zone_id: 107, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1444, work_type_id: 6, zone_id: 107, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1442, work_type_id: 6, zone_id: 107, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1441, work_type_id: 6, zone_id: 107, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1440, work_type_id: 6, zone_id: 107, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1443, work_type_id: 6, zone_id: 107, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1481, work_type_id: 6, zone_id: 108, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1486, work_type_id: 6, zone_id: 108, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1484, work_type_id: 6, zone_id: 108, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1483, work_type_id: 6, zone_id: 108, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1482, work_type_id: 6, zone_id: 108, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1485, work_type_id: 6, zone_id: 108, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1493, work_type_id: 6, zone_id: 110, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1498, work_type_id: 6, zone_id: 110, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1496, work_type_id: 6, zone_id: 110, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1495, work_type_id: 6, zone_id: 110, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1494, work_type_id: 6, zone_id: 110, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1497, work_type_id: 6, zone_id: 110, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1487, work_type_id: 6, zone_id: 109, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1492, work_type_id: 6, zone_id: 109, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1490, work_type_id: 6, zone_id: 109, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1489, work_type_id: 6, zone_id: 109, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1488, work_type_id: 6, zone_id: 109, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1491, work_type_id: 6, zone_id: 109, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1433, work_type_id: 6, zone_id: 126, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1438, work_type_id: 6, zone_id: 126, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1436, work_type_id: 6, zone_id: 126, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1435, work_type_id: 6, zone_id: 126, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1434, work_type_id: 6, zone_id: 126, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1437, work_type_id: 6, zone_id: 126, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1505, work_type_id: 6, zone_id: 100, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1510, work_type_id: 6, zone_id: 100, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1508, work_type_id: 6, zone_id: 100, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1507, work_type_id: 6, zone_id: 100, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1506, work_type_id: 6, zone_id: 100, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1509, work_type_id: 6, zone_id: 100, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1499, work_type_id: 6, zone_id: 101, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1504, work_type_id: 6, zone_id: 101, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1502, work_type_id: 6, zone_id: 101, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1501, work_type_id: 6, zone_id: 101, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1500, work_type_id: 6, zone_id: 101, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1503, work_type_id: 6, zone_id: 101, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1451, work_type_id: 6, zone_id: 111, text: "Возьми список пересчёта и иди по нему по порядку", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1456, work_type_id: 6, zone_id: 111, text: "Если есть пересорт, сообщи ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1454, work_type_id: 6, zone_id: 111, text: "Если нашёл расхождение, перепроверь ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1453, work_type_id: 6, zone_id: 111, text: "Не пропускай верхние полки и задние ряды", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1452, work_type_id: 6, zone_id: 111, text: "Считай товар на полке и в подсобке, если относится к зоне", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1455, work_type_id: 6, zone_id: 111, text: "Фиксируй результат сразу, чтобы не забыть", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1412, work_type_id: 2, zone_id: 117, text: "Держи рабочее место чистым и без лишних вещей", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1413, work_type_id: 2, zone_id: 117, text: "Если есть ошибка, сразу сообщи старшему кассиру", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1414, work_type_id: 2, zone_id: 117, text: "Не начинай работу, если техника неисправна", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1409, work_type_id: 2, zone_id: 117, text: "Открой смену в кассе и проверь, что касса готова", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1411, work_type_id: 2, zone_id: 117, text: "Проверь, есть ли пакеты и чековая лента", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1410, work_type_id: 2, zone_id: 117, text: "Проверь сканер, принтер, терминал и связь", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1432, work_type_id: 3, zone_id: 114, text: "Держи зону КСО чистой, без мусора", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1431, work_type_id: 3, zone_id: 114, text: "Если есть подозрение на ошибку, останови операцию и позови старшего", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1429, work_type_id: 3, zone_id: 114, text: "Подтверждай возраст и ограничения только после проверки документов", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1428, work_type_id: 3, zone_id: 114, text: "Помогай покупателю, если он не знает что нажать", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1430, work_type_id: 3, zone_id: 114, text: "Весовые и дорогие товары проверяй выборочно", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1427, work_type_id: 3, zone_id: 114, text: "Следи за экранами КСО и подходи к красным уведомлениям", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1330, work_type_id: 1, zone_id: 105, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1326, work_type_id: 1, zone_id: 105, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1328, work_type_id: 1, zone_id: 105, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1325, work_type_id: 1, zone_id: 105, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1329, work_type_id: 1, zone_id: 105, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1327, work_type_id: 1, zone_id: 105, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1318, work_type_id: 1, zone_id: 106, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1314, work_type_id: 1, zone_id: 106, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1316, work_type_id: 1, zone_id: 106, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1313, work_type_id: 1, zone_id: 106, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1317, work_type_id: 1, zone_id: 106, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1315, work_type_id: 1, zone_id: 106, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1348, work_type_id: 1, zone_id: 102, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1344, work_type_id: 1, zone_id: 102, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1346, work_type_id: 1, zone_id: 102, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1343, work_type_id: 1, zone_id: 102, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1347, work_type_id: 1, zone_id: 102, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1345, work_type_id: 1, zone_id: 102, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1336, work_type_id: 1, zone_id: 104, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1332, work_type_id: 1, zone_id: 104, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1334, work_type_id: 1, zone_id: 104, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1331, work_type_id: 1, zone_id: 104, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1335, work_type_id: 1, zone_id: 104, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1333, work_type_id: 1, zone_id: 104, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1306, work_type_id: 1, zone_id: 113, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1302, work_type_id: 1, zone_id: 113, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1304, work_type_id: 1, zone_id: 113, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1301, work_type_id: 1, zone_id: 113, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1305, work_type_id: 1, zone_id: 113, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1303, work_type_id: 1, zone_id: 113, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1342, work_type_id: 1, zone_id: 103, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1338, work_type_id: 1, zone_id: 103, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1340, work_type_id: 1, zone_id: 103, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1337, work_type_id: 1, zone_id: 103, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1341, work_type_id: 1, zone_id: 103, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1339, work_type_id: 1, zone_id: 103, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1312, work_type_id: 1, zone_id: 107, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1308, work_type_id: 1, zone_id: 107, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1310, work_type_id: 1, zone_id: 107, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1307, work_type_id: 1, zone_id: 107, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1311, work_type_id: 1, zone_id: 107, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1309, work_type_id: 1, zone_id: 107, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1421, work_type_id: 1, zone_id: 117, text: "Выемку делай только по регламенту и с разрешения старшего", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1426, work_type_id: 1, zone_id: 117, text: "Если есть ошибка, сразу остановись и позови старшего", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1425, work_type_id: 1, zone_id: 117, text: "Не обсуждай сумму и не показывай деньги покупателям", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1422, work_type_id: 1, zone_id: 117, text: "Не оставляй кассу без присмотра во время операции", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1424, work_type_id: 1, zone_id: 117, text: "Передай наличность сразу в сейф или ответственному", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1423, work_type_id: 1, zone_id: 117, text: "Пересчитай деньги и оформи документы", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1354, work_type_id: 1, zone_id: 108, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1350, work_type_id: 1, zone_id: 108, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1352, work_type_id: 1, zone_id: 108, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1349, work_type_id: 1, zone_id: 108, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1353, work_type_id: 1, zone_id: 108, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1351, work_type_id: 1, zone_id: 108, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1366, work_type_id: 1, zone_id: 110, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1362, work_type_id: 1, zone_id: 110, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1364, work_type_id: 1, zone_id: 110, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1361, work_type_id: 1, zone_id: 110, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1365, work_type_id: 1, zone_id: 110, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1363, work_type_id: 1, zone_id: 110, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1360, work_type_id: 1, zone_id: 109, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1356, work_type_id: 1, zone_id: 109, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1358, work_type_id: 1, zone_id: 109, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1355, work_type_id: 1, zone_id: 109, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1359, work_type_id: 1, zone_id: 109, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1357, work_type_id: 1, zone_id: 109, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1300, work_type_id: 1, zone_id: 127, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1296, work_type_id: 1, zone_id: 127, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1298, work_type_id: 1, zone_id: 127, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1295, work_type_id: 1, zone_id: 127, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1299, work_type_id: 1, zone_id: 127, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1297, work_type_id: 1, zone_id: 127, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1378, work_type_id: 1, zone_id: 100, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1374, work_type_id: 1, zone_id: 100, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1376, work_type_id: 1, zone_id: 100, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1373, work_type_id: 1, zone_id: 100, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1377, work_type_id: 1, zone_id: 100, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1375, work_type_id: 1, zone_id: 100, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1372, work_type_id: 1, zone_id: 101, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1368, work_type_id: 1, zone_id: 101, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1370, work_type_id: 1, zone_id: 101, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1367, work_type_id: 1, zone_id: 101, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1371, work_type_id: 1, zone_id: 101, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1369, work_type_id: 1, zone_id: 101, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1324, work_type_id: 1, zone_id: 111, text: "После исправлений подровняй товар на полке и пройди зону ещё раз", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1320, work_type_id: 1, zone_id: 111, text: "Проверь, что лотки заполнены и нет пустот", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1322, work_type_id: 1, zone_id: 111, text: "Проверь соответствие ценников и маркировки партии рядом с товаром", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1319, work_type_id: 1, zone_id: 111, text: "Сверь выкладку с планограммой и поправь перестановки", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1323, work_type_id: 1, zone_id: 111, text: "Брак и рисковые позиции сразу сними", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1321, work_type_id: 1, zone_id: 111, text: "Убери грязную тару и проверь чистоту оборудования", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1099, work_type_id: 5, zone_id: 105, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1098, work_type_id: 5, zone_id: 105, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1100, work_type_id: 5, zone_id: 105, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1102, work_type_id: 5, zone_id: 105, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1101, work_type_id: 5, zone_id: 105, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1097, work_type_id: 5, zone_id: 105, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1087, work_type_id: 5, zone_id: 106, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1086, work_type_id: 5, zone_id: 106, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1088, work_type_id: 5, zone_id: 106, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1090, work_type_id: 5, zone_id: 106, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1089, work_type_id: 5, zone_id: 106, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1085, work_type_id: 5, zone_id: 106, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1117, work_type_id: 5, zone_id: 102, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1116, work_type_id: 5, zone_id: 102, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1118, work_type_id: 5, zone_id: 102, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1120, work_type_id: 5, zone_id: 102, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1119, work_type_id: 5, zone_id: 102, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1115, work_type_id: 5, zone_id: 102, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1105, work_type_id: 5, zone_id: 104, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1104, work_type_id: 5, zone_id: 104, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1106, work_type_id: 5, zone_id: 104, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1108, work_type_id: 5, zone_id: 104, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1107, work_type_id: 5, zone_id: 104, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1103, work_type_id: 5, zone_id: 104, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1111, work_type_id: 5, zone_id: 103, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1110, work_type_id: 5, zone_id: 103, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1112, work_type_id: 5, zone_id: 103, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1114, work_type_id: 5, zone_id: 103, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1113, work_type_id: 5, zone_id: 103, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1109, work_type_id: 5, zone_id: 103, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1081, work_type_id: 5, zone_id: 107, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1080, work_type_id: 5, zone_id: 107, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1082, work_type_id: 5, zone_id: 107, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1084, work_type_id: 5, zone_id: 107, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1083, work_type_id: 5, zone_id: 107, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1079, work_type_id: 5, zone_id: 107, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1123, work_type_id: 5, zone_id: 108, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1122, work_type_id: 5, zone_id: 108, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1124, work_type_id: 5, zone_id: 108, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1126, work_type_id: 5, zone_id: 108, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1125, work_type_id: 5, zone_id: 108, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1121, work_type_id: 5, zone_id: 108, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1135, work_type_id: 5, zone_id: 110, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1134, work_type_id: 5, zone_id: 110, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1136, work_type_id: 5, zone_id: 110, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1138, work_type_id: 5, zone_id: 110, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1137, work_type_id: 5, zone_id: 110, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1133, work_type_id: 5, zone_id: 110, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1129, work_type_id: 5, zone_id: 109, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1128, work_type_id: 5, zone_id: 109, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1130, work_type_id: 5, zone_id: 109, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1132, work_type_id: 5, zone_id: 109, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1131, work_type_id: 5, zone_id: 109, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1127, work_type_id: 5, zone_id: 109, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1075, work_type_id: 5, zone_id: 122, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1074, work_type_id: 5, zone_id: 122, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1076, work_type_id: 5, zone_id: 122, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1078, work_type_id: 5, zone_id: 122, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1077, work_type_id: 5, zone_id: 122, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1073, work_type_id: 5, zone_id: 122, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1147, work_type_id: 5, zone_id: 100, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1146, work_type_id: 5, zone_id: 100, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1148, work_type_id: 5, zone_id: 100, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1150, work_type_id: 5, zone_id: 100, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1149, work_type_id: 5, zone_id: 100, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1145, work_type_id: 5, zone_id: 100, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1141, work_type_id: 5, zone_id: 101, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1140, work_type_id: 5, zone_id: 101, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1142, work_type_id: 5, zone_id: 101, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1144, work_type_id: 5, zone_id: 101, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1143, work_type_id: 5, zone_id: 101, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1139, work_type_id: 5, zone_id: 101, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1093, work_type_id: 5, zone_id: 111, text: "В AX2012 добавь товар в «Задания для печати ценников» и выбери формат", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1092, work_type_id: 5, zone_id: 111, text: "В ТСД «Контроль ценников» отсканируй товар, чтобы найти код", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1094, work_type_id: 5, zone_id: 111, text: "Распечатай через Excel и проверь, что на ценнике есть название и штрихкод", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1096, work_type_id: 5, zone_id: 111, text: "После замены проверь сканером, что товар и ценник совпадают", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1095, work_type_id: 5, zone_id: 111, text: "Ставь ценник строго под товаром, обзор товара не закрывай", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1091, work_type_id: 5, zone_id: 111, text: "Проверь, какой ценник нужен: белый обычный или жёлтый промо", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1514, work_type_id: 8, zone_id: 115, text: "Вернись вовремя и отметь окончание перерыва", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1515, work_type_id: 8, zone_id: 115, text: "Если график меняется, сообщи старшему заранее", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1513, work_type_id: 8, zone_id: 115, text: "Зафиксируй перерыв в WFM как требуется", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1512, work_type_id: 8, zone_id: 115, text: "Перед уходом передай задачи и ключевую информацию коллеге", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1516, work_type_id: 8, zone_id: 115, text: "После перерыва быстро включись в работу и проверь свою зону", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
  { id: 1511, work_type_id: 8, zone_id: 115, text: "Согласуй время перерыва со старшим, чтобы зона не осталась пустой", created_at: LAMA_HINT_DATE, updated_at: LAMA_HINT_DATE },
];