import type { AISuggestion } from "@/lib/types";

/**
 * @endpoint GET /api/ai/suggestions
 * 20 AISuggestion — mix of types, statuses, priorities.
 * Includes FMCG (PENDING), fashion demo, BONUS_TASK_SUGGESTION, GOAL_SUGGESTION, INSIGHT.
 * 5 ACCEPTED + 8 REJECTED (with decision_reason) — for stats.
 */

const now = new Date("2026-05-01T10:00:00+07:00");
const hoursAgo = (h: number) =>
  new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_AI_SUGGESTIONS: AISuggestion[] = [
  // ── PENDING TASK_SUGGESTION — FMCG (5) ─────────────────────────

  {
    id: "ai-sug-001",
    type: "TASK_SUGGESTION",
    title: "Контроль скоропорта молочки",
    description: "Необходим внеплановый обход холодильников 1–4 с изъятием молочных продуктов со сроком ≤1 день.",
    rationale: "Списания молочки за неделю составили 4.8% при норме 2% (заданной в Стандартах для ИИ). Превышение в 2.4 раза. Контроль скоропорта вечером снизит риск дальнейших списаний.",
    proposed_payload: {
      title: "Контроль скоропорта молочки",
      type: "PLANNED",
      work_type_id: 11,
      work_type_name: "Контроль качества",
      store_id: 1,
      zone_id: 6,
      planned_minutes: 35,
      requires_photo: true,
      acceptance_policy: "MANUAL",
      time_start: "20:00:00",
      time_end: "20:35:00",
    },
    context_data: {
      anomaly_metric: "dairy_writeoff_pct",
      chart_data: {
        type: "bar",
        label: "Списания молочки, % (7 дней)",
        values: [2.1, 2.3, 2.8, 3.4, 4.1, 4.5, 4.8],
        norm: 2.0,
      },
    },
    status: "PENDING",
    priority: "high",
    target_object_type: "STORE",
    target_object_ids: [1],
    created_at: hoursAgo(3),
  },

  {
    id: "ai-sug-002",
    type: "TASK_SUGGESTION",
    title: "Уценка хлеба к закрытию",
    description: "По данным POS на конец дня — остаток хлебобулочки существенно выше нормы. Рекомендуется уценка.",
    rationale: "За последний час смены остаётся 47% дневной выпечки vs ожидаемых 15% (стандарт). Уценка к закрытию минимизирует списания и увеличивает выручку от реализации.",
    proposed_payload: {
      title: "Уценка хлеба и выпечки к закрытию",
      type: "PLANNED",
      work_type_id: 5,
      work_type_name: "Переоценка",
      store_id: 1,
      zone_id: 1,
      planned_minutes: 20,
      requires_photo: false,
      acceptance_policy: "MANUAL",
      time_start: "21:00:00",
      time_end: "21:20:00",
      discount_percent: 30,
    },
    context_data: {
      anomaly_metric: "bread_end_of_day_remainder_pct",
      chart_data: {
        type: "line",
        label: "Остаток хлеба на конец дня, % от дневного завоза",
        values: [18, 21, 32, 28, 41, 44, 47],
        norm: 15,
      },
    },
    status: "PENDING",
    priority: "medium",
    target_object_type: "STORE",
    target_object_ids: [1],
    created_at: hoursAgo(5),
  },

  {
    id: "ai-sug-003",
    type: "TASK_SUGGESTION",
    title: "Доукладка алкоголя из подсобки",
    description: "OOS алкоголя на полке превысил норму. На складе достаточный остаток — требуется доукладка.",
    rationale: "OOS алкоголя 6.2% при норме 4% (стандарт). На складе остаток 30+ позиций — нужна доукладка для восстановления полного ассортимента.",
    proposed_payload: {
      title: "Доукладка алкоголя из подсобки",
      type: "PLANNED",
      work_type_id: 4,
      work_type_name: "Выкладка",
      store_id: 4,
      zone_id: 1,
      product_category_id: 4,
      product_category_name: "Алкоголь крепкий",
      planned_minutes: 40,
      requires_photo: true,
      acceptance_policy: "MANUAL",
    },
    context_data: {
      anomaly_metric: "alcohol_oos_pct",
      related_skus: ["Водка Русская 0.5", "Коньяк 5* 0.5", "Виски Bells 0.7"],
    },
    status: "PENDING",
    priority: "medium",
    target_object_type: "STORE",
    target_object_ids: [4],
    created_at: hoursAgo(7),
  },

  {
    id: "ai-sug-004",
    type: "TASK_SUGGESTION",
    title: "Замена ценников после переоценки",
    description: "Выгрузка цен от 27 апр включала 23 SKU, ценники в зале не обновлены. Риск жалоб на кассе.",
    rationale: "По выгрузке от 27 апр изменены цены на 23 SKU. Ценники в зале не обновлены — риск жалоб на кассе и нарушение законодательства о ценообразовании (стандарт: обновить в течение 4 ч после выгрузки).",
    proposed_payload: {
      title: "Замена ценников после переоценки 27 апр",
      type: "PLANNED",
      work_type_id: 5,
      work_type_name: "Переоценка",
      store_id: 4,
      zone_id: 1,
      planned_minutes: 35,
      requires_photo: false,
      acceptance_policy: "MANUAL",
    },
    context_data: {
      anomaly_metric: "reprice_sku_count_pending",
      chart_data: null,
      related_skus: ["Йогурт Чудо 125г", "Кефир Bio 1%", "Творог зерненый 5%", "...+20 SKU"],
    },
    status: "PENDING",
    priority: "low",
    target_object_type: "STORE",
    target_object_ids: [4],
    created_at: hoursAgo(12),
  },

  {
    id: "ai-sug-005",
    type: "TASK_SUGGESTION",
    title: "Проверка холодильников 5–8",
    description: "За последние 24 часа не было задачи на проверку температурного режима холодильников 5–8.",
    rationale: "Не было задачи проверки температуры за последние 24ч (стандарт = ежедневно). Нарушение регламента + риск порчи скоропорта. Создать задачу немедленно.",
    proposed_payload: {
      title: "Проверка температурного режима холодильников 5–8",
      type: "PLANNED",
      work_type_id: 11,
      work_type_name: "Контроль качества",
      store_id: 1,
      zone_id: 6,
      planned_minutes: 20,
      requires_photo: false,
      acceptance_policy: "MANUAL",
    },
    context_data: {
      anomaly_metric: "hours_since_last_temp_check",
      chart_data: {
        type: "single_value",
        label: "Часов без проверки температуры",
        value: 27,
        norm: 24,
      },
    },
    status: "PENDING",
    priority: "high",
    target_object_type: "STORE",
    target_object_ids: [1],
    created_at: hoursAgo(1),
  },

  // ── FASHION DEMO TASK_SUGGESTION (1) ────────────────────────────

  {
    id: "ai-sug-006",
    type: "TASK_SUGGESTION",
    title: "Уценить непродающийся товар «Сарафан летний синий»",
    description: "Товар на полке с ноября 2025, продажи — 0 шт. Предлагается уценка + стикер + фото для маркетинг-канала.",
    rationale: "Карточка «Сарафан летний синий» заведена 5 месяцев назад. По данным POS — продажи 0 за весь период. Предлагаю скидку 10% (можно скорректировать: 5%, 15%, 20% — на усмотрение супервайзера) + наклеить стикер «Специальная цена» + сделать фото для отправки в маркетинг-канал.",
    proposed_payload: {
      title: "Уценить сарафан летний синий + стикер + фото",
      type: "PLANNED",
      work_type_id: 5,
      work_type_name: "Переоценка",
      store_id: 10,
      zone_id: 1,
      planned_minutes: 15,
      requires_photo: true,
      acceptance_policy: "MANUAL",
      discount_percent: 10, // editable before accept: 5/10/15/20
      marketing_channel_target: "Канал распродаж",
    },
    context_data: {
      anomaly_metric: "sku_zero_sales_days",
      chart_data: {
        type: "single_value",
        label: "Дней без продаж",
        value: 153,
      },
      related_skus: ["Сарафан летний синий, арт. SS-2025-BL-04"],
    },
    status: "PENDING",
    priority: "high",
    target_object_type: "STORE",
    target_object_ids: [10],
    created_at: hoursAgo(6),
  },

  // ── BONUS_TASK_SUGGESTION (3 — linked to goal-oos-active) ───────

  {
    id: "ai-sug-007",
    type: "BONUS_TASK_SUGGESTION",
    title: "Бонус: Доукладка молочки из подсобки",
    description: "Бонусная задача в рамках цели «Снизить OOS в молочке». 200 баллов за выполнение.",
    rationale: "Активная цель OOS-снижения. Доукладка 3 позиций из складского остатка устранит текущий OOS без ожидания новой поставки.",
    proposed_payload: {
      title: "Доукладка молочки из подсобки",
      type: "BONUS",
      bonus_points: 200,
      goal_id: "goal-oos-active",
      work_type_id: 4,
      store_id: 1,
      planned_minutes: 20,
    },
    status: "PENDING",
    priority: "high",
    target_object_type: "STORE",
    target_object_ids: [1],
    created_at: hoursAgo(2),
  },
  {
    id: "ai-sug-008",
    type: "BONUS_TASK_SUGGESTION",
    title: "Бонус: Контроль ценников молочки",
    description: "Бонусная задача — проверить актуальность ценников в молочном отделе. 150 баллов.",
    rationale: "Неверный ценник снижает конверсию и может маскировать OOS. Быстрая проверка займёт 10 минут и поддержит цель снижения OOS.",
    proposed_payload: {
      title: "Контроль ценников молочного отдела",
      type: "BONUS",
      bonus_points: 150,
      goal_id: "goal-oos-active",
      work_type_id: 10,
      store_id: 1,
      planned_minutes: 10,
    },
    status: "PENDING",
    priority: "medium",
    target_object_type: "STORE",
    target_object_ids: [1],
    created_at: hoursAgo(4),
  },
  {
    id: "ai-sug-009",
    type: "BONUS_TASK_SUGGESTION",
    title: "Бонус: Фотоотчёт полки молочки",
    description: "Бонусная задача — зафиксировать текущее состояние полки молочки. 100 баллов.",
    rationale: "Нужна актуальная фотография для системы контроля выкладки. Используется для обновления витрины ИИ и анализа OOS-тренда.",
    proposed_payload: {
      title: "Фотоотчёт полки молочки",
      type: "BONUS",
      bonus_points: 100,
      goal_id: "goal-oos-active",
      work_type_id: 4,
      store_id: 1,
      planned_minutes: 5,
    },
    status: "PENDING",
    priority: "low",
    target_object_type: "STORE",
    target_object_ids: [1],
    created_at: hoursAgo(8),
  },

  // ── GOAL_SUGGESTION (2) ─────────────────────────────────────────

  {
    id: "ai-sug-010",
    type: "GOAL_SUGGESTION",
    title: "Снизить OOS по топ-SKU молочки",
    description: "ИИ предлагает активировать макроцель снижения OOS в молочной категории на уровне сети.",
    rationale: "За апрель средний OOS молочки по сети составил 6.2% — на 55% выше нормы 4% (стандарт). Тренд ухудшения 3 недели подряд. Цель поможет фокусировать бонусные и дополнительные задачи.",
    proposed_payload: {
      category: "OOS_REDUCTION",
      target_value: 4.0,
      target_unit: "%",
      period_days: 14,
      scope: "NETWORK",
    },
    context_data: {
      anomaly_metric: "network_dairy_oos_pct",
      chart_data: {
        type: "trend",
        label: "OOS молочки по сети, %",
        values: [3.8, 4.1, 4.5, 5.0, 5.4, 5.8, 6.2],
        norm: 4.0,
      },
    },
    status: "PENDING",
    priority: "high",
    target_object_type: "NETWORK",
    target_object_ids: [],
    created_at: daysAgo(1),
  },
  {
    id: "ai-sug-011",
    type: "GOAL_SUGGESTION",
    title: "Снизить списания Fresh-категории",
    description: "Списания Fresh выше нормы в 3 из 8 магазинов. ИИ предлагает цель на уровне сети.",
    rationale: "Fresh-списания: FC-TOM-001 — 3.9%, SPAR-TOM-001 — 3.2%, SPAR-NSK-001 — 4.1%. Норма — 2.5% (стандарт). Системная проблема, требует сетевой цели.",
    proposed_payload: {
      category: "WRITE_OFFS",
      target_value: 2.5,
      target_unit: "%",
      period_days: 14,
      scope: "NETWORK",
    },
    status: "PENDING",
    priority: "medium",
    target_object_type: "NETWORK",
    target_object_ids: [],
    created_at: daysAgo(2),
  },

  // ── INSIGHT (4, without proposed_payload) ──────────────────────

  {
    id: "ai-sug-012",
    type: "INSIGHT",
    title: "Accept rate Романова И. А. упал на 60% за 3 дня",
    description: "У супервайзера Романов И. А. accept rate снизился с 78% до 31% за последние 3 дня.",
    rationale: "Резкое падение может указывать на проблему с типом предложений для его зоны ответственности (магазины Новосибирск) или на временные операционные изменения. Рекомендуется проверить последние отклонённые suggestions.",
    proposed_payload: {},
    context_data: {
      anomaly_metric: "supervisor_accept_rate_change",
      chart_data: {
        type: "line",
        label: "Accept rate Романов, %",
        values: [78, 76, 74, 65, 48, 38, 31],
      },
    },
    status: "PENDING",
    priority: "high",
    target_object_type: "STORE_LIST",
    target_object_ids: [4, 5],
    created_at: hoursAgo(6),
  },
  {
    id: "ai-sug-013",
    type: "INSIGHT",
    title: "Магазины Food City ниже нормы по выкладке промо в среду",
    description: "Анализ последних 4 недель показывает системное падение completion rate промо-выкладки в Food City по средам.",
    rationale: "FC-TOM-001 и FC-TOM-002: completion rate задач типа «Мерчендайзинг (планограммы)» по средам — 67% vs норма 85%+. Возможная причина: смена расписания или смена персонала. Рекомендуется ручная проверка.",
    proposed_payload: {},
    context_data: {
      anomaly_metric: "promo_merch_wednesday_completion",
    },
    status: "PENDING",
    priority: "medium",
    target_object_type: "STORE_LIST",
    target_object_ids: [7, 8],
    created_at: daysAgo(3),
  },
  {
    id: "ai-sug-014",
    type: "INSIGHT",
    title: "Возвраты задач у новых сотрудников +22% за месяц",
    description: "Сотрудники со стажем ≤3 месяца возвращают задачи на доработку в 1.3 раза чаще, чем в прошлом месяце.",
    rationale: "Возможные причины: изменились требования к фотоотчётам или новые сотрудники не ознакомлены с обновлёнными стандартами. Рекомендуется проверить регламенты в разделе «Документы».",
    proposed_payload: {},
    context_data: {
      anomaly_metric: "new_employee_return_rate_pct",
    },
    status: "PENDING",
    priority: "medium",
    target_object_type: "NETWORK",
    target_object_ids: [],
    created_at: daysAgo(4),
  },
  {
    id: "ai-sug-015",
    type: "INSIGHT",
    title: "Хлебобулочка — стабильный рост продаж +5% уже 4 недели",
    description: "Позитивный сигнал: продажи хлебобулочной категории устойчиво растут по всей сети.",
    rationale: "Категория «Хлебобулочка» показывает рост продаж +5% 4 недели подряд по сети. Связано с запуском собственной выпечки в FC-TOM-001 в марте. Рекомендуется увеличить плановый завоз на следующую неделю.",
    proposed_payload: {},
    context_data: {
      anomaly_metric: "bread_sales_growth_pct",
      chart_data: {
        type: "bar",
        label: "Рост продаж хлебобулочки по неделям, %",
        values: [+4.8, +5.1, +5.3, +5.2],
      },
    },
    status: "PENDING",
    priority: "low",
    target_object_type: "NETWORK",
    target_object_ids: [],
    created_at: daysAgo(1),
  },

  // ── ACCEPTED (5 — for stats) ────────────────────────────────────

  {
    id: "ai-sug-016",
    type: "TASK_SUGGESTION",
    title: "Доукладка фруктов и овощей",
    description: "OOS в категории фрукты/овощи превысил норму в SPAR-TOM-001.",
    rationale: "OOS 5.1% при норме 3.5% (стандарт). Есть остатки на складе.",
    proposed_payload: { work_type_id: 4, store_id: 1, planned_minutes: 25 },
    status: "ACCEPTED",
    priority: "medium",
    target_object_type: "STORE",
    target_object_ids: [1],
    created_at: daysAgo(5),
    decided_at: daysAgo(5),
    decided_by: 4,
    linked_object_type: "task",
    linked_object_id: "task-from-ai-016",
    linked_object_title: "Доукладка фруктов и овощей",
  },
  {
    id: "ai-sug-017",
    type: "TASK_SUGGESTION",
    title: "Внеплановая инвентаризация кондитерки",
    description: "Расхождение остатков кондитерки по данным системы и физическому пересчёту.",
    rationale: "Расхождение 3.1% при норме 1% (стандарт). Рекомендуется внеплановая инвентаризация.",
    proposed_payload: { work_type_id: 6, store_id: 4, planned_minutes: 60 },
    context_data: { anomaly_metric: "inventory_discrepancy_pct" },
    status: "ACCEPTED",
    priority: "high",
    target_object_type: "STORE",
    target_object_ids: [4],
    created_at: daysAgo(4),
    decided_at: daysAgo(4),
    decided_by: 4,
    decision_comment: "Принято с правками: время выполнения увеличено до 90 мин",
    linked_object_type: "task",
    linked_object_id: "task-from-ai-017",
    linked_object_title: "Внеплановая инвентаризация кондитерки",
  },
  {
    id: "ai-sug-018",
    type: "GOAL_SUGGESTION",
    title: "Снизить OOS по заморозке",
    description: "OOS заморозки 8.1% — выше нормы в 2 раза.",
    rationale: "OOS 8.1% при норме 4% (стандарт). Тренд ухудшения 2 недели.",
    proposed_payload: { category: "OOS_REDUCTION", target_value: 4.0 },
    status: "ACCEPTED",
    priority: "high",
    target_object_type: "NETWORK",
    target_object_ids: [],
    created_at: daysAgo(32),
    decided_at: daysAgo(32),
    decided_by: 3,
    linked_object_type: "goal",
    linked_object_id: "goal-from-ai-018",
    linked_object_title: "Снизить OOS по заморозке",
  },
  {
    id: "ai-sug-019",
    type: "TASK_SUGGESTION",
    title: "Проверка EGAIS документов перед вечерней продажей",
    description: "Алкогольная поставка принята, EGAIS не подтверждена — риск штрафа.",
    rationale: "Поставка алкоголя принята в 14:40. EGAIS не подтверждена. Ограничение продаж с 22:00 (стандарт: подтвердить в течение 4ч).",
    proposed_payload: { work_type_id: 13, store_id: 2, planned_minutes: 15 },
    status: "ACCEPTED",
    priority: "high",
    target_object_type: "STORE",
    target_object_ids: [2],
    created_at: daysAgo(6),
    decided_at: daysAgo(6),
    decided_by: 6,
    linked_object_type: "task",
    linked_object_id: "task-from-ai-019",
    linked_object_title: "Проверка EGAIS документов перед вечерней продажей",
  },
  {
    id: "ai-sug-020",
    type: "BONUS_TASK_SUGGESTION",
    title: "Бонус: Выкладка заморозки из остатков",
    description: "Бонусная задача в рамках цели OOS заморозки.",
    rationale: "Есть остатки заморозки на складе, полка OOS. 200 баллов.",
    proposed_payload: { type: "BONUS", bonus_points: 200, goal_id: "goal-oos-completed", work_type_id: 4, store_id: 4, title: "Выкладка заморозки из остатков" },
    status: "ACCEPTED",
    priority: "medium",
    target_object_type: "STORE",
    target_object_ids: [4],
    created_at: daysAgo(15),
    decided_at: daysAgo(15),
    decided_by: 4,
    linked_object_type: "bonus_task",
    linked_object_id: "bonus-task-from-ai-020",
    linked_object_title: "Выкладка заморозки из остатков",
  },

  // ── REJECTED (8 — with decision_reason) ────────────────────────

  ...[
    { id: "ai-sug-r01", title: "Уборка склада перед приёмкой", reason: "Не релевантно сейчас", comment: "Приёмка отложена до завтра" },
    { id: "ai-sug-r02", title: "Контроль промо-стеллажей", reason: "Уже в работе", comment: "Задача уже создана вручную" },
    { id: "ai-sug-r03", title: "Переоценка кисломолочки", reason: "Не релевантно сейчас", comment: "Акция ещё не запущена" },
    { id: "ai-sug-r04", title: "Дополнительная инвентаризация замороженных", reason: "Уже в работе", comment: "" },
    { id: "ai-sug-r05", title: "Доукладка снековой зоны", reason: "Не согласен с анализом", comment: "Полка заполнена — данные POS некорректны" },
    { id: "ai-sug-r06", title: "Усилить выкладку промо зоны 3", reason: "Не согласен с анализом", comment: "Зона переделана по новой схеме, анализ устарел" },
    { id: "ai-sug-r07", title: "Обход торгового зала перед обедом", reason: "Слишком общее", comment: "Нет конкретных параметров — не понятно что проверять" },
    { id: "ai-sug-r08", title: "Не релевантно сейчас — контроль касс", reason: "Не релевантно сейчас", comment: "Технический сбой устранён, задача не нужна" },
  ].map(({ id, title, reason, comment }, idx): AISuggestion => ({
    id,
    type: "TASK_SUGGESTION",
    title,
    description: `Задача предложена ИИ — отклонена.`,
    rationale: "Данные показали аномалию, однако менеджер отклонил.",
    proposed_payload: { work_type_id: 4 + (idx % 5), store_id: 1 + (idx % 4) },
    status: "REJECTED",
    priority: ["high", "medium", "low"][idx % 3] as AISuggestion["priority"],
    target_object_type: "STORE",
    target_object_ids: [1 + (idx % 4)],
    created_at: daysAgo(1 + idx),
    decided_at: daysAgo(1 + idx),
    decided_by: idx % 2 === 0 ? 4 : 12,
    decision_reason: reason,
    decision_comment: comment || undefined,
  })),
];
