import type { AuditEntry } from "@/lib/types";

/**
 * @endpoint GET /api/audit
 * 30 audit entries — realistic mix over last 7 days.
 * Actions: task.*, user.*, permission.*, shift.*, settings.*, api_key.*, login.
 */

const now = new Date("2026-05-01T10:00:00+07:00");
const at = (hoursBack: number, minuteOffset = 0) =>
  new Date(
    now.getTime() - hoursBack * 60 * 60 * 1000 - minuteOffset * 60 * 1000
  ).toISOString();

const UAS = {
  mac_chrome: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  win_edge: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0",
  iphone: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/604.1",
  android: "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.82 Mobile Safari/537.36",
  win_chrome: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

export const MOCK_AUDIT_ENTRIES: AuditEntry[] = [
  // ── task.create ────────────────────────────────────────────────
  {
    id: "audit-001",
    occurred_at: at(2, 15),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR", email: "i.romanov@spar-sibir.ru" },
    action: "task.create",
    action_label: "Создание задачи",
    entity_type: "task",
    entity_id: "task-005",
    entity_name: "Проверка сроков годности молочки",
    entity_url: "/tasks/task-005",
    payload: { store_id: 4, assignee_id: 23, type: "ADDITIONAL", source: "MANAGER" },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },
  {
    id: "audit-002",
    occurred_at: at(4, 5),
    actor: { id: 12, name: "Тарасова Ольга Викторовна", role: "SUPERVISOR" },
    action: "task.create",
    action_label: "Создание задачи",
    entity_type: "task",
    entity_id: "task-011",
    entity_name: "Подготовка зоны выпечки",
    entity_url: "/tasks/task-011",
    payload: { store_id: 7, assignee_id: 25, type: "PLANNED", source: "PLANNED" },
    ip_address: "91.243.56.18",
    user_agent: UAS.iphone,
    device_type: "mobile",
  },

  // ── task.start ─────────────────────────────────────────────────
  {
    id: "audit-003",
    occurred_at: at(2, 0),
    actor: { id: 15, name: "Козлова Дарья Андреевна", role: "WORKER" },
    action: "task.start",
    action_label: "Задача начата",
    entity_type: "task",
    entity_id: "task-006",
    entity_name: "Выкладка молочной полки в холодильнике 3",
    entity_url: "/tasks/task-006",
    payload: { state_from: "NEW", state_to: "IN_PROGRESS" },
    ip_address: "213.87.135.4",
    user_agent: UAS.android,
    device_type: "mobile",
  },
  {
    id: "audit-004",
    occurred_at: at(3, 20),
    actor: { id: 18, name: "Федоров Алексей Николаевич", role: "WORKER" },
    action: "task.start",
    action_label: "Задача начата",
    entity_type: "task",
    entity_id: "task-004",
    entity_name: "Приёмка молочки от ООО «Деревенское молочко»",
    entity_url: "/tasks/task-004",
    payload: { state_from: "NEW", state_to: "IN_PROGRESS" },
    ip_address: "213.87.135.9",
    user_agent: UAS.android,
    device_type: "mobile",
  },

  // ── task.pause ─────────────────────────────────────────────────
  {
    id: "audit-005",
    occurred_at: at(1, 20),
    actor: { id: 17, name: "Медведева Татьяна Ивановна", role: "WORKER" },
    action: "task.pause",
    action_label: "Задача приостановлена",
    entity_type: "task",
    entity_id: "task-013",
    entity_name: "Уборка прикассовой зоны",
    entity_url: "/tasks/task-013",
    payload: { state_from: "IN_PROGRESS", state_to: "PAUSED", comment: "Ждёт поставки чистящего средства" },
    ip_address: "188.243.56.78",
    user_agent: UAS.iphone,
    device_type: "mobile",
  },
  {
    id: "audit-006",
    occurred_at: at(1, 40),
    actor: { id: 21, name: "Кириллова Светлана Васильевна", role: "WORKER" },
    action: "task.pause",
    action_label: "Задача приостановлена",
    entity_type: "task",
    entity_id: "task-015",
    entity_name: "Заказ на расходники РЦ Новосибирск",
    entity_url: "/tasks/task-015",
    payload: { comment: "Ожидает подтверждения бюджета от регионального" },
    ip_address: "94.71.218.33",
    user_agent: UAS.android,
    device_type: "mobile",
  },

  // ── task.complete ──────────────────────────────────────────────
  {
    id: "audit-007",
    occurred_at: at(6, 10),
    actor: { id: 20, name: "Попов Владимир Сергеевич", role: "WORKER" },
    action: "task.complete",
    action_label: "Задача завершена",
    entity_type: "task",
    entity_id: "task-010",
    entity_name: "Открытие зоны самообслуживания",
    entity_url: "/tasks/task-010",
    payload: { state_from: "IN_PROGRESS", state_to: "COMPLETED", acceptance_policy: "AUTO" },
    ip_address: "213.87.135.20",
    user_agent: UAS.android,
    device_type: "mobile",
  },
  {
    id: "audit-008",
    occurred_at: at(25, 0),
    actor: { id: 15, name: "Козлова Дарья Андреевна", role: "WORKER" },
    action: "task.complete",
    action_label: "Задача завершена",
    entity_type: "task",
    entity_id: "task-017",
    entity_name: "Раскладка кондитерского фронта",
    entity_url: "/tasks/task-017",
    payload: { state_from: "IN_PROGRESS", state_to: "COMPLETED", has_report_image: true },
    ip_address: "213.87.135.4",
    user_agent: UAS.android,
    device_type: "mobile",
  },

  // ── task.approve ───────────────────────────────────────────────
  {
    id: "audit-009",
    occurred_at: at(10, 5),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "task.approve",
    action_label: "Задача принята",
    entity_type: "task",
    entity_id: "task-017",
    entity_name: "Раскладка кондитерского фронта",
    entity_url: "/tasks/task-017",
    payload: { review_state_from: "ON_REVIEW", review_state_to: "ACCEPTED" },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },
  {
    id: "audit-010",
    occurred_at: at(48, 0),
    actor: { id: 12, name: "Тарасова Ольга Викторовна", role: "SUPERVISOR" },
    action: "task.approve",
    action_label: "Задача принята",
    entity_type: "task",
    entity_id: "task-019",
    entity_name: "Промо-выкладка в зоне входа",
    entity_url: "/tasks/task-019",
    payload: { review_state_from: "ON_REVIEW", review_state_to: "ACCEPTED" },
    ip_address: "91.243.56.18",
    user_agent: UAS.win_chrome,
    device_type: "desktop",
  },

  // ── task.reject ────────────────────────────────────────────────
  {
    id: "audit-011",
    occurred_at: at(4, 0),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "task.reject",
    action_label: "Задача отклонена",
    entity_type: "task",
    entity_id: "task-016",
    entity_name: "Инвентаризация бакалеи",
    entity_url: "/tasks/task-016",
    payload: {
      review_comment: "Отчёт неполный — не хватает скан-листа участка 5",
      review_state_from: "ON_REVIEW",
      review_state_to: "REJECTED",
    },
    diff: [
      { field: "review_state", before: "ON_REVIEW", after: "REJECTED" },
      { field: "review_comment", before: null, after: "Отчёт неполный — не хватает скан-листа участка 5" },
    ],
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── task.update (diff example) ─────────────────────────────────
  {
    id: "audit-012",
    occurred_at: at(5, 30),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "task.update",
    action_label: "Задача обновлена",
    entity_type: "task",
    entity_id: "task-006",
    entity_name: "Выкладка молочной полки в холодильнике 3",
    entity_url: "/tasks/task-006",
    payload: { updated_fields: ["comment"] },
    diff: [
      { field: "comment", before: null, after: "Особое внимание на йогурты — поставка сегодня утром" },
    ],
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── user.update ────────────────────────────────────────────────
  {
    id: "audit-013",
    occurred_at: at(72, 15),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "user.update",
    action_label: "Профиль сотрудника обновлён",
    entity_type: "user",
    entity_id: "26",
    entity_name: "Гусев Павел Михайлович",
    payload: { updated_fields: ["phone", "position_id"] },
    diff: [
      { field: "phone", before: "+7 (913) 150-55-12", after: "+7 (913) 150-55-99" },
      { field: "position_id", before: 3, after: 5 },
    ],
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },
  {
    id: "audit-014",
    occurred_at: at(96, 5),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "user.update",
    action_label: "Профиль сотрудника обновлён",
    entity_type: "user",
    entity_id: "22",
    entity_name: "Степанов Андрей Борисович",
    payload: { updated_fields: ["preferred_locale"] },
    diff: [
      { field: "preferred_locale", before: "ru", after: "en" },
    ],
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── user.activate / user.deactivate ───────────────────────────
  {
    id: "audit-015",
    occurred_at: at(120, 0),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "user.activate",
    action_label: "Сотрудник активирован",
    entity_type: "user",
    entity_id: "31",
    entity_name: "Мельников Евгений Игоревич",
    payload: { freelancer_status_from: "VERIFICATION", freelancer_status_to: "ACTIVE" },
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },
  {
    id: "audit-016",
    occurred_at: at(144, 30),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "user.deactivate",
    action_label: "Сотрудник деактивирован (архивирован)",
    entity_type: "user",
    entity_id: "28",
    entity_name: "Тихонов Игорь Васильевич",
    payload: { archive_reason: "OBSOLETE", archived: true },
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── permission.grant / permission.revoke ───────────────────────
  {
    id: "audit-017",
    occurred_at: at(50, 0),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "permission.grant",
    action_label: "Допуск выдан",
    entity_type: "permission",
    entity_id: "perm-024",
    entity_name: "SELF_CHECKOUT → Козлова Дарья",
    payload: { permission: "SELF_CHECKOUT", user_id: 15, user_name: "Козлова Дарья Андреевна" },
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },
  {
    id: "audit-018",
    occurred_at: at(80, 20),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "permission.revoke",
    action_label: "Допуск отозван",
    entity_type: "permission",
    entity_id: "perm-011",
    entity_name: "CASHIER → Новиков Максим",
    payload: { permission: "CASHIER", user_id: 16, user_name: "Новиков Максим Юрьевич", reason: "Не прошёл переаттестацию" },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── shift.open / shift.close / shift.force_close ───────────────
  {
    id: "audit-019",
    occurred_at: at(8, 0),
    actor: { id: 15, name: "Козлова Дарья Андреевна", role: "WORKER" },
    action: "shift.open",
    action_label: "Смена открыта",
    entity_type: "shift",
    entity_id: "shift-041",
    entity_name: "Смена Козловой 01.05.2026",
    payload: { store_id: 1, planned_start: "08:00:00", actual_start: "07:58:23", late_minutes: 0 },
    ip_address: "213.87.135.4",
    user_agent: UAS.android,
    device_type: "mobile",
  },
  {
    id: "audit-020",
    occurred_at: at(0, 5),
    actor: { id: 22, name: "Степанов Андрей Борисович", role: "WORKER" },
    action: "shift.close",
    action_label: "Смена закрыта",
    entity_type: "shift",
    entity_id: "shift-044",
    entity_name: "Смена Степанова 01.05.2026",
    payload: { store_id: 4, actual_end: at(0, 5), overtime_minutes: 12 },
    ip_address: "94.71.218.33",
    user_agent: UAS.android,
    device_type: "mobile",
  },
  {
    id: "audit-021",
    occurred_at: at(22, 0),
    actor: { id: 5, name: "Иванов Александр Сергеевич", role: "STORE_DIRECTOR" },
    action: "shift.force_close",
    action_label: "Смена принудительно закрыта",
    entity_type: "shift",
    entity_id: "shift-038",
    entity_name: "Смена Белова 29.04.2026",
    payload: { reason: "Сотрудник покинул магазин без закрытия в приложении", user_id: 27 },
    ip_address: "91.185.44.203",
    user_agent: UAS.win_chrome,
    device_type: "desktop",
  },

  // ── settings.update ────────────────────────────────────────────
  {
    id: "audit-022",
    occurred_at: at(100, 0),
    actor: { id: 3, name: "Соколова Анна Викторовна", role: "NETWORK_OPS", email: "a.sokolova@spar-sibir.ru" },
    action: "settings.update",
    action_label: "Настройки организации обновлены",
    entity_type: "organization",
    entity_id: "org-spar",
    entity_name: "СПАР Сибирь",
    payload: { section: "ai_standards" },
    diff: [
      { field: "dairy_writeoff_norm_pct", before: 2.0, after: 2.5 },
      { field: "oos_norm_pct", before: 4.0, after: 3.5 },
    ],
    ip_address: "195.182.35.7",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
    platform_action: true,
  },
  {
    id: "audit-023",
    occurred_at: at(160, 0),
    actor: { id: 14, name: "Кузнецов Никита Павлович", role: "OPERATOR" },
    action: "settings.update",
    action_label: "Тип работ обновлён",
    entity_type: "work_type",
    entity_id: "4",
    entity_name: "Выкладка",
    payload: { updated_fields: ["default_duration_min"] },
    diff: [
      { field: "default_duration_min", before: 30, after: 35 },
    ],
    ip_address: "78.37.211.100",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── api_key.create ─────────────────────────────────────────────
  {
    id: "audit-024",
    occurred_at: at(130, 0),
    actor: { id: 3, name: "Соколова Анна Викторовна", role: "NETWORK_OPS" },
    action: "api_key.create",
    action_label: "API-ключ создан",
    entity_type: "api_key",
    entity_id: "key-005",
    entity_name: "Интеграция POS SPAR Томск пр. Ленина 80",
    payload: { scope: ["tasks:read", "shifts:read"], expires_at: "2027-05-01" },
    ip_address: "195.182.35.7",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },
  {
    id: "audit-025",
    occurred_at: at(145, 0),
    actor: { id: 3, name: "Соколова Анна Викторовна", role: "NETWORK_OPS" },
    action: "api_key.create",
    action_label: "API-ключ создан",
    entity_type: "api_key",
    entity_id: "key-006",
    entity_name: "Webhook LAMA → WFM",
    payload: { scope: ["webhooks:write"], expires_at: null },
    ip_address: "195.182.35.7",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── login (everyone) ──────────────────────────────────────────
  {
    id: "audit-026",
    occurred_at: at(8, 30),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR", email: "i.romanov@spar-sibir.ru" },
    action: "login",
    action_label: "Вход в систему",
    entity_type: "session",
    entity_id: "sess-romanov-0501",
    entity_name: "Сессия Романов 01.05.2026",
    payload: { method: "phone_otp", channel: "telegram" },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
    login_method: "phone_otp.telegram",
  },
  {
    id: "audit-027",
    occurred_at: at(7, 50),
    actor: { id: 15, name: "Козлова Дарья Андреевна", role: "WORKER" },
    action: "login",
    action_label: "Вход в систему",
    entity_type: "session",
    entity_id: "sess-kozlova-0501",
    entity_name: "Сессия Козлова 01.05.2026",
    payload: { method: "phone_otp", channel: "sms_fallback" },
    ip_address: "213.87.135.4",
    user_agent: UAS.android,
    device_type: "mobile",
    login_method: "phone_otp.sms_fallback",
  },
  {
    id: "audit-028",
    occurred_at: at(9, 0),
    actor: { id: 3, name: "Соколова Анна Викторовна", role: "NETWORK_OPS", email: "a.sokolova@spar-sibir.ru" },
    action: "login",
    action_label: "Вход в систему",
    entity_type: "session",
    entity_id: "sess-sokolova-0501",
    entity_name: "Сессия Соколова 01.05.2026",
    payload: { method: "totp", channel: "authenticator" },
    ip_address: "195.182.35.7",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
    login_method: "totp.authenticator",
  },
  {
    id: "audit-029",
    occurred_at: at(8, 45),
    actor: { id: 14, name: "Кузнецов Никита Павлович", role: "OPERATOR", email: "n.kuznetsov@spar-sibir.ru" },
    action: "login",
    action_label: "Вход в систему",
    entity_type: "session",
    entity_id: "sess-kuznetsov-0501",
    entity_name: "Сессия Кузнецов 01.05.2026",
    payload: { method: "email_magic_link" },
    ip_address: "78.37.211.100",
    user_agent: UAS.win_edge,
    device_type: "desktop",
    login_method: "email_magic_link",
  },
  {
    id: "audit-030",
    occurred_at: at(7, 58),
    actor: { id: 12, name: "Тарасова Ольга Викторовна", role: "SUPERVISOR" },
    action: "login",
    action_label: "Вход в систему",
    entity_type: "session",
    entity_id: "sess-tarasova-0501",
    entity_name: "Сессия Тарасова 01.05.2026",
    payload: { method: "phone_otp", channel: "max" },
    ip_address: "91.243.56.18",
    user_agent: UAS.iphone,
    device_type: "mobile",
    login_method: "phone_otp.max",
  },

  // ── application.create ─────────────────────────────────────────
  {
    id: "audit-031",
    occurred_at: at(3, 0),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR", email: "i.romanov@spar-sibir.ru" },
    action: "application.create",
    action_label: "Заявка создана",
    entity_type: "freelance_application",
    entity_id: "fapp-101",
    entity_name: "Заявка на выкладку товара 03.05.2026",
    entity_url: "/freelance/applications/fapp-101",
    payload: { store_id: 1, work_type_id: 4, requested_hours: 4, requested_count: 2 },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── application.approve_full ───────────────────────────────────
  {
    id: "audit-032",
    occurred_at: at(2, 30),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "application.approve_full",
    action_label: "Заявка полностью принята",
    entity_type: "freelance_application",
    entity_id: "fapp-098",
    entity_name: "Заявка на приёмку молочки 02.05.2026",
    entity_url: "/freelance/applications/fapp-098",
    payload: { approved_count: 2, approved_hours: 6 },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── application.approve_partial ────────────────────────────────
  {
    id: "audit-033",
    occurred_at: at(26, 0),
    actor: { id: 12, name: "Тарасова Ольга Викторовна", role: "SUPERVISOR" },
    action: "application.approve_partial",
    action_label: "Заявка принята частично",
    entity_type: "freelance_application",
    entity_id: "fapp-095",
    entity_name: "Заявка на уборку склада 30.04.2026",
    entity_url: "/freelance/applications/fapp-095",
    payload: { requested_count: 4, approved_count: 2, reason: "Недостаточно бюджета" },
    diff: [
      { field: "approved_count", before: null, after: 2 },
      { field: "requested_count", before: 4, after: 4 },
    ],
    ip_address: "91.243.56.18",
    user_agent: UAS.iphone,
    device_type: "mobile",
  },

  // ── application.reject ─────────────────────────────────────────
  {
    id: "audit-034",
    occurred_at: at(50, 0),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "application.reject",
    action_label: "Заявка отклонена",
    entity_type: "freelance_application",
    entity_id: "fapp-091",
    entity_name: "Заявка на инвентаризацию 28.04.2026",
    entity_url: "/freelance/applications/fapp-091",
    payload: { reason: "Плановая инвентаризация перенесена на следующий месяц" },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── application.replace_with_bonus ────────────────────────────
  {
    id: "audit-035",
    occurred_at: at(48, 30),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "application.replace_with_bonus",
    action_label: "Заменена на бонусную задачу",
    entity_type: "freelance_application",
    entity_id: "fapp-089",
    entity_name: "Заявка на промо-выкладку 27.04.2026",
    payload: { bonus_task_id: "task-bonus-014", reason: "Задача перераспределена штатному" },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── assignment.create ──────────────────────────────────────────
  {
    id: "audit-036",
    occurred_at: at(2, 0),
    actor: { id: 9, name: "Агент Берёзов Андрей Петрович", role: "SUPERVISOR" },
    action: "assignment.create",
    action_label: "Назначение создано",
    entity_type: "freelance_assignment",
    entity_id: "fas-201",
    entity_name: "Козин Дмитрий → Выкладка товара (SPAR пр. Ленина 80)",
    entity_url: "/freelance/assignments/fas-201",
    payload: { freelancer_id: 55, application_id: "fapp-101", store_id: 1 },
    ip_address: "10.0.0.5",
    user_agent: UAS.win_chrome,
    device_type: "desktop",
  },

  // ── assignment.remove ──────────────────────────────────────────
  {
    id: "audit-037",
    occurred_at: at(1, 30),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "assignment.remove",
    action_label: "Назначение удалено",
    entity_type: "freelance_assignment",
    entity_id: "fas-198",
    entity_name: "Зайцев Олег → Уборка склада (SPAR Новосибирск)",
    payload: { reason: "Исполнитель отказался", freelancer_id: 58 },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── service.confirm ────────────────────────────────────────────
  {
    id: "audit-038",
    occurred_at: at(5, 0),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "service.confirm",
    action_label: "Услуга подтверждена",
    entity_type: "freelance_service",
    entity_id: "fsvc-301",
    entity_name: "Выкладка молочной полки — Козин Д. 30.04",
    entity_url: "/freelance/services/fsvc-301",
    payload: { confirmed_hours: 4, amount: 1800, freelancer_id: 55 },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── service.dispute ────────────────────────────────────────────
  {
    id: "audit-039",
    occurred_at: at(28, 0),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "service.dispute",
    action_label: "По услуге открыт спор",
    entity_type: "freelance_service",
    entity_id: "fsvc-289",
    entity_name: "Инвентаризация — Зайцев О. 28.04",
    entity_url: "/freelance/services/fsvc-289",
    payload: { reason: "Фактически отработано меньше заявленного", reported_hours: 6, disputed_hours: 4 },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── service.no_show ────────────────────────────────────────────
  {
    id: "audit-040",
    occurred_at: at(22, 0),
    actor: { id: 12, name: "Тарасова Ольга Викторовна", role: "SUPERVISOR" },
    action: "service.no_show",
    action_label: "Невыход исполнителя",
    entity_type: "freelance_service",
    entity_id: "fsvc-277",
    entity_name: "Приёмка товара — Барсуков К. 29.04",
    payload: { freelancer_id: 61, application_id: "fapp-088", penalty_applied: true },
    ip_address: "91.243.56.18",
    user_agent: UAS.iphone,
    device_type: "mobile",
  },

  // ── service.amount_adjust ─────────────────────────────────────
  {
    id: "audit-041",
    occurred_at: at(6, 0),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "service.amount_adjust",
    action_label: "Сумма услуги скорректирована",
    entity_type: "freelance_service",
    entity_id: "fsvc-298",
    entity_name: "Выкладка напитков — Серов Н. 01.05",
    entity_url: "/freelance/services/fsvc-298",
    payload: { from_amount: 2400, to_amount: 1800, reason: "Работа выполнена частично (3ч из 4)" },
    diff: [
      { field: "amount", before: 2400, after: 1800 },
      { field: "reason", before: null, after: "Работа выполнена частично (3ч из 4)" },
    ],
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── payout.batch_created ──────────────────────────────────────
  {
    id: "audit-042",
    occurred_at: at(12, 0),
    actor: { id: 99, name: "WFM System", role: "NETWORK_OPS" },
    action: "payout.batch_created",
    action_label: "Реестр выплат сформирован",
    entity_type: "freelance_payout",
    entity_id: "pbatch-045",
    entity_name: "Реестр выплат 01.05.2026",
    entity_url: "/freelance/payouts/pbatch-045",
    payload: { entries_count: 12, total_amount: 48600, currency: "RUB" },
    ip_address: "127.0.0.1",
    device_type: "desktop",
  },

  // ── payout.sent_to_nominal ─────────────────────────────────────
  {
    id: "audit-043",
    occurred_at: at(11, 30),
    actor: { id: 99, name: "WFM System", role: "NETWORK_OPS" },
    action: "payout.sent_to_nominal",
    action_label: "Выплата отправлена на номинальный счёт",
    entity_type: "freelance_payout",
    entity_id: "pout-512",
    entity_name: "Выплата Козин Д. 1 800 ₽",
    entity_url: "/freelance/payouts/pout-512",
    payload: { freelancer_id: 55, amount: 1800, bank_ref: "TXN-20260501-0512" },
    ip_address: "127.0.0.1",
    device_type: "desktop",
  },

  // ── payout.failed ─────────────────────────────────────────────
  {
    id: "audit-044",
    occurred_at: at(11, 0),
    actor: { id: 99, name: "WFM System", role: "NETWORK_OPS" },
    action: "payout.failed",
    action_label: "Выплата не прошла",
    entity_type: "freelance_payout",
    entity_id: "pout-508",
    entity_name: "Выплата Барсуков К. 1 200 ₽",
    payload: { freelancer_id: 61, amount: 1200, error_code: "CARD_EXPIRED", retry_scheduled: true },
    ip_address: "127.0.0.1",
    device_type: "desktop",
  },

  // ── payout.retry ──────────────────────────────────────────────
  {
    id: "audit-045",
    occurred_at: at(10, 0),
    actor: { id: 3, name: "Соколова Анна Викторовна", role: "NETWORK_OPS" },
    action: "payout.retry",
    action_label: "Повтор выплаты",
    entity_type: "freelance_payout",
    entity_id: "pout-508",
    entity_name: "Выплата Барсуков К. 1 200 ₽",
    payload: { freelancer_id: 61, amount: 1200, retry_number: 1 },
    ip_address: "195.182.35.7",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── oferta.sent ───────────────────────────────────────────────
  {
    id: "audit-046",
    occurred_at: at(4, 0),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "oferta.sent",
    action_label: "Оферта отправлена исполнителю",
    entity_type: "freelance_oferta",
    entity_id: "oferta-072",
    entity_name: "Оферта → Сидоров Пётр Анатольевич",
    payload: { freelancer_id: 67, channel: "telegram", oferta_version: "2.1" },
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── oferta.accepted ───────────────────────────────────────────
  {
    id: "audit-047",
    occurred_at: at(3, 45),
    actor: { id: 67, name: "Сидоров Пётр Анатольевич", role: "WORKER" },
    action: "oferta.accepted",
    action_label: "Оферта принята",
    entity_type: "freelance_oferta",
    entity_id: "oferta-072",
    entity_name: "Оферта → Сидоров Пётр Анатольевич",
    payload: { freelancer_id: 67, accepted_at: at(3, 45), oferta_version: "2.1" },
    ip_address: "213.87.135.90",
    user_agent: UAS.android,
    device_type: "mobile",
  },

  // ── freelancer.activate ────────────────────────────────────────
  {
    id: "audit-048",
    occurred_at: at(36, 0),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "freelancer.activate",
    action_label: "Исполнитель активирован",
    entity_type: "freelancer",
    entity_id: "fl-067",
    entity_name: "Сидоров Пётр Анатольевич",
    entity_url: "/freelancers/fl-067",
    payload: { status_from: "VERIFICATION", status_to: "ACTIVE" },
    diff: [
      { field: "status", before: "VERIFICATION", after: "ACTIVE" },
    ],
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── freelancer.block ───────────────────────────────────────────
  {
    id: "audit-049",
    occurred_at: at(60, 0),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "freelancer.block",
    action_label: "Исполнитель заблокирован",
    entity_type: "freelancer",
    entity_id: "fl-061",
    entity_name: "Барсуков Константин Вячеславович",
    entity_url: "/freelancers/fl-061",
    payload: { reason: "Систематические невыходы (3 раза за месяц)", status_from: "ACTIVE", status_to: "BLOCKED" },
    diff: [
      { field: "status", before: "ACTIVE", after: "BLOCKED" },
    ],
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── budget_limit.create ───────────────────────────────────────
  {
    id: "audit-050",
    occurred_at: at(72, 0),
    actor: { id: 3, name: "Соколова Анна Викторовна", role: "NETWORK_OPS" },
    action: "budget_limit.create",
    action_label: "Бюджетный лимит создан",
    entity_type: "budget_limit",
    entity_id: "bl-022",
    entity_name: "Лимит SPAR пр. Ленина 80 — Май 2026",
    payload: { store_id: 1, month: "2026-05", amount_rub: 80000 },
    ip_address: "195.182.35.7",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── budget_limit.update ───────────────────────────────────────
  {
    id: "audit-051",
    occurred_at: at(30, 0),
    actor: { id: 3, name: "Соколова Анна Викторовна", role: "NETWORK_OPS" },
    action: "budget_limit.update",
    action_label: "Бюджетный лимит обновлён",
    entity_type: "budget_limit",
    entity_id: "bl-019",
    entity_name: "Лимит SPAR Новосибирск — Апрель 2026",
    payload: { store_id: 7, month: "2026-04", old_amount: 60000, new_amount: 75000 },
    diff: [
      { field: "amount_rub", before: 60000, after: 75000 },
    ],
    ip_address: "195.182.35.7",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── service_norm.create ───────────────────────────────────────
  {
    id: "audit-052",
    occurred_at: at(90, 0),
    actor: { id: 14, name: "Кузнецов Никита Павлович", role: "OPERATOR" },
    action: "service_norm.create",
    action_label: "Норматив создан",
    entity_type: "service_norm",
    entity_id: "sn-014",
    entity_name: "Выкладка молочной продукции — норматив",
    payload: { work_type_id: 4, hours_per_unit: 0.25, units: "паллет" },
    ip_address: "78.37.211.100",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── service_norm.update ───────────────────────────────────────
  {
    id: "audit-053",
    occurred_at: at(45, 0),
    actor: { id: 14, name: "Кузнецов Никита Павлович", role: "OPERATOR" },
    action: "service_norm.update",
    action_label: "Норматив обновлён",
    entity_type: "service_norm",
    entity_id: "sn-011",
    entity_name: "Инвентаризация бакалеи — норматив",
    payload: { work_type_id: 2, old_hours: 0.5, new_hours: 0.4 },
    diff: [
      { field: "hours_per_unit", before: 0.5, after: 0.4 },
    ],
    ip_address: "78.37.211.100",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── agent.create ──────────────────────────────────────────────
  {
    id: "audit-054",
    occurred_at: at(120, 0),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "agent.create",
    action_label: "Агент зарегистрирован",
    entity_type: "agent",
    entity_id: "ag-009",
    entity_name: "ИП Берёзов Андрей Петрович",
    entity_url: "/freelance/agents/ag-009",
    payload: { inn: "700501123456", type: "INDIVIDUAL_ENTREPRENEUR" },
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── agent.block ───────────────────────────────────────────────
  {
    id: "audit-055",
    occurred_at: at(168, 0),
    actor: { id: 3, name: "Соколова Анна Викторовна", role: "NETWORK_OPS" },
    action: "agent.block",
    action_label: "Агент заблокирован",
    entity_type: "agent",
    entity_id: "ag-007",
    entity_name: "ИП Харламов Виктор Николаевич",
    payload: { reason: "Нарушение условий договора", status_from: "ACTIVE", status_to: "BLOCKED" },
    diff: [
      { field: "status", before: "ACTIVE", after: "BLOCKED" },
    ],
    ip_address: "195.182.35.7",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── external_hr.config_update ─────────────────────────────────
  {
    id: "audit-056",
    occurred_at: at(140, 0),
    actor: { id: 14, name: "Кузнецов Никита Павлович", role: "OPERATOR" },
    action: "external_hr.config_update",
    action_label: "Конфигурация внешней HR-системы обновлена",
    entity_type: "external_hr",
    entity_id: "ext-hr-spar",
    entity_name: "HR Connector — SPAR Сибирь",
    payload: { connector_type: "LAMA", updated_fields: ["sync_interval_min", "webhook_url"] },
    diff: [
      { field: "sync_interval_min", before: 60, after: 30 },
      { field: "webhook_url", before: "https://old.lama.example/hook", after: "https://lama.spar-sibir.ru/hook" },
    ],
    ip_address: "78.37.211.100",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── external_hr.sync_manual ───────────────────────────────────
  {
    id: "audit-057",
    occurred_at: at(14, 0),
    actor: { id: 14, name: "Кузнецов Никита Павлович", role: "OPERATOR" },
    action: "external_hr.sync_manual",
    action_label: "Ручная синхронизация HR-системы",
    entity_type: "external_hr",
    entity_id: "ext-hr-spar",
    entity_name: "HR Connector — SPAR Сибирь",
    payload: { triggered_by: "operator", synced_records: 148, errors: 0 },
    ip_address: "78.37.211.100",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── payment_mode.update (platform_action: true) ────────────────
  {
    id: "audit-058",
    occurred_at: at(200, 0),
    actor: { id: 100, name: "Администратор платформы", role: "NETWORK_OPS", email: "admin@beyondviolet.io" },
    action: "payment_mode.update",
    action_label: "Режим выплат изменён",
    entity_type: "payment_mode",
    entity_id: "org-spar",
    entity_name: "СПАР Сибирь",
    payload: { payment_mode_from: "CLIENT_DIRECT", payment_mode_to: "NOMINAL_ACCOUNT" },
    diff: [
      { field: "payment_mode", before: "CLIENT_DIRECT", after: "NOMINAL_ACCOUNT" },
    ],
    ip_address: "185.30.12.44",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
    platform_action: true,
  },
];
