import type { AuditEntry } from "@/lib/types";

/**
 * @endpoint GET /api/audit
 * 30 audit entries — realistic mix over last 7 days.
 * Actions: task.*, user.*, permission.*, shift.*, settings.*, api_key.*, login.
 */

const now = new Date("2026-05-01T10:00:00+07:00");
const at = (hoursBack: number, minuteOffset = 0) =>
  new Date(
    now.getTime() - hoursBack * 60 * 60 * 1000 - minuteOffset * 60 * 1000
  ).toISOString();

const UAS = {
  mac_chrome: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  win_edge: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0",
  iphone: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/604.1",
  android: "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.82 Mobile Safari/537.36",
  win_chrome: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

export const MOCK_AUDIT_ENTRIES: AuditEntry[] = [
  // ── task.create ────────────────────────────────────────────────
  {
    id: "audit-001",
    occurred_at: at(2, 15),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR", email: "i.romanov@spar-sibir.ru" },
    action: "task.create",
    action_label: "Создание задачи",
    entity_type: "task",
    entity_id: "task-005",
    entity_name: "Проверка сроков годности молочки",
    entity_url: "/tasks/task-005",
    payload: { store_id: 4, assignee_id: 23, type: "ADDITIONAL", source: "MANAGER" },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },
  {
    id: "audit-002",
    occurred_at: at(4, 5),
    actor: { id: 12, name: "Тарасова Ольга Викторовна", role: "SUPERVISOR" },
    action: "task.create",
    action_label: "Создание задачи",
    entity_type: "task",
    entity_id: "task-011",
    entity_name: "Подготовка зоны выпечки",
    entity_url: "/tasks/task-011",
    payload: { store_id: 7, assignee_id: 25, type: "PLANNED", source: "PLANNED" },
    ip_address: "91.243.56.18",
    user_agent: UAS.iphone,
    device_type: "mobile",
  },

  // ── task.start ─────────────────────────────────────────────────
  {
    id: "audit-003",
    occurred_at: at(2, 0),
    actor: { id: 15, name: "Козлова Дарья Андреевна", role: "WORKER" },
    action: "task.start",
    action_label: "Задача начата",
    entity_type: "task",
    entity_id: "task-006",
    entity_name: "Выкладка молочной полки в холодильнике 3",
    entity_url: "/tasks/task-006",
    payload: { state_from: "NEW", state_to: "IN_PROGRESS" },
    ip_address: "213.87.135.4",
    user_agent: UAS.android,
    device_type: "mobile",
  },
  {
    id: "audit-004",
    occurred_at: at(3, 20),
    actor: { id: 18, name: "Федоров Алексей Николаевич", role: "WORKER" },
    action: "task.start",
    action_label: "Задача начата",
    entity_type: "task",
    entity_id: "task-004",
    entity_name: "Приёмка молочки от ООО «Деревенское молочко»",
    entity_url: "/tasks/task-004",
    payload: { state_from: "NEW", state_to: "IN_PROGRESS" },
    ip_address: "213.87.135.9",
    user_agent: UAS.android,
    device_type: "mobile",
  },

  // ── task.pause ─────────────────────────────────────────────────
  {
    id: "audit-005",
    occurred_at: at(1, 20),
    actor: { id: 17, name: "Медведева Татьяна Ивановна", role: "WORKER" },
    action: "task.pause",
    action_label: "Задача приостановлена",
    entity_type: "task",
    entity_id: "task-013",
    entity_name: "Уборка прикассовой зоны",
    entity_url: "/tasks/task-013",
    payload: { state_from: "IN_PROGRESS", state_to: "PAUSED", comment: "Ждёт поставки чистящего средства" },
    ip_address: "188.243.56.78",
    user_agent: UAS.iphone,
    device_type: "mobile",
  },
  {
    id: "audit-006",
    occurred_at: at(1, 40),
    actor: { id: 21, name: "Кириллова Светлана Васильевна", role: "WORKER" },
    action: "task.pause",
    action_label: "Задача приостановлена",
    entity_type: "task",
    entity_id: "task-015",
    entity_name: "Заказ на расходники РЦ Новосибирск",
    entity_url: "/tasks/task-015",
    payload: { comment: "Ожидает подтверждения бюджета от регионального" },
    ip_address: "94.71.218.33",
    user_agent: UAS.android,
    device_type: "mobile",
  },

  // ── task.complete ──────────────────────────────────────────────
  {
    id: "audit-007",
    occurred_at: at(6, 10),
    actor: { id: 20, name: "Попов Владимир Сергеевич", role: "WORKER" },
    action: "task.complete",
    action_label: "Задача завершена",
    entity_type: "task",
    entity_id: "task-010",
    entity_name: "Открытие зоны самообслуживания",
    entity_url: "/tasks/task-010",
    payload: { state_from: "IN_PROGRESS", state_to: "COMPLETED", acceptance_policy: "AUTO" },
    ip_address: "213.87.135.20",
    user_agent: UAS.android,
    device_type: "mobile",
  },
  {
    id: "audit-008",
    occurred_at: at(25, 0),
    actor: { id: 15, name: "Козлова Дарья Андреевна", role: "WORKER" },
    action: "task.complete",
    action_label: "Задача завершена",
    entity_type: "task",
    entity_id: "task-017",
    entity_name: "Раскладка кондитерского фронта",
    entity_url: "/tasks/task-017",
    payload: { state_from: "IN_PROGRESS", state_to: "COMPLETED", has_report_image: true },
    ip_address: "213.87.135.4",
    user_agent: UAS.android,
    device_type: "mobile",
  },

  // ── task.approve ───────────────────────────────────────────────
  {
    id: "audit-009",
    occurred_at: at(10, 5),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "task.approve",
    action_label: "Задача принята",
    entity_type: "task",
    entity_id: "task-017",
    entity_name: "Раскладка кондитерского фронта",
    entity_url: "/tasks/task-017",
    payload: { review_state_from: "ON_REVIEW", review_state_to: "ACCEPTED" },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },
  {
    id: "audit-010",
    occurred_at: at(48, 0),
    actor: { id: 12, name: "Тарасова Ольга Викторовна", role: "SUPERVISOR" },
    action: "task.approve",
    action_label: "Задача принята",
    entity_type: "task",
    entity_id: "task-019",
    entity_name: "Промо-выкладка в зоне входа",
    entity_url: "/tasks/task-019",
    payload: { review_state_from: "ON_REVIEW", review_state_to: "ACCEPTED" },
    ip_address: "91.243.56.18",
    user_agent: UAS.win_chrome,
    device_type: "desktop",
  },

  // ── task.reject ────────────────────────────────────────────────
  {
    id: "audit-011",
    occurred_at: at(4, 0),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "task.reject",
    action_label: "Задача отклонена",
    entity_type: "task",
    entity_id: "task-016",
    entity_name: "Инвентаризация бакалеи",
    entity_url: "/tasks/task-016",
    payload: {
      review_comment: "Отчёт неполный — не хватает скан-листа участка 5",
      review_state_from: "ON_REVIEW",
      review_state_to: "REJECTED",
    },
    diff: [
      { field: "review_state", before: "ON_REVIEW", after: "REJECTED" },
      { field: "review_comment", before: null, after: "Отчёт неполный — не хватает скан-листа участка 5" },
    ],
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── task.update (diff example) ─────────────────────────────────
  {
    id: "audit-012",
    occurred_at: at(5, 30),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "task.update",
    action_label: "Задача обновлена",
    entity_type: "task",
    entity_id: "task-006",
    entity_name: "Выкладка молочной полки в холодильнике 3",
    entity_url: "/tasks/task-006",
    payload: { updated_fields: ["comment"] },
    diff: [
      { field: "comment", before: null, after: "Особое внимание на йогурты — поставка сегодня утром" },
    ],
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── user.update ────────────────────────────────────────────────
  {
    id: "audit-013",
    occurred_at: at(72, 15),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "user.update",
    action_label: "Профиль сотрудника обновлён",
    entity_type: "user",
    entity_id: "26",
    entity_name: "Гусев Павел Михайлович",
    payload: { updated_fields: ["phone", "position_id"] },
    diff: [
      { field: "phone", before: "+7 (913) 150-55-12", after: "+7 (913) 150-55-99" },
      { field: "position_id", before: 3, after: 5 },
    ],
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },
  {
    id: "audit-014",
    occurred_at: at(96, 5),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "user.update",
    action_label: "Профиль сотрудника обновлён",
    entity_type: "user",
    entity_id: "22",
    entity_name: "Степанов Андрей Борисович",
    payload: { updated_fields: ["preferred_locale"] },
    diff: [
      { field: "preferred_locale", before: "ru", after: "en" },
    ],
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── user.activate / user.deactivate ───────────────────────────
  {
    id: "audit-015",
    occurred_at: at(120, 0),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "user.activate",
    action_label: "Сотрудник активирован",
    entity_type: "user",
    entity_id: "31",
    entity_name: "Мельников Евгений Игоревич",
    payload: { freelancer_status_from: "VERIFICATION", freelancer_status_to: "ACTIVE" },
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },
  {
    id: "audit-016",
    occurred_at: at(144, 30),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "user.deactivate",
    action_label: "Сотрудник деактивирован (архивирован)",
    entity_type: "user",
    entity_id: "28",
    entity_name: "Тихонов Игорь Васильевич",
    payload: { archive_reason: "OBSOLETE", archived: true },
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── permission.grant / permission.revoke ───────────────────────
  {
    id: "audit-017",
    occurred_at: at(50, 0),
    actor: { id: 13, name: "Морозова Елена Сергеевна", role: "HR_MANAGER" },
    action: "permission.grant",
    action_label: "Допуск выдан",
    entity_type: "permission",
    entity_id: "perm-024",
    entity_name: "SELF_CHECKOUT → Козлова Дарья",
    payload: { permission: "SELF_CHECKOUT", user_id: 15, user_name: "Козлова Дарья Андреевна" },
    ip_address: "188.124.67.91",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },
  {
    id: "audit-018",
    occurred_at: at(80, 20),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR" },
    action: "permission.revoke",
    action_label: "Допуск отозван",
    entity_type: "permission",
    entity_id: "perm-011",
    entity_name: "CASHIER → Новиков Максим",
    payload: { permission: "CASHIER", user_id: 16, user_name: "Новиков Максим Юрьевич", reason: "Не прошёл переаттестацию" },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── shift.open / shift.close / shift.force_close ───────────────
  {
    id: "audit-019",
    occurred_at: at(8, 0),
    actor: { id: 15, name: "Козлова Дарья Андреевна", role: "WORKER" },
    action: "shift.open",
    action_label: "Смена открыта",
    entity_type: "shift",
    entity_id: "shift-041",
    entity_name: "Смена Козловой 01.05.2026",
    payload: { store_id: 1, planned_start: "08:00:00", actual_start: "07:58:23", late_minutes: 0 },
    ip_address: "213.87.135.4",
    user_agent: UAS.android,
    device_type: "mobile",
  },
  {
    id: "audit-020",
    occurred_at: at(0, 5),
    actor: { id: 22, name: "Степанов Андрей Борисович", role: "WORKER" },
    action: "shift.close",
    action_label: "Смена закрыта",
    entity_type: "shift",
    entity_id: "shift-044",
    entity_name: "Смена Степанова 01.05.2026",
    payload: { store_id: 4, actual_end: at(0, 5), overtime_minutes: 12 },
    ip_address: "94.71.218.33",
    user_agent: UAS.android,
    device_type: "mobile",
  },
  {
    id: "audit-021",
    occurred_at: at(22, 0),
    actor: { id: 5, name: "Иванов Александр Сергеевич", role: "STORE_DIRECTOR" },
    action: "shift.force_close",
    action_label: "Смена принудительно закрыта",
    entity_type: "shift",
    entity_id: "shift-038",
    entity_name: "Смена Белова 29.04.2026",
    payload: { reason: "Сотрудник покинул магазин без закрытия в приложении", user_id: 27 },
    ip_address: "91.185.44.203",
    user_agent: UAS.win_chrome,
    device_type: "desktop",
  },

  // ── settings.update ────────────────────────────────────────────
  {
    id: "audit-022",
    occurred_at: at(100, 0),
    actor: { id: 3, name: "Соколова Анна Викторовна", role: "NETWORK_OPS", email: "a.sokolova@spar-sibir.ru" },
    action: "settings.update",
    action_label: "Настройки организации обновлены",
    entity_type: "organization",
    entity_id: "org-spar",
    entity_name: "СПАР Сибирь",
    payload: { section: "ai_standards" },
    diff: [
      { field: "dairy_writeoff_norm_pct", before: 2.0, after: 2.5 },
      { field: "oos_norm_pct", before: 4.0, after: 3.5 },
    ],
    ip_address: "195.182.35.7",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },
  {
    id: "audit-023",
    occurred_at: at(160, 0),
    actor: { id: 14, name: "Кузнецов Никита Павлович", role: "OPERATOR" },
    action: "settings.update",
    action_label: "Тип работ обновлён",
    entity_type: "work_type",
    entity_id: "4",
    entity_name: "Выкладка",
    payload: { updated_fields: ["default_duration_min"] },
    diff: [
      { field: "default_duration_min", before: 30, after: 35 },
    ],
    ip_address: "78.37.211.100",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },

  // ── api_key.create ─────────────────────────────────────────────
  {
    id: "audit-024",
    occurred_at: at(130, 0),
    actor: { id: 3, name: "Соколова Анна Викторовна", role: "NETWORK_OPS" },
    action: "api_key.create",
    action_label: "API-ключ создан",
    entity_type: "api_key",
    entity_id: "key-005",
    entity_name: "Интеграция POS SPAR Томск пр. Ленина 80",
    payload: { scope: ["tasks:read", "shifts:read"], expires_at: "2027-05-01" },
    ip_address: "195.182.35.7",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },
  {
    id: "audit-025",
    occurred_at: at(145, 0),
    actor: { id: 3, name: "Соколова Анна Викторовна", role: "NETWORK_OPS" },
    action: "api_key.create",
    action_label: "API-ключ создан",
    entity_type: "api_key",
    entity_id: "key-006",
    entity_name: "Webhook LAMA → WFM",
    payload: { scope: ["webhooks:write"], expires_at: null },
    ip_address: "195.182.35.7",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },

  // ── login (everyone) ──────────────────────────────────────────
  {
    id: "audit-026",
    occurred_at: at(8, 30),
    actor: { id: 4, name: "Романов Игорь Алексеевич", role: "SUPERVISOR", email: "i.romanov@spar-sibir.ru" },
    action: "login",
    action_label: "Вход в систему",
    entity_type: "session",
    entity_id: "sess-romanov-0501",
    entity_name: "Сессия Романов 01.05.2026",
    payload: { method: "phone_otp", channel: "telegram" },
    ip_address: "78.37.211.52",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },
  {
    id: "audit-027",
    occurred_at: at(7, 50),
    actor: { id: 15, name: "Козлова Дарья Андреевна", role: "WORKER" },
    action: "login",
    action_label: "Вход в систему",
    entity_type: "session",
    entity_id: "sess-kozlova-0501",
    entity_name: "Сессия Козлова 01.05.2026",
    payload: { method: "phone_otp", channel: "sms_fallback" },
    ip_address: "213.87.135.4",
    user_agent: UAS.android,
    device_type: "mobile",
  },
  {
    id: "audit-028",
    occurred_at: at(9, 0),
    actor: { id: 3, name: "Соколова Анна Викторовна", role: "NETWORK_OPS", email: "a.sokolova@spar-sibir.ru" },
    action: "login",
    action_label: "Вход в систему",
    entity_type: "session",
    entity_id: "sess-sokolova-0501",
    entity_name: "Сессия Соколова 01.05.2026",
    payload: { method: "totp", channel: "authenticator" },
    ip_address: "195.182.35.7",
    user_agent: UAS.mac_chrome,
    device_type: "desktop",
  },
  {
    id: "audit-029",
    occurred_at: at(8, 45),
    actor: { id: 14, name: "Кузнецов Никита Павлович", role: "OPERATOR", email: "n.kuznetsov@spar-sibir.ru" },
    action: "login",
    action_label: "Вход в систему",
    entity_type: "session",
    entity_id: "sess-kuznetsov-0501",
    entity_name: "Сессия Кузнецов 01.05.2026",
    payload: { method: "email_magic_link" },
    ip_address: "78.37.211.100",
    user_agent: UAS.win_edge,
    device_type: "desktop",
  },
  {
    id: "audit-030",
    occurred_at: at(7, 58),
    actor: { id: 12, name: "Тарасова Ольга Викторовна", role: "SUPERVISOR" },
    action: "login",
    action_label: "Вход в систему",
    entity_type: "session",
    entity_id: "sess-tarasova-0501",
    entity_name: "Сессия Тарасова 01.05.2026",
    payload: { method: "phone_otp", channel: "max" },
    ip_address: "91.243.56.18",
    user_agent: UAS.iphone,
    device_type: "mobile",
  },
];
