import type { ServiceNorm } from "@/lib/types";

/**
 * @endpoint GET /api/freelance/service-norms
 * 17 ServiceNorm records. Each (object_format × work_type_id) pair is unique.
 * No duplicates on (object_format, work_type_id) composite key.
 * approved_by = 4 (Романов И.А., SUPERVISOR), approved_at = 2025-11-15.
 * Приёмка = часть Складских работ (id=13), отдельной нормы нет.
 * Production norms (SEWING_WORKSHOP, PRODUCTION_LINE) only apply when org has WORKSHOP.
 */
export const MOCK_SERVICE_NORMS: ServiceNorm[] = [
  // ── SUPERMARKET (6 нормативов) ───────────────────────────────────
  {
    id: "sn-001",
    object_format: "SUPERMARKET",
    work_type_id: 4,
    work_type_name: "Выкладка",
    normative_per_hour: 200,
    unit: "SKU",
    hourly_rate: 380,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },
  {
    id: "sn-002",
    object_format: "SUPERMARKET",
    work_type_id: 2,
    work_type_name: "Касса",
    normative_per_hour: 80,
    unit: "CHECKS",
    hourly_rate: 350,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },
  {
    id: "sn-003",
    object_format: "SUPERMARKET",
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    normative_per_hour: 350,
    unit: "SKU",
    hourly_rate: 420,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },
  {
    id: "sn-004",
    object_format: "SUPERMARKET",
    work_type_id: 13,
    work_type_name: "Складские работы",
    normative_per_hour: 120,
    unit: "BOXES",
    hourly_rate: 400,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },
  {
    id: "sn-005",
    object_format: "SUPERMARKET",
    work_type_id: 12,
    work_type_name: "Уборка",
    normative_per_hour: 250,
    unit: "M2",
    hourly_rate: 280,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },
  {
    id: "sn-006",
    object_format: "SUPERMARKET",
    work_type_id: 5,
    work_type_name: "Переоценка",
    normative_per_hour: 150,
    unit: "PCS",
    hourly_rate: 360,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },

  // ── HYPERMARKET (4 норматива) ────────────────────────────────────
  {
    id: "sn-007",
    object_format: "HYPERMARKET",
    work_type_id: 4,
    work_type_name: "Выкладка",
    normative_per_hour: 220,
    unit: "SKU",
    hourly_rate: 400,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },
  {
    id: "sn-008",
    object_format: "HYPERMARKET",
    work_type_id: 13,
    work_type_name: "Складские работы",
    normative_per_hour: 30,
    unit: "PALLETS",
    hourly_rate: 450,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },
  {
    id: "sn-009",
    object_format: "HYPERMARKET",
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    normative_per_hour: 380,
    unit: "SKU",
    hourly_rate: 440,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },
  {
    id: "sn-010",
    object_format: "HYPERMARKET",
    work_type_id: 2,
    work_type_name: "Касса",
    normative_per_hour: 100,
    unit: "CHECKS",
    hourly_rate: 380,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },

  // ── CONVENIENCE (2 норматива) ────────────────────────────────────
  {
    id: "sn-011",
    object_format: "CONVENIENCE",
    work_type_id: 4,
    work_type_name: "Выкладка",
    normative_per_hour: 180,
    unit: "SKU",
    hourly_rate: 360,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },
  {
    id: "sn-012",
    object_format: "CONVENIENCE",
    work_type_id: 2,
    work_type_name: "Касса",
    normative_per_hour: 60,
    unit: "CHECKS",
    hourly_rate: 320,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },

  // ── SMALL_SHOP (2 норматива) ─────────────────────────────────────
  {
    id: "sn-013",
    object_format: "SMALL_SHOP",
    work_type_id: 4,
    work_type_name: "Выкладка",
    normative_per_hour: 150,
    unit: "SKU",
    hourly_rate: 320,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },
  {
    id: "sn-014",
    object_format: "SMALL_SHOP",
    work_type_id: 2,
    work_type_name: "Касса",
    normative_per_hour: 40,
    unit: "CHECKS",
    hourly_rate: 300,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },

  // ── SEWING_WORKSHOP (2 норматива) — только для org с WORKSHOP ────
  {
    id: "sn-015",
    object_format: "SEWING_WORKSHOP",
    work_type_id: 21,
    work_type_name: "Машинный пошив",
    normative_per_hour: 8,
    unit: "PCS",
    hourly_rate: 280,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },
  {
    id: "sn-016",
    object_format: "SEWING_WORKSHOP",
    work_type_id: 22,
    work_type_name: "Вышивка и маркировка",
    normative_per_hour: 12,
    unit: "PCS",
    hourly_rate: 320,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },

  // ── PRODUCTION_LINE (1 норматив) ─────────────────────────────────
  {
    id: "sn-017",
    object_format: "PRODUCTION_LINE",
    work_type_id: 23,
    work_type_name: "Наполнение",
    normative_per_hour: 200,
    unit: "PCS",
    hourly_rate: 350,
    currency: "RUB",
    approved_by: 4,
    approved_by_name: "Романов И. А.",
    approved_at: "2025-11-15T10:00:00Z",
    archived: false,
  },
];
