import type { Service } from "@/lib/types";
import { daysFromNow, daysAgoFrom } from "./_today";

/**
 * @endpoint GET /api/freelance/services
 * 35 Service records across all ServiceStatus values.
 * Distribution: 8 PLANNED + 3 IN_PROGRESS + 4 COMPLETED + 5 CONFIRMED
 *             + 3 READY_TO_PAY + 8 PAID + 2 NO_SHOW + 2 DISPUTED
 *
 * total_amount = payable_hours × hourly_rate (NOMINAL_ACCOUNT formula).
 * 3 records have actual_hours < scheduled_hours (demo underload).
 * 1 record has underload_not_fault=true (payable > actual).
 * 1 record has manually_adjusted (REGIONAL corrected final amount).
 */
export const MOCK_FREELANCE_SERVICES: Service[] = [
  // ── 8 PLANNED ────────────────────────────────────────────────────
  {
    id: "svc-001",
    freelancer_id: 100,
    freelancer_name: "Краснов Артём Дмитриевич",
    freelancer_phone: "+79131001001",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: "app-001",
    assignment_id: "asgn-001",
    task_ids: ["task-fl-001", "task-fl-002"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysFromNow(5).slice(0, 10),
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 0,
    payable_hours: 8,
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 3040,
    status: "PLANNED",
    created_at: daysAgoFrom(1),
    updated_at: daysAgoFrom(1),
  },
  {
    id: "svc-002",
    freelancer_id: 101,
    freelancer_name: "Смирнова Виктория Олеговна",
    freelancer_phone: "+79131001002",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: "app-001",
    assignment_id: "asgn-002",
    task_ids: ["task-fl-003"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysFromNow(5).slice(0, 10),
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 0,
    payable_hours: 8,
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 3040,
    status: "PLANNED",
    created_at: daysAgoFrom(1),
    updated_at: daysAgoFrom(1),
  },
  {
    id: "svc-003",
    freelancer_id: 106,
    freelancer_name: "Захаров Максим Игоревич",
    freelancer_phone: "+79132001001",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: "app-002",
    assignment_id: "asgn-003",
    task_ids: ["task-fl-004", "task-fl-005"],
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    service_date: daysFromNow(3).slice(0, 10),
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    scheduled_hours: 12,
    actual_hours: 0,
    payable_hours: 12,
    normative_volume: 4560,
    normative_unit: "SKU",
    hourly_rate: 440,
    total_amount: 5280,
    status: "PLANNED",
    created_at: daysAgoFrom(2),
    updated_at: daysAgoFrom(2),
  },
  {
    id: "svc-004",
    freelancer_id: 107,
    freelancer_name: "Громова Наталья Сергеевна",
    freelancer_phone: "+79132001002",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: "app-002",
    assignment_id: "asgn-004",
    task_ids: ["task-fl-006"],
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    service_date: daysFromNow(3).slice(0, 10),
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    scheduled_hours: 12,
    actual_hours: 0,
    payable_hours: 12,
    normative_volume: 4560,
    normative_unit: "SKU",
    hourly_rate: 440,
    total_amount: 5280,
    status: "PLANNED",
    created_at: daysAgoFrom(2),
    updated_at: daysAgoFrom(2),
  },
  {
    id: "svc-005",
    freelancer_id: 113,
    freelancer_name: "Котова Дарья Михайловна",
    freelancer_phone: "+79135001001",
    agent_id: "agent-003",
    agent_name: "ИП Никитин А. И.",
    application_id: "app-003",
    assignment_id: "asgn-005",
    task_ids: ["task-fl-007"],
    store_id: 4,
    store_name: "СПАР Новосибирск, ул. Ленина 55",
    service_date: daysFromNow(1).slice(0, 10),
    work_type_id: 2,
    work_type_name: "Касса",
    scheduled_hours: 6,
    actual_hours: 0,
    payable_hours: 6,
    normative_volume: 600,
    normative_unit: "CHECKS",
    hourly_rate: 380,
    total_amount: 2280,
    status: "PLANNED",
    created_at: daysAgoFrom(0),
    updated_at: daysAgoFrom(0),
  },
  {
    id: "svc-006",
    freelancer_id: 102,
    freelancer_name: "Поляков Денис Сергеевич",
    freelancer_phone: "+79131001003",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: "app-008",
    assignment_id: "asgn-006",
    task_ids: ["task-fl-008", "task-fl-009"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysFromNow(4).slice(0, 10),
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    scheduled_hours: 8,
    actual_hours: 0,
    payable_hours: 8,
    normative_volume: 2800,
    normative_unit: "SKU",
    hourly_rate: 420,
    total_amount: 3360,
    status: "PLANNED",
    created_at: daysAgoFrom(2),
    updated_at: daysAgoFrom(2),
  },
  {
    id: "svc-007",
    freelancer_id: 103,
    freelancer_name: "Орехова Людмила Валентиновна",
    freelancer_phone: "+79131001004",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: "app-008",
    assignment_id: "asgn-007",
    task_ids: ["task-fl-010"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysFromNow(4).slice(0, 10),
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    scheduled_hours: 8,
    actual_hours: 0,
    payable_hours: 8,
    normative_volume: 2800,
    normative_unit: "SKU",
    hourly_rate: 420,
    total_amount: 3360,
    status: "PLANNED",
    created_at: daysAgoFrom(2),
    updated_at: daysAgoFrom(2),
  },
  {
    id: "svc-008",
    freelancer_id: 110,
    freelancer_name: "Сергеев Алексей Юрьевич",
    freelancer_phone: "+79132001005",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: "app-012",
    assignment_id: "asgn-008",
    task_ids: ["task-fl-011"],
    store_id: 270,
    store_name: "С-6 Мичурина 37 (П)",
    service_date: daysFromNow(7).slice(0, 10),
    work_type_id: 13,
    work_type_name: "Складские работы",
    scheduled_hours: 4,
    actual_hours: 0,
    payable_hours: 4,
    normative_volume: 480,
    normative_unit: "BOXES",
    hourly_rate: 400,
    total_amount: 1600,
    status: "PLANNED",
    created_at: daysAgoFrom(2),
    updated_at: daysAgoFrom(2),
  },

  // ── 3 IN_PROGRESS (today) ─────────────────────────────────────────
  {
    id: "svc-009",
    freelancer_id: 104,
    freelancer_name: "Жуков Руслан Анатольевич",
    freelancer_phone: "+79131001005",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: "app-006",
    assignment_id: "asgn-009",
    task_ids: ["task-fl-012", "task-fl-013"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: "2026-05-01",
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 3,
    payable_hours: 8,
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 3040,
    status: "IN_PROGRESS",
    created_at: daysAgoFrom(8),
    updated_at: "2026-05-01T10:00:00Z",
  },
  {
    id: "svc-010",
    freelancer_id: 111,
    freelancer_name: "Власова Светлана Борисовна",
    freelancer_phone: "+79132001006",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: "app-006",
    assignment_id: null,
    task_ids: ["task-fl-014"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: "2026-05-01",
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 2,
    payable_hours: 8,
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 3040,
    status: "IN_PROGRESS",
    created_at: daysAgoFrom(8),
    updated_at: "2026-05-01T09:30:00Z",
  },
  {
    id: "svc-011",
    freelancer_id: 112,
    freelancer_name: "Мартынов Андрей Владимирович",
    freelancer_phone: "+79132001007",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: "app-007",
    assignment_id: null,
    task_ids: ["task-fl-015"],
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    service_date: "2026-05-01",
    work_type_id: 2,
    work_type_name: "Касса",
    scheduled_hours: 6,
    actual_hours: 4,
    payable_hours: 6,
    normative_volume: 600,
    normative_unit: "CHECKS",
    hourly_rate: 380,
    total_amount: 2280,
    status: "IN_PROGRESS",
    created_at: daysAgoFrom(9),
    updated_at: "2026-05-01T08:00:00Z",
  },

  // ── 4 COMPLETED (ожидают подтверждения директора) ────────────────
  {
    id: "svc-012",
    freelancer_id: 105,
    freelancer_name: "Миронова Ольга Петровна",
    freelancer_phone: "+79131001006",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: "app-006",
    assignment_id: "asgn-011",
    task_ids: ["task-fl-016", "task-fl-017"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysAgoFrom(5).slice(0, 10),
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 8,
    payable_hours: 8,
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 3040,
    status: "COMPLETED",
    created_at: daysAgoFrom(8),
    updated_at: daysAgoFrom(5),
  },
  {
    id: "svc-013",
    freelancer_id: 114,
    freelancer_name: "Крылов Василий Петрович",
    freelancer_phone: "+79135001002",
    agent_id: "agent-003",
    agent_name: "ИП Никитин А. И.",
    application_id: "app-014",
    assignment_id: null,
    task_ids: ["task-fl-018"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysAgoFrom(3).slice(0, 10),
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 8,
    payable_hours: 8,
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 3040,
    status: "COMPLETED",
    created_at: daysAgoFrom(4),
    updated_at: daysAgoFrom(3),
  },
  {
    /**
     * Demo underload NOT at fault: пришёл на 8 ч, задач только на 5 ч.
     * actual_hours=5, payable_hours=8 (underload_not_fault=true).
     */
    id: "svc-014",
    freelancer_id: 108,
    freelancer_name: "Федосеев Игорь Николаевич",
    freelancer_phone: "+79132001003",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: "app-006",
    assignment_id: null,
    task_ids: ["task-fl-019"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysAgoFrom(4).slice(0, 10),
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 5,
    payable_hours: 8,
    underload_not_fault: true,
    adjustment_reason: "Недозагрузка не по вине: пришёл на 8 ч, задач только на 5 ч",
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 3040,
    status: "COMPLETED",
    created_at: daysAgoFrom(7),
    updated_at: daysAgoFrom(4),
  },
  {
    /**
     * Demo: исполнитель закончил рано (виноват сам).
     * actual_hours=4, payable_hours=4 (виноват исполнитель).
     */
    id: "svc-015",
    freelancer_id: 109,
    freelancer_name: "Соболева Екатерина Андреевна",
    freelancer_phone: "+79132001004",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: "app-007",
    assignment_id: "asgn-010",
    task_ids: ["task-fl-020"],
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    service_date: daysAgoFrom(6).slice(0, 10),
    work_type_id: 2,
    work_type_name: "Касса",
    scheduled_hours: 6,
    actual_hours: 4,
    payable_hours: 4,
    adjustment_reason: "Исполнитель покинул рабочее место досрочно без уважительной причины",
    normative_volume: 480,
    normative_unit: "CHECKS",
    hourly_rate: 350,
    total_amount: 1400,
    status: "COMPLETED",
    created_at: daysAgoFrom(9),
    updated_at: daysAgoFrom(6),
  },

  // ── 5 CONFIRMED (директор подтвердил, ждёт реестра выплат) ───────
  {
    id: "svc-016",
    freelancer_id: 100,
    freelancer_name: "Краснов Артём Дмитриевич",
    freelancer_phone: "+79131001001",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: "app-006",
    assignment_id: null,
    task_ids: ["task-fl-021"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysAgoFrom(7).slice(0, 10),
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 8,
    payable_hours: 8,
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 3040,
    status: "CONFIRMED",
    confirmed_by: 5,
    confirmed_at: daysAgoFrom(6),
    created_at: daysAgoFrom(10),
    updated_at: daysAgoFrom(6),
  },
  {
    id: "svc-017",
    freelancer_id: 106,
    freelancer_name: "Захаров Максим Игоревич",
    freelancer_phone: "+79132001001",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: "app-007",
    assignment_id: null,
    task_ids: ["task-fl-022", "task-fl-023"],
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    service_date: daysAgoFrom(7).slice(0, 10),
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    scheduled_hours: 10,
    actual_hours: 10,
    payable_hours: 10,
    normative_volume: 3800,
    normative_unit: "SKU",
    hourly_rate: 440,
    total_amount: 4400,
    status: "CONFIRMED",
    confirmed_by: 10,
    confirmed_at: daysAgoFrom(6),
    created_at: daysAgoFrom(10),
    updated_at: daysAgoFrom(6),
  },
  {
    /**
     * manually_adjusted: REGIONAL поднял итоговую сумму поверх расчётной.
     * Автоматический расчёт: 8×350=2800₽, региональный скорректировал до 3300₽.
     */
    id: "svc-018",
    freelancer_id: 113,
    freelancer_name: "Котова Дарья Михайловна",
    freelancer_phone: "+79135001001",
    agent_id: "agent-003",
    agent_name: "ИП Никитин А. И.",
    application_id: "app-009",
    assignment_id: null,
    task_ids: ["task-fl-024"],
    store_id: 5,
    store_name: "СПАР Новосибирск, Красный пр. 200",
    service_date: daysAgoFrom(8).slice(0, 10),
    work_type_id: 13,
    work_type_name: "Складские работы",
    scheduled_hours: 8,
    actual_hours: 8,
    payable_hours: 8,
    normative_volume: 960,
    normative_unit: "BOXES",
    hourly_rate: 350,
    total_amount: 3300,
    status: "CONFIRMED",
    confirmed_by: 8,
    confirmed_at: daysAgoFrom(7),
    manually_adjusted: {
      adjusted_by: 3,
      adjusted_by_name: "Соколова А. В.",
      adjusted_at: daysAgoFrom(6),
      from_amount: 2800,
      to_amount: 3300,
      reason: "Доплата за качественную работу в нестандартных условиях",
    },
    created_at: daysAgoFrom(11),
    updated_at: daysAgoFrom(6),
  },
  {
    id: "svc-019",
    freelancer_id: 114,
    freelancer_name: "Крылов Василий Петрович",
    freelancer_phone: "+79135001002",
    agent_id: "agent-003",
    agent_name: "ИП Никитин А. И.",
    application_id: "app-009",
    assignment_id: null,
    task_ids: ["task-fl-025"],
    store_id: 5,
    store_name: "СПАР Новосибирск, Красный пр. 200",
    service_date: daysAgoFrom(8).slice(0, 10),
    work_type_id: 13,
    work_type_name: "Складские работы",
    scheduled_hours: 8,
    actual_hours: 8,
    payable_hours: 8,
    normative_volume: 960,
    normative_unit: "BOXES",
    hourly_rate: 400,
    total_amount: 3200,
    status: "CONFIRMED",
    confirmed_by: 8,
    confirmed_at: daysAgoFrom(7),
    created_at: daysAgoFrom(11),
    updated_at: daysAgoFrom(7),
  },
  {
    id: "svc-020",
    freelancer_id: 101,
    freelancer_name: "Смирнова Виктория Олеговна",
    freelancer_phone: "+79131001002",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: "app-014",
    assignment_id: null,
    task_ids: ["task-fl-026"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysAgoFrom(3).slice(0, 10),
    work_type_id: 5,
    work_type_name: "Переоценка",
    scheduled_hours: 4,
    actual_hours: 4,
    payable_hours: 4,
    normative_volume: 600,
    normative_unit: "PCS",
    hourly_rate: 360,
    total_amount: 1440,
    status: "CONFIRMED",
    confirmed_by: 5,
    confirmed_at: daysAgoFrom(2),
    created_at: daysAgoFrom(5),
    updated_at: daysAgoFrom(2),
  },

  // ── 3 READY_TO_PAY (в Номинальном счёте) ─────────────────────────
  {
    id: "svc-021",
    freelancer_id: 105,
    freelancer_name: "Миронова Ольга Петровна",
    freelancer_phone: "+79131001006",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: "app-006",
    assignment_id: null,
    task_ids: ["task-fl-027"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysAgoFrom(9).slice(0, 10),
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 8,
    payable_hours: 8,
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 3040,
    payout_id: "payout-009",
    status: "READY_TO_PAY",
    confirmed_by: 5,
    confirmed_at: daysAgoFrom(8),
    created_at: daysAgoFrom(12),
    updated_at: daysAgoFrom(8),
  },
  {
    id: "svc-022",
    freelancer_id: 107,
    freelancer_name: "Громова Наталья Сергеевна",
    freelancer_phone: "+79132001002",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: "app-007",
    assignment_id: null,
    task_ids: ["task-fl-028"],
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    service_date: daysAgoFrom(9).slice(0, 10),
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    scheduled_hours: 10,
    actual_hours: 9,
    payable_hours: 10,
    underload_not_fault: false,
    normative_volume: 3800,
    normative_unit: "SKU",
    hourly_rate: 440,
    total_amount: 4400,
    payout_id: "payout-009",
    status: "READY_TO_PAY",
    confirmed_by: 10,
    confirmed_at: daysAgoFrom(8),
    created_at: daysAgoFrom(12),
    updated_at: daysAgoFrom(8),
  },
  {
    id: "svc-023",
    freelancer_id: 110,
    freelancer_name: "Сергеев Алексей Юрьевич",
    freelancer_phone: "+79132001005",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: "app-009",
    assignment_id: null,
    task_ids: ["task-fl-029"],
    store_id: 5,
    store_name: "СПАР Новосибирск, Красный пр. 200",
    service_date: daysAgoFrom(9).slice(0, 10),
    work_type_id: 12,
    work_type_name: "Уборка",
    scheduled_hours: 6,
    actual_hours: 6,
    payable_hours: 6,
    normative_volume: 1500,
    normative_unit: "M2",
    hourly_rate: 280,
    total_amount: 1680,
    payout_id: "payout-010",
    status: "READY_TO_PAY",
    confirmed_by: 7,
    confirmed_at: daysAgoFrom(8),
    created_at: daysAgoFrom(12),
    updated_at: daysAgoFrom(8),
  },

  // ── 8 PAID (история прошлых недель) ──────────────────────────────
  {
    id: "svc-024",
    freelancer_id: 100,
    freelancer_name: "Краснов Артём Дмитриевич",
    freelancer_phone: "+79131001001",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: null,
    assignment_id: null,
    task_ids: ["task-fl-030"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysAgoFrom(14).slice(0, 10),
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 8,
    payable_hours: 8,
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 3040,
    payout_id: "payout-001",
    status: "PAID",
    confirmed_by: 5,
    confirmed_at: daysAgoFrom(13),
    created_at: daysAgoFrom(17),
    updated_at: daysAgoFrom(12),
  },
  {
    id: "svc-025",
    freelancer_id: 101,
    freelancer_name: "Смирнова Виктория Олеговна",
    freelancer_phone: "+79131001002",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: null,
    assignment_id: null,
    task_ids: ["task-fl-031"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysAgoFrom(14).slice(0, 10),
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 8,
    payable_hours: 8,
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 3040,
    payout_id: "payout-001",
    status: "PAID",
    confirmed_by: 5,
    confirmed_at: daysAgoFrom(13),
    created_at: daysAgoFrom(17),
    updated_at: daysAgoFrom(12),
  },
  {
    id: "svc-026",
    freelancer_id: 106,
    freelancer_name: "Захаров Максим Игоревич",
    freelancer_phone: "+79132001001",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: null,
    assignment_id: null,
    task_ids: ["task-fl-032"],
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    service_date: daysAgoFrom(14).slice(0, 10),
    work_type_id: 13,
    work_type_name: "Складские работы",
    scheduled_hours: 8,
    actual_hours: 8,
    payable_hours: 8,
    normative_volume: 960,
    normative_unit: "BOXES",
    hourly_rate: 400,
    total_amount: 3200,
    payout_id: "payout-002",
    status: "PAID",
    confirmed_by: 10,
    confirmed_at: daysAgoFrom(13),
    created_at: daysAgoFrom(17),
    updated_at: daysAgoFrom(12),
  },
  {
    id: "svc-027",
    freelancer_id: 107,
    freelancer_name: "Громова Наталья Сергеевна",
    freelancer_phone: "+79132001002",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: null,
    assignment_id: null,
    task_ids: ["task-fl-033"],
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    service_date: daysAgoFrom(14).slice(0, 10),
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    scheduled_hours: 10,
    actual_hours: 10,
    payable_hours: 10,
    normative_volume: 4400,
    normative_unit: "SKU",
    hourly_rate: 440,
    total_amount: 4400,
    payout_id: "payout-002",
    status: "PAID",
    confirmed_by: 10,
    confirmed_at: daysAgoFrom(13),
    created_at: daysAgoFrom(17),
    updated_at: daysAgoFrom(12),
  },
  {
    id: "svc-028",
    freelancer_id: 102,
    freelancer_name: "Поляков Денис Сергеевич",
    freelancer_phone: "+79131001003",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: null,
    assignment_id: null,
    task_ids: ["task-fl-034"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysAgoFrom(21).slice(0, 10),
    work_type_id: 5,
    work_type_name: "Переоценка",
    scheduled_hours: 6,
    actual_hours: 6,
    payable_hours: 6,
    normative_volume: 900,
    normative_unit: "PCS",
    hourly_rate: 360,
    total_amount: 2160,
    payout_id: "payout-003",
    status: "PAID",
    confirmed_by: 5,
    confirmed_at: daysAgoFrom(20),
    created_at: daysAgoFrom(24),
    updated_at: daysAgoFrom(19),
  },
  {
    id: "svc-029",
    freelancer_id: 113,
    freelancer_name: "Котова Дарья Михайловна",
    freelancer_phone: "+79135001001",
    agent_id: "agent-003",
    agent_name: "ИП Никитин А. И.",
    application_id: null,
    assignment_id: null,
    task_ids: ["task-fl-035"],
    store_id: 4,
    store_name: "СПАР Новосибирск, ул. Ленина 55",
    service_date: daysAgoFrom(21).slice(0, 10),
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 10,
    actual_hours: 10,
    payable_hours: 10,
    normative_volume: 2200,
    normative_unit: "SKU",
    hourly_rate: 400,
    total_amount: 4000,
    payout_id: "payout-004",
    status: "PAID",
    confirmed_by: 7,
    confirmed_at: daysAgoFrom(20),
    created_at: daysAgoFrom(24),
    updated_at: daysAgoFrom(19),
  },
  {
    id: "svc-030",
    freelancer_id: 108,
    freelancer_name: "Федосеев Игорь Николаевич",
    freelancer_phone: "+79132001003",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: null,
    assignment_id: null,
    task_ids: ["task-fl-036"],
    store_id: 6,
    store_name: "СПАР Кемерово, пр. Советский 50",
    service_date: daysAgoFrom(21).slice(0, 10),
    work_type_id: 13,
    work_type_name: "Складские работы",
    scheduled_hours: 8,
    actual_hours: 8,
    payable_hours: 8,
    normative_volume: 960,
    normative_unit: "BOXES",
    hourly_rate: 400,
    total_amount: 3200,
    payout_id: "payout-005",
    status: "PAID",
    confirmed_by: 9,
    confirmed_at: daysAgoFrom(20),
    created_at: daysAgoFrom(24),
    updated_at: daysAgoFrom(19),
  },
  {
    id: "svc-031",
    freelancer_id: 109,
    freelancer_name: "Соболева Екатерина Андреевна",
    freelancer_phone: "+79132001004",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: null,
    assignment_id: null,
    task_ids: ["task-fl-037"],
    store_id: 6,
    store_name: "СПАР Кемерово, пр. Советский 50",
    service_date: daysAgoFrom(21).slice(0, 10),
    work_type_id: 2,
    work_type_name: "Касса",
    scheduled_hours: 6,
    actual_hours: 6,
    payable_hours: 6,
    normative_volume: 600,
    normative_unit: "CHECKS",
    hourly_rate: 350,
    total_amount: 2100,
    payout_id: "payout-005",
    status: "PAID",
    confirmed_by: 9,
    confirmed_at: daysAgoFrom(20),
    created_at: daysAgoFrom(24),
    updated_at: daysAgoFrom(19),
  },

  // ── 2 NO_SHOW ─────────────────────────────────────────────────────
  {
    id: "svc-032",
    freelancer_id: 116,
    freelancer_name: "Тихомиров Сергей Васильевич",
    freelancer_phone: "+79133002001",
    agent_id: null,
    agent_name: null,
    application_id: "app-006",
    assignment_id: null,
    task_ids: [],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysAgoFrom(11).slice(0, 10),
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 0,
    payable_hours: 0,
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 0,
    no_show_reason: "Исполнитель не вышел на смену, на звонки не отвечает",
    status: "NO_SHOW",
    created_at: daysAgoFrom(14),
    updated_at: daysAgoFrom(11),
  },
  {
    id: "svc-033",
    freelancer_id: 105,
    freelancer_name: "Миронова Ольга Петровна",
    freelancer_phone: "+79131001006",
    agent_id: "agent-001",
    agent_name: "ИП Захарова М. С.",
    application_id: "app-007",
    assignment_id: null,
    task_ids: [],
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    service_date: daysAgoFrom(10).slice(0, 10),
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    scheduled_hours: 10,
    actual_hours: 0,
    payable_hours: 0,
    normative_volume: 3800,
    normative_unit: "SKU",
    hourly_rate: 440,
    total_amount: 0,
    no_show_reason: "Исполнитель сообщил об отказе за час до начала смены",
    status: "NO_SHOW",
    created_at: daysAgoFrom(13),
    updated_at: daysAgoFrom(10),
  },

  // ── 2 DISPUTED ───────────────────────────────────────────────────
  {
    id: "svc-034",
    freelancer_id: 111,
    freelancer_name: "Власова Светлана Борисовна",
    freelancer_phone: "+79132001006",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: "app-006",
    assignment_id: null,
    task_ids: ["task-fl-038"],
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    service_date: daysAgoFrom(6).slice(0, 10),
    work_type_id: 4,
    work_type_name: "Выкладка",
    scheduled_hours: 8,
    actual_hours: 6,
    payable_hours: 6,
    normative_volume: 1600,
    normative_unit: "SKU",
    hourly_rate: 380,
    total_amount: 2280,
    dispute_reason: "Директор отклонил: несоответствие качества выкладки стандартам магазина",
    status: "DISPUTED",
    created_at: daysAgoFrom(9),
    updated_at: daysAgoFrom(6),
  },
  {
    id: "svc-035",
    freelancer_id: 112,
    freelancer_name: "Мартынов Андрей Владимирович",
    freelancer_phone: "+79132001007",
    agent_id: "agent-002",
    agent_name: "ООО «Кадровый партнёр»",
    application_id: "app-007",
    assignment_id: null,
    task_ids: ["task-fl-039"],
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    service_date: daysAgoFrom(5).slice(0, 10),
    work_type_id: 13,
    work_type_name: "Складские работы",
    scheduled_hours: 6,
    actual_hours: 4,
    payable_hours: 4,
    normative_volume: 720,
    normative_unit: "BOXES",
    hourly_rate: 400,
    total_amount: 1600,
    dispute_reason: "Директор отклонил: не весь объём выполнен, часть паллет не разобрана",
    status: "DISPUTED",
    created_at: daysAgoFrom(8),
    updated_at: daysAgoFrom(5),
  },
];
