import type { User } from "@/lib/types";

/**
 * @endpoint GET /api/freelance/freelancers
 * 23 FREELANCE users. IDs start at 100 to avoid collision with MOCK_USERS (1-31).
 *
 * Distribution:
 *   - 6 ACTIVE через agent-001 (ИП Захарова)
 *   - 7 ACTIVE через agent-002 (ООО «Кадровый партнёр»; 2 EXTERNAL_SYNC)
 *   - 2 ACTIVE через agent-003 (ИП Никитин)
 *   - 5 ACTIVE независимых (agent_id: null) — фрилансер не закреплён за агентом
 *   - 1 NEW + 1 BLOCKED + 1 ARCHIVED
 *
 * agent_id опционален: фрилансер может работать самостоятельно (CLIENT_DIRECT
 * payment_mode), либо через агента-ИП (NOMINAL_ACCOUNT mode).
 */
export const MOCK_FREELANCERS: User[] = [
  // ── 6 ACTIVE with agent-001 (ИП Захарова М.С.) ──────────────────
  {
    id: 100,
    sso_id: "sso-fl-100",
    phone: "+79131001001",
    first_name: "Артём",
    last_name: "Краснов",
    middle_name: "Дмитриевич",
    type: "FREELANCE",
    hired_at: "2025-10-01",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-001",
    oferta_accepted_at: "2025-10-01",
    rating: 4.7,
    source: "MANUAL",
  },
  {
    id: 101,
    sso_id: "sso-fl-101",
    phone: "+79131001002",
    first_name: "Виктория",
    last_name: "Смирнова",
    middle_name: "Олеговна",
    type: "FREELANCE",
    hired_at: "2025-10-15",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-001",
    oferta_accepted_at: "2025-10-15",
    rating: 4.5,
    source: "MANUAL",
  },
  {
    id: 102,
    sso_id: "sso-fl-102",
    phone: "+79131001003",
    first_name: "Денис",
    last_name: "Поляков",
    middle_name: "Сергеевич",
    type: "FREELANCE",
    hired_at: "2025-11-01",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-001",
    oferta_accepted_at: "2025-11-01",
    rating: 4.3,
    source: "MANUAL",
  },
  {
    id: 103,
    sso_id: "sso-fl-103",
    phone: "+79131001004",
    first_name: "Людмила",
    last_name: "Орехова",
    middle_name: "Валентиновна",
    type: "FREELANCE",
    hired_at: "2025-11-20",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-001",
    oferta_accepted_at: "2025-11-20",
    rating: 4.8,
    source: "MANUAL",
  },
  {
    id: 104,
    sso_id: "sso-fl-104",
    phone: "+79131001005",
    first_name: "Руслан",
    last_name: "Жуков",
    middle_name: "Анатольевич",
    type: "FREELANCE",
    hired_at: "2025-12-05",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-001",
    oferta_accepted_at: "2025-12-05",
    rating: 4.2,
    source: "MANUAL",
  },
  {
    id: 105,
    sso_id: "sso-fl-105",
    phone: "+79131001006",
    first_name: "Ольга",
    last_name: "Миронова",
    middle_name: "Петровна",
    type: "FREELANCE",
    hired_at: "2026-01-10",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-001",
    oferta_accepted_at: "2026-01-10",
    rating: 4.6,
    source: "MANUAL",
  },

  // ── 7 ACTIVE with agent-002 (ООО «Кадровый партнёр»), 2 EXTERNAL_SYNC ──
  {
    id: 106,
    sso_id: "sso-fl-106",
    phone: "+79132001001",
    first_name: "Максим",
    last_name: "Захаров",
    middle_name: "Игоревич",
    type: "FREELANCE",
    hired_at: "2025-12-01",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-002",
    oferta_accepted_at: "2025-12-01",
    rating: 4.4,
    source: "MANUAL",
  },
  {
    id: 107,
    sso_id: "sso-fl-107",
    phone: "+79132001002",
    first_name: "Наталья",
    last_name: "Громова",
    middle_name: "Сергеевна",
    type: "FREELANCE",
    hired_at: "2025-12-10",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-002",
    oferta_accepted_at: "2025-12-10",
    rating: 4.9,
    source: "MANUAL",
  },
  {
    id: 108,
    sso_id: "sso-fl-108",
    phone: "+79132001003",
    first_name: "Игорь",
    last_name: "Федосеев",
    middle_name: "Николаевич",
    type: "FREELANCE",
    hired_at: "2026-01-05",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-002",
    oferta_accepted_at: "2026-01-05",
    rating: 4.3,
    source: "MANUAL",
  },
  {
    id: 109,
    sso_id: "sso-fl-109",
    phone: "+79132001004",
    first_name: "Екатерина",
    last_name: "Соболева",
    middle_name: "Андреевна",
    type: "FREELANCE",
    hired_at: "2026-01-15",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-002",
    oferta_accepted_at: "2026-01-15",
    rating: 4.7,
    source: "MANUAL",
  },
  {
    id: 110,
    sso_id: "sso-fl-110",
    phone: "+79132001005",
    first_name: "Алексей",
    last_name: "Сергеев",
    middle_name: "Юрьевич",
    type: "FREELANCE",
    hired_at: "2026-02-01",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-002",
    oferta_accepted_at: "2026-02-01",
    rating: 4.5,
    source: "MANUAL",
  },
  {
    /** EXTERNAL_SYNC — пришёл из внешней HR-системы SPAR */
    id: 111,
    sso_id: "sso-fl-111",
    phone: "+79132001006",
    first_name: "Светлана",
    last_name: "Власова",
    middle_name: "Борисовна",
    type: "FREELANCE",
    hired_at: "2026-02-20",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-002",
    oferta_accepted_at: "2026-02-20",
    rating: 4.6,
    source: "EXTERNAL_SYNC",
  },
  {
    /** EXTERNAL_SYNC — второй пример из внешней HR */
    id: 112,
    sso_id: "sso-fl-112",
    phone: "+79132001007",
    first_name: "Андрей",
    last_name: "Мартынов",
    middle_name: "Владимирович",
    type: "FREELANCE",
    hired_at: "2026-03-05",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-002",
    oferta_accepted_at: "2026-03-05",
    rating: 4.4,
    source: "EXTERNAL_SYNC",
  },

  // ── 2 ACTIVE with agent-003 (ИП Никитин А.И.) ───────────────────
  {
    id: 113,
    sso_id: "sso-fl-113",
    phone: "+79135001001",
    first_name: "Дарья",
    last_name: "Котова",
    middle_name: "Михайловна",
    type: "FREELANCE",
    hired_at: "2026-02-10",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-003",
    oferta_accepted_at: "2026-02-10",
    rating: 4.8,
    source: "MANUAL",
  },
  {
    id: 114,
    sso_id: "sso-fl-114",
    phone: "+79135001002",
    first_name: "Василий",
    last_name: "Крылов",
    middle_name: "Петрович",
    type: "FREELANCE",
    hired_at: "2026-03-01",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-003",
    oferta_accepted_at: "2026-03-01",
    rating: 4.5,
    source: "MANUAL",
  },

  // ── 1 NEW (только добавлен телефон, оферта не подписана) ─────────
  {
    id: 115,
    sso_id: "sso-fl-115",
    phone: "+79133001001",
    first_name: "Кирилл",
    last_name: "Новиков",
    middle_name: "Алексеевич",
    type: "FREELANCE",
    hired_at: "2026-04-28",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "NEW",
    agent_id: "agent-001",
    oferta_accepted_at: null,
    rating: undefined,
    source: "MANUAL",
  },

  // ── 5 ACTIVE независимых (без agent_id) — фрилансер сам по себе ──
  {
    id: 118,
    sso_id: "sso-fl-118",
    phone: "+79136001001",
    first_name: "Иван",
    last_name: "Соколов",
    middle_name: "Сергеевич",
    type: "FREELANCE",
    hired_at: "2025-09-15",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: null,
    oferta_accepted_at: "2025-09-15",
    rating: 4.6,
    source: "MANUAL",
  },
  {
    id: 119,
    sso_id: "sso-fl-119",
    phone: "+79136001002",
    first_name: "Алина",
    last_name: "Жукова",
    middle_name: "Дмитриевна",
    type: "FREELANCE",
    hired_at: "2025-11-20",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: null,
    oferta_accepted_at: "2025-11-20",
    rating: 4.4,
    source: "MANUAL",
  },
  {
    id: 120,
    sso_id: "sso-fl-120",
    phone: "+79136001003",
    first_name: "Роман",
    last_name: "Морозов",
    middle_name: "Андреевич",
    type: "FREELANCE",
    hired_at: "2026-01-10",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    freelancer_status: "ACTIVE",
    agent_id: null,
    oferta_accepted_at: "2026-01-10",
    rating: 4.2,
    source: "MANUAL",
  },
  {
    id: 121,
    sso_id: "sso-fl-121",
    phone: "+79136001004",
    first_name: "Татьяна",
    last_name: "Богданова",
    middle_name: "Игоревна",
    type: "FREELANCE",
    hired_at: "2026-02-22",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: null,
    oferta_accepted_at: "2026-02-22",
    rating: 4.7,
    source: "MANUAL",
  },
  {
    id: 122,
    sso_id: "sso-fl-122",
    phone: "+79136001005",
    first_name: "Никита",
    last_name: "Лебедев",
    middle_name: "Валерьевич",
    type: "FREELANCE",
    hired_at: "2026-03-12",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: null,
    oferta_accepted_at: "2026-03-12",
    rating: 4.0,
    source: "MANUAL",
  },

  // ── 1 BLOCKED ────────────────────────────────────────────────────
  {
    id: 116,
    sso_id: "sso-fl-116",
    phone: "+79133002001",
    first_name: "Сергей",
    last_name: "Тихомиров",
    middle_name: "Васильевич",
    type: "FREELANCE",
    hired_at: "2025-08-01",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "BLOCKED",
    agent_id: null,
    oferta_accepted_at: "2025-08-01",
    rating: undefined,
    source: "MANUAL",
  },

  // ── 1 ARCHIVED ───────────────────────────────────────────────────
  {
    id: 117,
    sso_id: "sso-fl-117",
    phone: "+79133003001",
    first_name: "Марина",
    last_name: "Ефимова",
    middle_name: "Константиновна",
    type: "FREELANCE",
    hired_at: "2025-05-01",
    archived: true,
    archive_reason: "OBSOLETE",
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ARCHIVED",
    agent_id: null,
    oferta_accepted_at: "2025-05-01",
    rating: undefined,
    source: "MANUAL",
  },
];
