import type { AgentEarning } from "@/lib/types";
import { daysAgoFrom } from "./_today";

/**
 * @endpoint GET /api/freelance/agent-earnings
 * 25 AgentEarning records linked to Payout PAID + services.
 * Grouped by agent_id × payout_date.
 * commission_amount = round(gross_amount_base * commission_pct / 100).
 * Status: PAID for older records, CALCULATED for fresh ones.
 */
export const MOCK_AGENT_EARNINGS: AgentEarning[] = [
  // ── agent-001 (ИП Захарова М.С., 10%) — linked to paid payouts ──
  {
    id: "ae-001",
    agent_id: "agent-001",
    period_date: daysAgoFrom(12).slice(0, 10),
    freelancer_id: 100,
    freelancer_name: "Краснов Артём Дмитриевич",
    service_id: "svc-024",
    gross_amount_base: 3040,
    commission_pct: 10,
    commission_amount: 304,
    payout_id: "payout-001",
    status: "PAID",
    created_at: daysAgoFrom(12),
  },
  {
    id: "ae-002",
    agent_id: "agent-001",
    period_date: daysAgoFrom(12).slice(0, 10),
    freelancer_id: 101,
    freelancer_name: "Смирнова Виктория Олеговна",
    service_id: "svc-025",
    gross_amount_base: 3040,
    commission_pct: 10,
    commission_amount: 304,
    payout_id: "payout-001",
    status: "PAID",
    created_at: daysAgoFrom(12),
  },
  {
    id: "ae-003",
    agent_id: "agent-001",
    period_date: daysAgoFrom(11).slice(0, 10),
    freelancer_id: 102,
    freelancer_name: "Поляков Денис Сергеевич",
    service_id: "svc-028",
    gross_amount_base: 2160,
    commission_pct: 10,
    commission_amount: 216,
    payout_id: "payout-003",
    status: "PAID",
    created_at: daysAgoFrom(11),
  },
  {
    id: "ae-004",
    agent_id: "agent-001",
    period_date: daysAgoFrom(18).slice(0, 10),
    freelancer_id: 103,
    freelancer_name: "Орехова Людмила Валентиновна",
    service_id: "svc-012",
    gross_amount_base: 3040,
    commission_pct: 10,
    commission_amount: 304,
    payout_id: "payout-006",
    status: "PAID",
    created_at: daysAgoFrom(18),
  },
  {
    id: "ae-005",
    agent_id: "agent-001",
    period_date: daysAgoFrom(18).slice(0, 10),
    freelancer_id: 104,
    freelancer_name: "Жуков Руслан Анатольевич",
    service_id: "svc-016",
    gross_amount_base: 3040,
    commission_pct: 10,
    commission_amount: 304,
    payout_id: "payout-006",
    status: "PAID",
    created_at: daysAgoFrom(18),
  },
  {
    id: "ae-006",
    agent_id: "agent-001",
    period_date: daysAgoFrom(18).slice(0, 10),
    freelancer_id: 105,
    freelancer_name: "Миронова Ольга Петровна",
    service_id: "svc-021",
    gross_amount_base: 3040,
    commission_pct: 10,
    commission_amount: 304,
    payout_id: "payout-006",
    status: "PAID",
    created_at: daysAgoFrom(18),
  },
  {
    id: "ae-007",
    agent_id: "agent-001",
    period_date: daysAgoFrom(1).slice(0, 10),
    freelancer_id: 105,
    freelancer_name: "Миронова Ольга Петровна",
    service_id: "svc-016",
    gross_amount_base: 3040,
    commission_pct: 10,
    commission_amount: 304,
    payout_id: "payout-007",
    status: "CALCULATED",
    created_at: daysAgoFrom(2),
  },

  // ── agent-002 (ООО «Кадровый партнёр», 8%) ───────────────────────
  {
    id: "ae-008",
    agent_id: "agent-002",
    period_date: daysAgoFrom(12).slice(0, 10),
    freelancer_id: 106,
    freelancer_name: "Захаров Максим Игоревич",
    service_id: "svc-026",
    gross_amount_base: 3200,
    commission_pct: 8,
    commission_amount: 256,
    payout_id: "payout-002",
    status: "PAID",
    created_at: daysAgoFrom(12),
  },
  {
    id: "ae-009",
    agent_id: "agent-002",
    period_date: daysAgoFrom(12).slice(0, 10),
    freelancer_id: 107,
    freelancer_name: "Громова Наталья Сергеевна",
    service_id: "svc-027",
    gross_amount_base: 4400,
    commission_pct: 8,
    commission_amount: 352,
    payout_id: "payout-002",
    status: "PAID",
    created_at: daysAgoFrom(12),
  },
  {
    id: "ae-010",
    agent_id: "agent-002",
    period_date: daysAgoFrom(11).slice(0, 10),
    freelancer_id: 108,
    freelancer_name: "Федосеев Игорь Николаевич",
    service_id: "svc-030",
    gross_amount_base: 3200,
    commission_pct: 8,
    commission_amount: 256,
    payout_id: "payout-005",
    status: "PAID",
    created_at: daysAgoFrom(11),
  },
  {
    id: "ae-011",
    agent_id: "agent-002",
    period_date: daysAgoFrom(11).slice(0, 10),
    freelancer_id: 109,
    freelancer_name: "Соболева Екатерина Андреевна",
    service_id: "svc-031",
    gross_amount_base: 2100,
    commission_pct: 8,
    commission_amount: 168,
    payout_id: "payout-005",
    status: "PAID",
    created_at: daysAgoFrom(11),
  },
  {
    id: "ae-012",
    agent_id: "agent-002",
    period_date: daysAgoFrom(18).slice(0, 10),
    freelancer_id: 110,
    freelancer_name: "Сергеев Алексей Юрьевич",
    service_id: "svc-022",
    gross_amount_base: 4400,
    commission_pct: 8,
    commission_amount: 352,
    payout_id: null,
    status: "PAID",
    created_at: daysAgoFrom(18),
  },
  {
    id: "ae-013",
    agent_id: "agent-002",
    period_date: daysAgoFrom(18).slice(0, 10),
    freelancer_id: 111,
    freelancer_name: "Власова Светлана Борисовна",
    service_id: "svc-023",
    gross_amount_base: 1680,
    commission_pct: 8,
    commission_amount: 134,
    payout_id: null,
    status: "PAID",
    created_at: daysAgoFrom(18),
  },
  {
    id: "ae-014",
    agent_id: "agent-002",
    period_date: daysAgoFrom(18).slice(0, 10),
    freelancer_id: 112,
    freelancer_name: "Мартынов Андрей Владимирович",
    service_id: "svc-017",
    gross_amount_base: 4400,
    commission_pct: 8,
    commission_amount: 352,
    payout_id: null,
    status: "PAID",
    created_at: daysAgoFrom(18),
  },
  {
    id: "ae-015",
    agent_id: "agent-002",
    period_date: daysAgoFrom(1).slice(0, 10),
    freelancer_id: 106,
    freelancer_name: "Захаров Максим Игоревич",
    service_id: "svc-017",
    gross_amount_base: 4400,
    commission_pct: 8,
    commission_amount: 352,
    payout_id: "payout-008",
    status: "CALCULATED",
    created_at: daysAgoFrom(2),
  },
  {
    id: "ae-016",
    agent_id: "agent-002",
    period_date: daysAgoFrom(7).slice(0, 10),
    freelancer_id: 107,
    freelancer_name: "Громова Наталья Сергеевна",
    service_id: "svc-022",
    gross_amount_base: 4400,
    commission_pct: 8,
    commission_amount: 352,
    payout_id: null,
    status: "PAID",
    created_at: daysAgoFrom(7),
  },
  {
    id: "ae-017",
    agent_id: "agent-002",
    period_date: daysAgoFrom(7).slice(0, 10),
    freelancer_id: 108,
    freelancer_name: "Федосеев Игорь Николаевич",
    service_id: "svc-026",
    gross_amount_base: 3200,
    commission_pct: 8,
    commission_amount: 256,
    payout_id: null,
    status: "PAID",
    created_at: daysAgoFrom(7),
  },

  // ── agent-003 (ИП Никитин А.И., 12%) ─────────────────────────────
  {
    id: "ae-018",
    agent_id: "agent-003",
    period_date: daysAgoFrom(11).slice(0, 10),
    freelancer_id: 113,
    freelancer_name: "Котова Дарья Михайловна",
    service_id: "svc-029",
    gross_amount_base: 4000,
    commission_pct: 12,
    commission_amount: 480,
    payout_id: "payout-004",
    status: "PAID",
    created_at: daysAgoFrom(11),
  },
  {
    id: "ae-019",
    agent_id: "agent-003",
    period_date: daysAgoFrom(18).slice(0, 10),
    freelancer_id: 114,
    freelancer_name: "Крылов Василий Петрович",
    service_id: "svc-019",
    gross_amount_base: 3200,
    commission_pct: 12,
    commission_amount: 384,
    payout_id: "payout-006",
    status: "PAID",
    created_at: daysAgoFrom(18),
  },
  {
    id: "ae-020",
    agent_id: "agent-003",
    period_date: daysAgoFrom(7).slice(0, 10),
    freelancer_id: 113,
    freelancer_name: "Котова Дарья Михайловна",
    service_id: "svc-018",
    gross_amount_base: 3300,
    commission_pct: 12,
    commission_amount: 396,
    payout_id: null,
    status: "PAID",
    created_at: daysAgoFrom(7),
  },
  {
    id: "ae-021",
    agent_id: "agent-003",
    period_date: daysAgoFrom(3).slice(0, 10),
    freelancer_id: 114,
    freelancer_name: "Крылов Василий Петрович",
    service_id: "svc-013",
    gross_amount_base: 3040,
    commission_pct: 12,
    commission_amount: 365,
    payout_id: null,
    status: "CALCULATED",
    created_at: daysAgoFrom(3),
  },
  {
    id: "ae-022",
    agent_id: "agent-003",
    period_date: daysAgoFrom(3).slice(0, 10),
    freelancer_id: 113,
    freelancer_name: "Котова Дарья Михайловна",
    service_id: "svc-020",
    gross_amount_base: 1440,
    commission_pct: 12,
    commission_amount: 173,
    payout_id: null,
    status: "CALCULATED",
    created_at: daysAgoFrom(3),
  },

  // ── agent-001 — additional history ──────────────────────────────
  {
    id: "ae-023",
    agent_id: "agent-001",
    period_date: daysAgoFrom(25).slice(0, 10),
    freelancer_id: 100,
    freelancer_name: "Краснов Артём Дмитриевич",
    service_id: "svc-024",
    gross_amount_base: 2800,
    commission_pct: 10,
    commission_amount: 280,
    payout_id: null,
    status: "PAID",
    created_at: daysAgoFrom(25),
  },
  {
    id: "ae-024",
    agent_id: "agent-002",
    period_date: daysAgoFrom(25).slice(0, 10),
    freelancer_id: 111,
    freelancer_name: "Власова Светлана Борисовна",
    service_id: "svc-034",
    gross_amount_base: 2280,
    commission_pct: 8,
    commission_amount: 182,
    payout_id: null,
    status: "PAID",
    created_at: daysAgoFrom(25),
  },
  {
    id: "ae-025",
    agent_id: "agent-003",
    period_date: daysAgoFrom(25).slice(0, 10),
    freelancer_id: 114,
    freelancer_name: "Крылов Василий Петрович",
    service_id: "svc-019",
    gross_amount_base: 3200,
    commission_pct: 12,
    commission_amount: 384,
    payout_id: null,
    status: "PAID",
    created_at: daysAgoFrom(25),
  },
];
