import type { FreelanceApplication } from "@/lib/types";
import { MOCK_TODAY, daysAgoFrom, dateFromNow, dateAgo } from "./_today";

void MOCK_TODAY; // imported for documentation / reference

/**
 * @endpoint GET /api/freelance/applications
 * 14 applications covering all ApplicationStatus variants and both sources.
 * Created by / decided by references:
 *   - store directors: id 5 (SPAR-TOM-001), id 7 (SPAR-NSK-001), id 9 (SPAR-KEM-001), id 10 (LAMA-Г-1)
 *   - supervisor: id 4 (Романов И.А.)
 *   - regional: id 3 (Соколова А.В.) acting as regional
 */
export const MOCK_FREELANCE_APPLICATIONS: FreelanceApplication[] = [
  // ── 3 PENDING INTERNAL ───────────────────────────────────────────
  {
    id: "app-001",
    source: "INTERNAL",
    status: "PENDING",
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    planned_date: dateFromNow(5),
    requested_hours: 8,
    work_type_id: 4,
    work_type_name: "Выкладка",
    comment: "Усиление выкладки на промо перед майскими праздниками",
    comment_en: "Reinforcing merchandising for promo before May holidays",
    created_by: 5,
    created_by_name: "Иванов А. С.",
    created_by_role: "STORE_DIRECTOR",
    created_at: daysAgoFrom(1),
    urgent: false,
    retroactive: false,
  },
  {
    id: "app-002",
    source: "INTERNAL",
    status: "PENDING",
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    planned_date: dateFromNow(3),
    requested_hours: 12,
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    comment: "Инвентаризация после завершения ремонта склада",
    comment_en: "Inventory check after warehouse renovation is completed",
    created_by: 10,
    created_by_name: "Смирнова О. И.",
    created_by_role: "STORE_DIRECTOR",
    created_at: daysAgoFrom(2),
    urgent: false,
    retroactive: false,
  },
  {
    /** urgent=true: создана SUPERVISOR у которого есть право на срочные */
    id: "app-003",
    source: "INTERNAL",
    status: "PENDING",
    store_id: 4,
    store_name: "СПАР Новосибирск, ул. Ленина 55",
    planned_date: dateFromNow(1),
    requested_hours: 6,
    work_type_id: 2,
    work_type_name: "Касса",
    comment: "Срочная замена заболевшего кассира",
    comment_en: "Urgent replacement for a sick cashier",
    created_by: 4,
    created_by_name: "Романов И. А.",
    created_by_role: "SUPERVISOR",
    created_at: daysAgoFrom(0),
    urgent: true,
    retroactive: false,
  },

  // ── 2 APPROVED_FULL EXTERNAL (без assignments, требуют назначения) ──
  {
    /** Синхронизация прислала статус сразу APPROVED_FULL, исполнители ещё не назначены */
    id: "app-004",
    source: "EXTERNAL",
    status: "APPROVED_FULL",
    store_id: 6,
    store_name: "СПАР Кемерово, пр. Советский 50",
    planned_date: dateFromNow(2),
    requested_hours: 10,
    approved_hours: 10,
    work_type_id: 4,
    work_type_name: "Выкладка",
    external_ref: "HR-2026-04-30-0042",
    created_by: 9,
    created_by_name: "Никитин Б. С.",
    created_by_role: "STORE_DIRECTOR",
    created_at: daysAgoFrom(1),
    urgent: false,
    retroactive: false,
  },
  {
    id: "app-005",
    source: "EXTERNAL",
    status: "APPROVED_FULL",
    store_id: 6,
    store_name: "СПАР Кемерово, пр. Советский 50",
    planned_date: dateFromNow(2),
    requested_hours: 8,
    approved_hours: 8,
    work_type_id: 13,
    work_type_name: "Складские работы",
    external_ref: "HR-2026-04-30-0043",
    created_by: 9,
    created_by_name: "Никитин Б. С.",
    created_by_role: "STORE_DIRECTOR",
    created_at: daysAgoFrom(1),
    urgent: false,
    retroactive: false,
  },

  // ── 2 APPROVED_FULL INTERNAL ─────────────────────────────────────
  {
    id: "app-006",
    source: "INTERNAL",
    status: "APPROVED_FULL",
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    planned_date: dateAgo(5),
    requested_hours: 8,
    approved_hours: 8,
    work_type_id: 4,
    work_type_name: "Выкладка",
    comment: "Плановая выкладка промо-зоны",
    comment_en: "Planned merchandising of the promo zone",
    created_by: 5,
    created_by_name: "Иванов А. С.",
    created_by_role: "STORE_DIRECTOR",
    created_at: daysAgoFrom(8),
    decided_by: 4,
    decided_by_name: "Романов И. А.",
    decided_at: daysAgoFrom(7),
    decision_comment: "Одобрено, бюджет в норме",
    decision_comment_en: "Approved, budget is within limits",
    urgent: false,
    retroactive: false,
  },
  {
    id: "app-007",
    source: "INTERNAL",
    status: "APPROVED_FULL",
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    planned_date: dateAgo(6),
    requested_hours: 6,
    approved_hours: 6,
    work_type_id: 2,
    work_type_name: "Касса",
    created_by: 10,
    created_by_name: "Смирнова О. И.",
    created_by_role: "STORE_DIRECTOR",
    created_at: daysAgoFrom(9),
    decided_by: 3,
    decided_by_name: "Соколова А. В.",
    decided_at: daysAgoFrom(8),
    decision_comment: "Согласовано",
    decision_comment_en: "Approved",
    urgent: false,
    retroactive: false,
  },

  // ── 2 APPROVED_PARTIAL INTERNAL ──────────────────────────────────
  {
    id: "app-008",
    source: "INTERNAL",
    status: "APPROVED_PARTIAL",
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    planned_date: dateFromNow(4),
    requested_hours: 12,
    approved_hours: 8,
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    comment: "Полная инвентаризация склада",
    comment_en: "Full warehouse inventory check",
    created_by: 5,
    created_by_name: "Иванов А. С.",
    created_by_role: "STORE_DIRECTOR",
    created_at: daysAgoFrom(2),
    decided_by: 4,
    decided_by_name: "Романов И. А.",
    decided_at: daysAgoFrom(1),
    decision_comment: "Бюджет недели поджимает, плюс 4 часа взять штатными",
    decision_comment_en: "Weekly budget is tight, cover the extra 4 hours with in-house staff",
    urgent: false,
    retroactive: false,
  },
  {
    id: "app-009",
    source: "INTERNAL",
    status: "APPROVED_PARTIAL",
    store_id: 5,
    store_name: "СПАР Новосибирск, Красный пр. 200",
    planned_date: dateFromNow(6),
    requested_hours: 8,
    approved_hours: 4,
    work_type_id: 13,
    work_type_name: "Складские работы",
    comment: "Разгрузка поставки",
    comment_en: "Unloading the delivery",
    created_by: 8,
    created_by_name: "Васильев Д. О.",
    created_by_role: "STORE_DIRECTOR",
    created_at: daysAgoFrom(3),
    decided_by: 4,
    decided_by_name: "Романов И. А.",
    decided_at: daysAgoFrom(2),
    decision_comment: "Часть закроем своими, чтобы не выходить за плановый расход",
    decision_comment_en: "We will cover part with in-house staff to stay within planned spend",
    urgent: false,
    retroactive: false,
  },

  // ── 1 REJECTED INTERNAL ──────────────────────────────────────────
  {
    id: "app-010",
    source: "INTERNAL",
    status: "REJECTED",
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    planned_date: dateAgo(3),
    requested_hours: 16,
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    comment: "Полная ревизия перед отчётным периодом",
    comment_en: "Full audit before the reporting period",
    created_by: 5,
    created_by_name: "Иванов А. С.",
    created_by_role: "STORE_DIRECTOR",
    created_at: daysAgoFrom(10),
    decided_by: 4,
    decided_by_name: "Романов И. А.",
    decided_at: daysAgoFrom(7),
    decision_comment: "Перерасход бюджета на месяц 18%, отказ",
    decision_comment_en: "Monthly budget overspend 18%, rejected",
    urgent: false,
    retroactive: false,
  },

  // ── 1 REPLACED_WITH_BONUS INTERNAL ──────────────────────────────
  {
    /**
     * Полный внештат стоил бы 12000₽, бонус 6000₽, экономия 6000₽.
     * replaced_with_bonus_budget_id → budget-001 из future-placeholders.ts.
     */
    id: "app-011",
    source: "INTERNAL",
    status: "REPLACED_WITH_BONUS",
    store_id: 200,
    store_name: "Г-1 Котовского 19/3 (ГМ)",
    planned_date: dateAgo(2),
    requested_hours: 10,
    work_type_id: 4,
    work_type_name: "Выкладка",
    comment: "Доп. выкладка перед праздниками",
    comment_en: "Additional merchandising before the holidays",
    created_by: 10,
    created_by_name: "Смирнова О. И.",
    created_by_role: "STORE_DIRECTOR",
    created_at: daysAgoFrom(5),
    decided_by: 4,
    decided_by_name: "Романов И. А.",
    decided_at: daysAgoFrom(4),
    decision_comment: "Магазин укомплектован, заменено бонусным пулом",
    decision_comment_en: "Store is fully staffed, replaced with the bonus pool",
    replaced_with_bonus_budget_id: "budget-002",
    urgent: false,
    retroactive: false,
  },

  // ── 1 MIXED INTERNAL ─────────────────────────────────────────────
  {
    id: "app-012",
    source: "INTERNAL",
    status: "MIXED",
    store_id: 270,
    store_name: "С-6 Мичурина 37 (П)",
    planned_date: dateFromNow(7),
    requested_hours: 8,
    approved_hours: 8,
    work_type_id: 13,
    work_type_name: "Складские работы",
    comment: "Поставка перед выходными, нужно усиление",
    comment_en: "Delivery before the weekend, additional staff needed",
    created_by: 10,
    created_by_name: "Смирнова О. И.",
    created_by_role: "STORE_DIRECTOR",
    created_at: daysAgoFrom(2),
    decided_by: 4,
    decided_by_name: "Романов И. А.",
    decided_at: daysAgoFrom(1),
    decision_comment: "Половина внештатом, половина бонусом для роста мотивации",
    decision_comment_en: "Half via freelance, half via bonus pool to boost motivation",
    mixed_freelance_hours: 4,
    mixed_bonus_hours: 4,
    replaced_with_bonus_budget_id: "budget-003",
    urgent: false,
    retroactive: false,
  },

  // ── 1 CANCELLED ──────────────────────────────────────────────────
  {
    id: "app-013",
    source: "INTERNAL",
    status: "CANCELLED",
    store_id: 2,
    store_name: "СПАР Томск, ул. Красноармейская 99",
    planned_date: dateAgo(1),
    requested_hours: 4,
    work_type_id: 12,
    work_type_name: "Уборка",
    comment: "Генеральная уборка после акции",
    comment_en: "General cleaning after the promotion",
    created_by: 6,
    created_by_name: "Петрова Е. В.",
    created_by_role: "STORE_DIRECTOR",
    created_at: daysAgoFrom(4),
    urgent: false,
    retroactive: false,
  },

  // ── 1 retroactive=true SUPERVISOR INTERNAL ────────────────────────
  {
    /**
     * Создана задним числом, сразу APPROVED_FULL.
     * decided_at === created_at — специфика retroactive-заявок.
     */
    id: "app-014",
    source: "INTERNAL",
    status: "APPROVED_FULL",
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    planned_date: dateAgo(3),
    requested_hours: 8,
    approved_hours: 8,
    work_type_id: 4,
    work_type_name: "Выкладка",
    comment: "Задним числом: внештат по факту отработан 28 апреля",
    comment_en: "Retroactive: freelance shift was actually worked on April 28",
    created_by: 4,
    created_by_name: "Романов И. А.",
    created_by_role: "SUPERVISOR",
    created_at: daysAgoFrom(1),
    decided_by: 4,
    decided_by_name: "Романов И. А.",
    decided_at: daysAgoFrom(1),
    decision_comment: "Retroactive: подтверждаю факт выхода",
    decision_comment_en: "Retroactive: confirming the worker showed up",
    urgent: false,
    retroactive: true,
  },
];
