import type { Notification } from "@/lib/types";

/**
 * @endpoint GET /api/notifications
 * 18 notifications — mix of TASK_REVIEW / TASK_REJECTED / TASK_STATE_CHANGED / GENERIC.
 * Последние 7 дней. Mix is_read true/false.
 *
 * Bilingual demo: каждая нотификация имеет `title_en` + `body_en`.
 * Реальные ФИО / store names / task names — RU only (LAMA-данные).
 */

const now = new Date("2026-05-01T10:00:00+07:00");
const hoursAgo = (h: number) =>
  new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_NOTIFICATIONS: Notification[] = [
  // ── TASK_REVIEW (6) ─────────────────────────────────────────────
  {
    id: "notif-001",
    user_id: 4, // Романов (SUPERVISOR)
    category: "TASK_REVIEW",
    title: "Задача завершена и ждёт проверки",
    title_en: "Task completed and awaiting review",
    body: "Козлова Дарья завершила «Выкладка молочной полки в холодильнике 3» и отправила на проверку.",
    body_en: "Daria Kozlova completed «Dairy shelf merchandising in fridge 3» and submitted it for review.",
    data: { task_id: "task-006", store_id: 1, assignee_id: 15 },
    link: "/tasks/task-006",
    is_read: false,
    is_archived: false,
    created_at: hoursAgo(1),
  },
  {
    id: "notif-002",
    user_id: 4,
    category: "TASK_REVIEW",
    title: "Задача завершена и ждёт проверки",
    title_en: "Task completed and awaiting review",
    body: "Новиков Максим завершил «Выкладка пива по планограмме» и отправил на проверку.",
    body_en: "Maxim Novikov completed «Beer planogram merchandising» and submitted it for review.",
    data: { task_id: "task-007", store_id: 1, assignee_id: 16 },
    link: "/tasks/task-007",
    is_read: false,
    is_archived: false,
    created_at: hoursAgo(2),
  },
  {
    id: "notif-003",
    user_id: 5, // Иванов (STORE_DIRECTOR)
    category: "TASK_REVIEW",
    title: "Задача завершена и ждёт проверки",
    title_en: "Task completed and awaiting review",
    body: "Степанов Андрей завершил «Переоценка кондитерки по выгрузке от 27 апр» и отправил на проверку.",
    body_en: "Andrey Stepanov completed «Confectionery repricing from 27 Apr feed» and submitted it for review.",
    data: { task_id: "task-008", store_id: 1, assignee_id: 19 },
    link: "/tasks/task-008",
    is_read: true,
    is_archived: false,
    created_at: hoursAgo(5),
  },
  {
    id: "notif-004",
    user_id: 4,
    category: "TASK_REVIEW",
    title: "Задача завершена и ждёт проверки",
    title_en: "Task completed and awaiting review",
    body: "Кириллова Светлана завершила «Инвентаризация заморозки» — приложена фотография акта.",
    body_en: "Svetlana Kirillova completed «Frozen goods inventory» — a photo of the report is attached.",
    data: { task_id: "task-012", store_id: 4, assignee_id: 21, has_photo: true },
    link: "/tasks/task-012",
    is_read: false,
    is_archived: false,
    created_at: hoursAgo(3),
  },
  {
    id: "notif-005",
    user_id: 12, // Тарасова (SUPERVISOR Food City)
    category: "TASK_REVIEW",
    title: "Задача завершена и ждёт проверки",
    title_en: "Task completed and awaiting review",
    body: "Соловьева Ирина завершила «Подготовка зоны выпечки» и отправила на проверку.",
    body_en: "Irina Solovyeva completed «Bakery zone preparation» and submitted it for review.",
    data: { task_id: "task-011", store_id: 7, assignee_id: 25 },
    link: "/tasks/task-011",
    is_read: true,
    is_archived: false,
    created_at: daysAgo(1),
  },
  {
    id: "notif-006",
    user_id: 4,
    category: "TASK_REVIEW",
    title: "Задача завершена и ждёт проверки",
    title_en: "Task completed and awaiting review",
    body: "Волкова Марина завершила «Проверка сроков годности молочки» — требуется проверка фото.",
    body_en: "Marina Volkova completed «Dairy expiration date check» — photo verification required.",
    data: { task_id: "task-005", store_id: 4, assignee_id: 23, has_photo: true },
    link: "/tasks/task-005",
    is_read: false,
    is_archived: false,
    created_at: daysAgo(2),
  },

  // ── TASK_REJECTED (4) ───────────────────────────────────────────
  {
    id: "notif-007",
    user_id: 17, // Медведева (WORKER)
    category: "TASK_REJECTED",
    title: "Задача отклонена — требуется повторное выполнение",
    title_en: "Task rejected — rework required",
    body: "Инвентаризация бакалеи отклонена: «Отчёт неполный — не хватает скан-листа участка 5. Пересчитать и приложить фото.»",
    body_en: "Grocery inventory rejected: «Report incomplete — scan sheet for section 5 is missing. Recount and attach a photo.»",
    data: { task_id: "task-016", reviewer_id: 4, reviewer_name: "Романов И. А." },
    link: "/tasks/task-016",
    is_read: false,
    is_archived: false,
    created_at: hoursAgo(4),
  },
  {
    id: "notif-008",
    user_id: 19, // Захарова (WORKER)
    category: "TASK_REJECTED",
    title: "Задача отклонена — требуется повторное выполнение",
    title_en: "Task rejected — rework required",
    body: "Замена ценников на акционных стеллажах отклонена: «Ценники на стеллаже 12 не обновлены. Повторить.»",
    body_en: "Price tag replacement on promo shelves rejected: «Tags on shelf 12 not updated. Redo.»",
    data: { task_id: "task-020", reviewer_id: 5, reviewer_name: "Иванов А. С." },
    link: "/tasks/task-020",
    is_read: true,
    is_archived: false,
    created_at: daysAgo(1),
  },
  {
    id: "notif-009",
    user_id: 24, // Лебедев (WORKER)
    category: "TASK_REJECTED",
    title: "Задача отклонена — требуется повторное выполнение",
    title_en: "Task rejected — rework required",
    body: "Приёмка алкоголя от Сибирского винного дома отклонена: «Акт расхождения по 3 позициям не приложен. Уточнить с поставщиком.»",
    body_en: "Alcohol receiving from Siberian Wine House rejected: «Discrepancy report for 3 SKUs not attached. Clarify with supplier.»",
    data: { task_id: "task-014", reviewer_id: 4, reviewer_name: "Романов И. А." },
    link: "/tasks/task-014",
    is_read: true,
    is_archived: false,
    created_at: daysAgo(3),
  },
  {
    id: "notif-010",
    user_id: 22, // Степанов (WORKER)
    category: "TASK_REJECTED",
    title: "Задача отклонена — требуется повторное выполнение",
    title_en: "Task rejected — rework required",
    body: "Замена ценников после переоценки отклонена: «Обновлено 18 из 23 SKU. Проверить стеллажи 4, 7.»",
    body_en: "Price tag replacement after repricing rejected: «18 of 23 SKUs updated. Check shelves 4, 7.»",
    data: { task_id: "task-023", reviewer_id: 7, reviewer_name: "Сидоров К. М." },
    link: "/tasks/task-023",
    is_read: false,
    is_archived: false,
    created_at: daysAgo(2),
  },

  // ── TASK_STATE_CHANGED (5) ──────────────────────────────────────
  {
    id: "notif-011",
    user_id: 5,
    category: "TASK_STATE_CHANGED",
    title: "Задача автоматически принята",
    title_en: "Task automatically approved",
    body: "«Открытие зоны самообслуживания» (политика авто-приёмки) — принята автоматически. Исполнитель: Попов Владимир.",
    body_en: "«Self-checkout zone opening» (auto-acceptance policy) — accepted automatically. Worker: Vladimir Popov.",
    data: { task_id: "task-010", auto: true, assignee_id: 20 },
    link: "/tasks/task-010",
    is_read: true,
    is_archived: false,
    created_at: hoursAgo(6),
  },
  {
    id: "notif-012",
    user_id: 5,
    category: "TASK_STATE_CHANGED",
    title: "Задача автоматически принята",
    title_en: "Task automatically approved",
    body: "«Уборка прикассовой зоны» (политика авто-приёмки) — принята автоматически. Исполнитель: Медведева Татьяна.",
    body_en: "«Checkout zone cleaning» (auto-acceptance policy) — accepted automatically. Worker: Tatyana Medvedeva.",
    data: { task_id: "task-013", auto: true, assignee_id: 17 },
    link: "/tasks/task-013",
    is_read: true,
    is_archived: false,
    created_at: daysAgo(1),
  },
  {
    id: "notif-013",
    user_id: 4,
    category: "TASK_STATE_CHANGED",
    title: "Задача переведена в статус «В работе»",
    title_en: "Task moved to In Progress",
    body: "Федоров Алексей приступил к «Приёмка молочки от ООО «Деревенское молочко»».",
    body_en: "Alexey Fedorov started «Receiving dairy from Derevenskoe Moloko LLC».",
    data: { task_id: "task-004", new_state: "IN_PROGRESS", assignee_id: 18 },
    link: "/tasks/task-004",
    is_read: false,
    is_archived: false,
    created_at: hoursAgo(8),
  },
  {
    id: "notif-014",
    user_id: 12,
    category: "TASK_STATE_CHANGED",
    title: "Задача автоматически принята",
    title_en: "Task automatically approved",
    body: "«Заказ расходников» выполнен и автоматически принят системой.",
    body_en: "«Consumables order» completed and automatically accepted by the system.",
    data: { task_id: "task-003", auto: true, assignee_id: 15 },
    link: "/tasks/task-003",
    is_read: true,
    is_archived: false,
    created_at: daysAgo(4),
  },
  {
    id: "notif-015",
    user_id: 4,
    category: "TASK_STATE_CHANGED",
    title: "Задача приостановлена",
    title_en: "Task paused",
    body: "Кириллова Светлана поставила на паузу «Заказ на расходники РЦ Новосибирск»: ожидает подтверждения бюджета.",
    body_en: "Svetlana Kirillova paused «Consumables order — DC Novosibirsk»: awaiting budget approval.",
    data: { task_id: "task-015", new_state: "PAUSED", assignee_id: 21 },
    link: "/tasks/task-015",
    is_read: false,
    is_archived: false,
    created_at: daysAgo(5),
  },

  // ── FREELANCE (7) ───────────────────────────────────────────────
  {
    id: "notif-019",
    user_id: 4, // Романов (SUPERVISOR)
    category: "FREELANCE_APPLICATION_PENDING",
    title: "Заявка на внештатника ждёт согласования",
    title_en: "Freelance application awaiting approval",
    body: "Заявка №A-2041 на 3 исполнителей (Магнит Ленина 12) направлена на согласование супервайзеру.",
    body_en: "Application #A-2041 for 3 freelancers (Магнит Ленина 12) sent to the supervisor for approval.",
    data: { application_id: "app-2041", store_id: 1 },
    link: "/freelance/applications/app-2041",
    is_read: false,
    is_archived: false,
    created_at: hoursAgo(2),
  },
  {
    id: "notif-020",
    user_id: 6, // Региональный
    category: "FREELANCE_BUDGET_OVERLIMIT",
    title: "Перерасход бюджета внештата",
    title_en: "Freelance budget overrun",
    body: "Магазин «Ленина 12» превысил месячный лимит на 18 000 ₽. Текущие расходы: 148 000 / 130 000 ₽.",
    body_en: "Store «Ленина 12» has exceeded its monthly limit by ₽18,000. Current spend: ₽148,000 / ₽130,000.",
    data: { store_id: 1, overlimit_amount: 18000 },
    link: "/freelance?store_id=1",
    is_read: false,
    is_archived: false,
    created_at: hoursAgo(5),
  },
  {
    id: "notif-021",
    user_id: 5, // Иванов (STORE_DIRECTOR)
    category: "FREELANCE_NO_TASKS",
    title: "Внештатный исполнитель без задач",
    title_en: "Freelancer with no assigned tasks",
    body: "Ершов Павел вышел по заявке №A-2039 сегодня, но задач ему не назначено. Проверьте расписание.",
    body_en: "Pavel Ershov showed up under application #A-2039 today, but no tasks are assigned to him. Check the schedule.",
    data: { application_id: "app-2039", freelancer_id: 30, store_id: 1 },
    link: "/freelance/applications/app-2039",
    is_read: false,
    is_archived: false,
    created_at: hoursAgo(1),
  },
  {
    id: "notif-022",
    user_id: 5,
    category: "FREELANCE_SERVICE_NOT_CONFIRMED",
    title: "Услуга ожидает вашего подтверждения",
    title_en: "Service awaiting your confirmation",
    body: "Услуга Ершова Павла за 30 апреля не подтверждена. Подтвердите до 23:59 сегодня, иначе уйдёт в DISPUTED.",
    body_en: "Pavel Ershov's service for April 30 has not been confirmed. Confirm by 23:59 today, otherwise it will move to DISPUTED.",
    data: { service_id: "svc-509", freelancer_id: 30 },
    link: "/freelance/services?service_id=svc-509",
    is_read: false,
    is_archived: false,
    created_at: hoursAgo(3),
  },
  {
    id: "notif-023",
    user_id: 4,
    category: "FREELANCE_NO_SHOW",
    title: "Невыход внештатного исполнителя",
    title_en: "Freelancer no-show",
    body: "Климова Анна (заявка №A-2038) не вышла на смену 1 мая. Статус изменён на NO_SHOW. Назначьте замену или закройте заявку.",
    body_en: "Anna Klimova (application #A-2038) did not show up for her shift on May 1. Status changed to NO_SHOW. Assign a replacement or close the application.",
    data: { service_id: "svc-507", freelancer_id: 31, store_id: 1 },
    link: "/freelance/services?status=NO_SHOW",
    is_read: false,
    is_archived: false,
    created_at: daysAgo(1),
  },
  {
    id: "notif-024",
    user_id: 3, // Соколова (NETWORK_OPS)
    category: "FREELANCE_EXTERNAL_SYNC",
    title: "Синхронизация заявок из HR-системы завершена",
    title_en: "HR system applications sync completed",
    body: "Получено 12 новых заявок из LAMA-HR (SPAR). Проверьте входящие заявки и подтвердите корректность данных.",
    body_en: "12 new applications received from LAMA-HR (SPAR). Review incoming applications and confirm the data is correct.",
    data: { imported_count: 12, source: "LAMA_HR" },
    link: "/integrations",
    is_read: true,
    is_archived: false,
    created_at: daysAgo(1),
  },
  {
    id: "notif-025",
    user_id: 6, // Региональный
    category: "FREELANCE_PAYOUT_DONE",
    title: "Выплата исполнителям проведена",
    title_en: "Freelancer payout completed",
    body: "Реестр выплат №P-118 на 34 700 ₽ (7 исполнителей) успешно обработан через Номинальный счёт.",
    body_en: "Payout batch #P-118 for ₽34,700 (7 freelancers) has been successfully processed via the Nominal Account.",
    data: { payout_id: "payout-118", amount: 34700, payees_count: 7 },
    link: "/freelance/payouts?payout_id=payout-118",
    is_read: true,
    is_archived: false,
    created_at: daysAgo(2),
  },

  // ── GENERIC (3) ─────────────────────────────────────────────────
  {
    id: "notif-016",
    user_id: 4,
    category: "GENERIC",
    title: "Синхронизация с планировщиком завершена",
    title_en: "Scheduler sync completed",
    body: "LAMA-коннектор успешно выгрузил расписание на неделю 5–11 мая. Импортировано 47 смен по 8 магазинам.",
    body_en: "LAMA connector successfully fetched the schedule for the week of May 5–11. Imported 47 shifts across 8 stores.",
    data: { connector_type: "PLANNER", shifts_imported: 47, stores_count: 8 },
    link: "/settings/integrations",
    is_read: true,
    is_archived: false,
    created_at: daysAgo(1),
  },
  {
    id: "notif-017",
    user_id: 3, // Соколова (NETWORK_OPS)
    category: "GENERIC",
    title: "Обновление системы WFM Admin 2.4.1",
    title_en: "WFM Admin 2.4.1 update",
    body: "Доступно обновление: улучшена скорость загрузки отчётов, исправлены мелкие баги в модуле задач.",
    body_en: "An update is available: faster report loading, minor bug fixes in the tasks module.",
    data: { version: "2.4.1", changelog_url: "/changelog" },
    is_read: false,
    is_archived: false,
    created_at: daysAgo(3),
  },
  {
    id: "notif-018",
    user_id: 3,
    category: "GENERIC",
    title: "Плановое техническое обслуживание",
    title_en: "Scheduled maintenance",
    body: "3 мая 2026 с 02:00 до 04:00 (МСК) запланированы технические работы. Сервис будет недоступен.",
    body_en: "Scheduled maintenance on May 3, 2026 from 02:00 to 04:00 (MSK). The service will be unavailable.",
    data: { maintenance_start: "2026-05-03T02:00:00Z", maintenance_end: "2026-05-03T04:00:00Z" },
    is_read: true,
    is_archived: false,
    created_at: daysAgo(6),
  },
];
