import type { ProductCategory } from "@/lib/types";

/**
 * @endpoint GET /api/product-categories
 * Full 53-category FMCG taxonomy (as per LAMA standards).
 * Used for tagging tasks — not to be confused with WorkType.group.
 */
export const MOCK_PRODUCT_CATEGORIES: ProductCategory[] = [
  { id: 1,  code: "MILK",           name: "Молочка" },
  { id: 2,  code: "BREAD",          name: "Хлебобулочка" },
  { id: 3,  code: "GROCERY",        name: "Бакалея" },
  { id: 4,  code: "SPIRITS",        name: "Алкоголь крепкий" },
  { id: 5,  code: "WINE",           name: "Вино" },
  { id: 6,  code: "BEER",           name: "Пиво" },
  { id: 7,  code: "CONFECTIONERY",  name: "Кондитерка" },
  { id: 8,  code: "CHOCOLATE",      name: "Шоколад" },
  { id: 9,  code: "FRUIT_VEG",      name: "Овощи и фрукты" },
  { id: 10, code: "GREENS",         name: "Зелень" },
  { id: 11, code: "FROZEN",         name: "Заморозка" },
  { id: 12, code: "MEAT_FRESH",     name: "Мясо охлаждённое" },
  { id: 13, code: "MEAT_FROZEN",    name: "Мясо замороженное" },
  { id: 14, code: "FISH_FRESH",     name: "Рыба охлаждённая" },
  { id: 15, code: "FISH_FROZEN",    name: "Рыба замороженная" },
  { id: 16, code: "POULTRY",        name: "Птица" },
  { id: 17, code: "CHEESE",         name: "Сыры" },
  { id: 18, code: "SAUSAGE",        name: "Колбасы и деликатесы" },
  { id: 19, code: "SNACKS_SALTY",   name: "Снеки солёные" },
  { id: 20, code: "SNACKS_SWEET",   name: "Снеки сладкие" },
  { id: 21, code: "CHIPS",          name: "Чипсы" },
  { id: 22, code: "NUTS",           name: "Орехи и сухофрукты" },
  { id: 23, code: "SOFT_DRINKS",    name: "Безалкогольные напитки" },
  { id: 24, code: "JUICES",         name: "Соки и нектары" },
  { id: 25, code: "WATER",          name: "Воды" },
  { id: 26, code: "ENERGY",         name: "Энергетики" },
  { id: 27, code: "TEA",            name: "Чай" },
  { id: 28, code: "COFFEE",         name: "Кофе" },
  { id: 29, code: "READY_FOOD",     name: "Кулинария готовая" },
  { id: 30, code: "SEMI_FINISHED",  name: "Полуфабрикаты" },
  { id: 31, code: "BABY_FOOD",      name: "Детское питание" },
  { id: 32, code: "HEALTH_FOOD",    name: "Здоровое питание" },
  { id: 33, code: "SAUCES",         name: "Соусы и приправы" },
  { id: 34, code: "OILS",           name: "Масла и уксусы" },
  { id: 35, code: "GRAINS",         name: "Крупы" },
  { id: 36, code: "PASTA",          name: "Макаронные изделия" },
  { id: 37, code: "CANNED",         name: "Консервация" },
  { id: 38, code: "SEAFOOD",        name: "Икра и морепродукты" },
  { id: 39, code: "HOUSEHOLD_CHEM", name: "Бытовая химия" },
  { id: 40, code: "LAUNDRY",        name: "Стиральные порошки" },
  { id: 41, code: "DISHWASH",       name: "Средства для посуды" },
  { id: 42, code: "HYGIENE",        name: "Личная гигиена" },
  { id: 43, code: "COSMETICS",      name: "Косметика" },
  { id: 44, code: "PERFUME",        name: "Парфюмерия" },
  { id: 45, code: "DENTAL",         name: "Зубная паста и щётки" },
  { id: 46, code: "DIAPERS",        name: "Подгузники и салфетки" },
  { id: 47, code: "PET",            name: "Товары для животных" },
  { id: 48, code: "STATIONERY",     name: "Канцтовары" },
  { id: 49, code: "HOME_GOODS",     name: "Товары для дома" },
  { id: 50, code: "TEXTILE",        name: "Текстиль" },
  { id: 51, code: "SEASONAL",       name: "Сезонные товары" },
  { id: 52, code: "HOLIDAY",        name: "Товары к праздникам" },
  { id: 53, code: "NON_FOOD_OTHER", name: "Прочее non-food" },
];
