import type { Regulation } from "@/lib/types";

/**
 * @endpoint GET /api/regulations
 * 23 Regulation — diverse mix. 3 without tags (warning demo), 2 archived.
 * ai_usage_count_30d — how many times AI loaded this doc in context last 30 days.
 */

const d = (iso: string) => iso;

export const MOCK_REGULATIONS: Regulation[] = [
  // ── Tagged, active ─────────────────────────────────────────────

  {
    id: "reg-001",
    name: "Регламент выкладки молочной продукции",
    description: "Стандарт выкладки, фронтинга, ротации и контроля сроков годности в молочном отделе. Включает фото-примеры правильной и неправильной выкладки.",
    file_url: "/documents/regulation-001.pdf",
    file_type: "PDF",
    file_size_bytes: 2516582, // 2.4 МБ
    work_type_ids: [4, 11],
    zone_ids: [6],
    version: 3,
    is_archived: false,
    replaces_id: "reg-001-v2",
    uploaded_by: 14,
    uploaded_at: d("2026-04-01T09:00:00+07:00"),
    ai_usage_count_30d: 47,
  },
  {
    id: "reg-002",
    name: "Стандарт переоценки и стикеровки",
    description: "Процедура замены ценников при изменении цен из 1С: сроки, форматы стикеров, порядок утилизации старых ценников.",
    file_url: "/documents/regulation-002.pdf",
    file_type: "PDF",
    file_size_bytes: 1887437, // 1.8 МБ
    work_type_ids: [5, 10],
    zone_ids: [1],
    version: 2,
    is_archived: false,
    uploaded_by: 14,
    uploaded_at: d("2026-02-15T09:00:00+07:00"),
    ai_usage_count_30d: 32,
  },
  {
    id: "reg-003",
    name: "Инструкция по приёмке товара",
    description: "Пошаговая процедура приёмки: проверка документов, пересчёт, контроль температуры для скоропорта, оформление актов расхождений.",
    file_url: "/documents/regulation-003.docx",
    file_type: "WORD",
    file_size_bytes: 876544, // 856 КБ
    work_type_ids: [13],
    zone_ids: [2],
    version: 4,
    is_archived: false,
    uploaded_by: 14,
    uploaded_at: d("2026-03-01T09:00:00+07:00"),
    ai_usage_count_30d: 28,
  },
  {
    id: "reg-004",
    name: "Правила работы с просрочкой и списанием",
    description: "Регламент выявления, изъятия, оформления актов и утилизации просроченной продукции. Юридические требования и ответственность.",
    file_url: "/documents/regulation-004.pdf",
    file_type: "PDF",
    file_size_bytes: 3249152, // 3.1 МБ
    work_type_ids: [11],
    zone_ids: [1, 2, 6],
    version: 2,
    is_archived: false,
    uploaded_by: 3,
    uploaded_at: d("2026-01-10T09:00:00+07:00"),
    ai_usage_count_30d: 51,
  },
  {
    id: "reg-005",
    name: "Кассовая дисциплина и инкассация",
    description: "Порядок открытия/закрытия смены, Z-отчёт, работа с инкассацией, возвраты, обращение с наличными. Требования безопасности.",
    file_url: "/documents/regulation-005.pdf",
    file_type: "PDF",
    file_size_bytes: 4404019, // 4.2 МБ
    work_type_ids: [2],
    zone_ids: [3],
    version: 3,
    is_archived: false,
    uploaded_by: 14,
    uploaded_at: d("2026-01-20T09:00:00+07:00"),
    ai_usage_count_30d: 19,
  },
  {
    id: "reg-006",
    name: "Стандарт выкладки промо",
    description: "Правила размещения акционных товаров: зоны, дополнительные точки продаж, ценники промо-акций, контроль соответствия плану.",
    file_url: "/documents/regulation-006.pdf",
    file_type: "PDF",
    file_size_bytes: 1572864, // 1.5 МБ
    work_type_ids: [4, 9],
    zone_ids: [1],
    version: 1,
    is_archived: false,
    uploaded_by: 14,
    uploaded_at: d("2026-03-15T09:00:00+07:00"),
    ai_usage_count_30d: 24,
  },
  {
    id: "reg-007",
    name: "Инвентаризация: пошаговая инструкция",
    description: "Процедура плановой и внеплановой инвентаризации: подготовка, пересчёт, сверка с системой, оформление актов разногласий.",
    file_url: "/documents/regulation-007.docx",
    file_type: "WORD",
    file_size_bytes: 1048576, // 1.0 МБ
    work_type_ids: [6],
    zone_ids: [1, 2],
    version: 2,
    is_archived: false,
    uploaded_by: 14,
    uploaded_at: d("2026-02-01T09:00:00+07:00"),
    ai_usage_count_30d: 15,
  },
  {
    id: "reg-008",
    name: "Работа на самокассе — обучение",
    description: "Инструкция для операторов КСО: включение, помощь покупателям, типичные ошибки, сброс блокировок. Включает ссылку на обучающее видео.",
    file_url: "/documents/regulation-008.pdf",
    file_type: "PDF",
    file_size_bytes: 2097152,
    work_type_ids: [3],
    zone_ids: [4],
    version: 2,
    is_archived: false,
    uploaded_by: 14,
    uploaded_at: d("2026-01-05T09:00:00+07:00"),
    ai_usage_count_30d: 8,
  },
  {
    id: "reg-009",
    name: "Уборка торгового зала: чек-лист",
    description: "Стандарт уборки: зоны ответственности, периодичность, средства, отметки в журнале. Соответствие требованиям СанПиН.",
    file_url: "/documents/regulation-009.pdf",
    file_type: "PDF",
    file_size_bytes: 786432,
    work_type_ids: [12],
    zone_ids: [1, 3, 4, 5],
    version: 1,
    is_archived: false,
    uploaded_by: 14,
    uploaded_at: d("2025-12-01T09:00:00+07:00"),
    ai_usage_count_30d: 6,
  },
  {
    id: "reg-010",
    name: "Контроль скоропорта: ежедневный обход",
    description: "Регламент ежедневного обхода с проверкой сроков годности. Чек-лист по зонам, критерии изъятия, порядок уведомления.",
    file_url: "/documents/regulation-010.pdf",
    file_type: "PDF",
    file_size_bytes: 1258291,
    work_type_ids: [11],
    zone_ids: [6, 1],
    version: 2,
    is_archived: false,
    uploaded_by: 3,
    uploaded_at: d("2026-03-20T09:00:00+07:00"),
    ai_usage_count_30d: 61,
  },
  {
    id: "reg-011",
    name: "Стандарт работы с алкоголем и ЕГАИС",
    description: "Порядок приёмки, подтверждения в ЕГАИС, хранения и продажи алкогольной продукции. Требования лицензии.",
    file_url: "/documents/regulation-011.pdf",
    file_type: "PDF",
    file_size_bytes: 2359296,
    work_type_ids: [13, 11],
    zone_ids: [2, 1],
    version: 3,
    is_archived: false,
    uploaded_by: 14,
    uploaded_at: d("2026-02-10T09:00:00+07:00"),
    ai_usage_count_30d: 17,
  },
  {
    id: "reg-012",
    name: "Инструкция по работе с весовым товаром",
    description: "Правила взвешивания, маркировки, ценообразования и выкладки весовых продуктов. Настройка весов, калибровка.",
    file_url: "/documents/regulation-012.pdf",
    file_type: "PDF",
    file_size_bytes: 1048576,
    work_type_ids: [4, 5],
    zone_ids: [1],
    version: 1,
    is_archived: false,
    uploaded_by: 14,
    uploaded_at: d("2025-11-15T09:00:00+07:00"),
    ai_usage_count_30d: 9,
  },
  {
    id: "reg-013",
    name: "Правила складирования и товарного соседства",
    description: "Требования к хранению: температурные зоны, несовместимые группы товаров, маркировка паллет, FIFO-принцип.",
    file_url: "/documents/regulation-013.docx",
    file_type: "WORD",
    file_size_bytes: 917504,
    work_type_ids: [13],
    zone_ids: [2],
    version: 2,
    is_archived: false,
    uploaded_by: 14,
    uploaded_at: d("2026-01-25T09:00:00+07:00"),
    ai_usage_count_30d: 12,
  },
  {
    id: "reg-014",
    name: "Планограммы — порядок внедрения",
    description: "Как читать и внедрять планограмму: расстановка по схеме, отклонения, согласование с супервайзером.",
    file_url: "/documents/regulation-014.pdf",
    file_type: "PDF",
    file_size_bytes: 3145728,
    work_type_ids: [4, 9],
    zone_ids: [1],
    version: 1,
    is_archived: false,
    uploaded_by: 14,
    uploaded_at: d("2026-03-05T09:00:00+07:00"),
    ai_usage_count_30d: 21,
  },
  {
    id: "reg-015",
    name: "Работа с рекламациями и жалобами покупателей",
    description: "Порядок обработки жалоб: принятие, регистрация, эскалация, компенсация. Скрипты для типовых ситуаций.",
    file_url: "/documents/regulation-015.pdf",
    file_type: "PDF",
    file_size_bytes: 1310720,
    work_type_ids: [1],
    zone_ids: [3, 1],
    version: 2,
    is_archived: false,
    uploaded_by: 3,
    uploaded_at: d("2026-01-15T09:00:00+07:00"),
    ai_usage_count_30d: 4,
  },
  {
    id: "reg-016",
    name: "Пожарная безопасность и эвакуация",
    description: "Требования пожарной безопасности для торговых объектов: порядок эвакуации, расположение средств пожаротушения, действия персонала.",
    file_url: "/documents/regulation-016.pdf",
    file_type: "PDF",
    file_size_bytes: 2621440,
    work_type_ids: [1],
    zone_ids: [1, 2, 3, 4, 5],
    version: 1,
    is_archived: false,
    uploaded_by: 3,
    uploaded_at: d("2025-09-01T09:00:00+07:00"),
    ai_usage_count_30d: 2,
  },
  {
    id: "reg-017",
    name: "Охрана труда и техника безопасности",
    description: "Инструктаж по охране труда для работников торгового зала и склада. Обязательный документ для допуска к работе.",
    file_url: "/documents/regulation-017.pdf",
    file_type: "PDF",
    file_size_bytes: 1835008,
    work_type_ids: [13, 12],
    zone_ids: [1, 2],
    version: 2,
    is_archived: false,
    uploaded_by: 13,
    uploaded_at: d("2025-10-01T09:00:00+07:00"),
    ai_usage_count_30d: 3,
  },
  {
    id: "reg-018",
    name: "Мерчендайзинг fashion: стандарты Альфа",
    description: "Правила выкладки одежды в магазине Альфа: зонирование, фолдинг, развешивание, ценники. Специфика fashion-вертикали.",
    file_url: "/documents/regulation-018.pdf",
    file_type: "PDF",
    file_size_bytes: 4194304,
    work_type_ids: [4, 9],
    zone_ids: [1],
    version: 1,
    is_archived: false,
    uploaded_by: 11,
    uploaded_at: d("2026-04-10T09:00:00+07:00"),
    ai_usage_count_30d: 14,
  },
  {
    id: "reg-019",
    name: "Стандарт уценки и markdown (fashion)",
    description: "Правила стикеровки уценённых товаров, допустимые диапазоны скидок по категориям, маркетинг-канал после уценки.",
    file_url: "/documents/regulation-019.pdf",
    file_type: "PDF",
    file_size_bytes: 1048576,
    work_type_ids: [5],
    zone_ids: [1],
    version: 1,
    is_archived: false,
    uploaded_by: 11,
    uploaded_at: d("2026-04-12T09:00:00+07:00"),
    ai_usage_count_30d: 11,
  },
  {
    id: "reg-020",
    name: "Взаимодействие с промоутерами и мерчендайзерами поставщиков",
    description: "Порядок допуска, контроль, согласование действий внешних мерчендайзеров поставщиков в торговом зале.",
    file_url: "/documents/regulation-020.docx",
    file_type: "WORD",
    file_size_bytes: 720896,
    work_type_ids: [1, 4],
    zone_ids: [1],
    version: 1,
    is_archived: false,
    uploaded_by: 3,
    uploaded_at: d("2025-12-15T09:00:00+07:00"),
    ai_usage_count_30d: 5,
  },

  // ── Without tags — 3 records (warning demo in UI) ──────────────

  {
    id: "reg-021",
    name: "Приказ о введении новой формы одежды",
    description: "Внутренний приказ о требованиях к форменной одежде сотрудников с мая 2026.",
    file_url: "/documents/regulation-021.pdf",
    file_type: "PDF",
    file_size_bytes: 204800,
    work_type_ids: undefined,
    zone_ids: undefined,
    version: 1,
    is_archived: false,
    uploaded_by: 13,
    uploaded_at: d("2026-04-20T09:00:00+07:00"),
    ai_usage_count_30d: 0,
  },
  {
    id: "reg-022",
    name: "Памятка по корпоративной этике",
    description: "Общие правила поведения, коммуникации и дресс-кода в компании. Не привязана к конкретным типам работ.",
    file_url: "/documents/regulation-022.pdf",
    file_type: "PDF",
    file_size_bytes: 409600,
    work_type_ids: undefined,
    zone_ids: undefined,
    version: 1,
    is_archived: false,
    uploaded_by: 13,
    uploaded_at: d("2026-01-01T09:00:00+07:00"),
    ai_usage_count_30d: 0,
  },
  {
    id: "reg-023",
    name: "Техническое задание на POS-интеграцию",
    description: "Технический документ для IT-команды. Загружен ошибочно в раздел регламентов вместо документов.",
    file_url: "/documents/regulation-023.docx",
    file_type: "WORD",
    file_size_bytes: 1572864,
    work_type_ids: undefined,
    zone_ids: undefined,
    version: 1,
    is_archived: false,
    uploaded_by: 3,
    uploaded_at: d("2026-03-10T09:00:00+07:00"),
    ai_usage_count_30d: 0,
  },

  // ── Archived (2 — old versions replaced) ──────────────────────

  {
    id: "reg-001-v2",
    name: "Регламент выкладки молочной продукции (v2 — архив)",
    description: "Устаревшая версия. Заменена версией 3 от 01.04.2026.",
    file_url: "/documents/regulation-001-v2.pdf",
    file_type: "PDF",
    file_size_bytes: 2097152,
    work_type_ids: [4, 11],
    zone_ids: [6],
    version: 2,
    is_archived: true,
    replaces_id: null,
    uploaded_by: 14,
    uploaded_at: d("2025-10-01T09:00:00+07:00"),
    ai_usage_count_30d: 0,
  },
  {
    id: "reg-010-v1",
    name: "Контроль скоропорта: ежедневный обход (v1 — архив)",
    description: "Устаревшая версия. Заменена версией 2 от 20.03.2026.",
    file_url: "/documents/regulation-010-v1.pdf",
    file_type: "PDF",
    file_size_bytes: 942080,
    work_type_ids: [11],
    zone_ids: [6],
    version: 1,
    is_archived: true,
    replaces_id: null,
    uploaded_by: 3,
    uploaded_at: d("2025-08-15T09:00:00+07:00"),
    ai_usage_count_30d: 0,
  },
];
