import type { Store } from "@/lib/types";
import { REAL_LAMA_STORES } from "./_lama-real";

/**
 * @endpoint GET /api/stores
 * 18 objects:
 *  - 8 FMCG SPAR (Томск/Новосибирск/Кемерово/Северск)
 *  - 3 Abricos (Томск × 2, Кемерово) — бренд Lama
 *  - 2 Первоцвет (Томск) — бренд Lama
 *  - 3 Food City (Томск, 1 архив)
 *  - 1 Fashion Alfa (Левушка-кейс, AI-fashion демо)
 *  - 1 Workshop Техпроиздрав (production демо)
 *
 * manager_id / supervisor_id ссылаются на User.id из users.ts.
 * lama_synced_at — дата последней синхронизации с планировщиком.
 */

const now = new Date();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_STORES: Store[] = [
  // ── SPAR Томск ──────────────────────────────────────────────────────
  {
    id: 1,
    name: "СПАР Томск, пр. Ленина 80",
    external_code: "SPAR-TOM-001",
    address: "пр. Ленина, 80",
    city: "Томск",
    store_type: "Супермаркет",
    object_type: "STORE",
    object_format: "SUPERMARKET",
    organization_id: "org-lama",
    legal_entity_id: 1,
    region: "Томская обл.",
    manager_id: 5,   // Иванов А. С. — STORE_DIRECTOR
    supervisor_id: 3, // Романов И. А. — SUPERVISOR
    lama_synced_at: daysAgo(0),
    active: true,
    archived: false,
    geo: { lat: 56.4846, lng: 84.9576 },
  },
  {
    id: 2,
    name: "СПАР Томск, ул. Красноармейская 99",
    external_code: "SPAR-TOM-002",
    address: "ул. Красноармейская, 99",
    city: "Томск",
    store_type: "Магазин у дома",
    object_type: "STORE",
    object_format: "CONVENIENCE",
    organization_id: "org-lama",
    legal_entity_id: 1,
    region: "Томская обл.",
    manager_id: 6,   // Петрова Е. В.
    supervisor_id: 3,
    lama_synced_at: daysAgo(1),
    active: true,
    archived: false,
    geo: { lat: 56.4752, lng: 84.9482 },
  },
  {
    /** Empty state demo: нет директора магазина */
    id: 3,
    name: "СПАР Томск, пр. Фрунзе 92а",
    external_code: "SPAR-TOM-003",
    address: "пр. Фрунзе, 92а",
    city: "Томск",
    store_type: "Супермаркет",
    object_type: "STORE",
    object_format: "SUPERMARKET",
    organization_id: "org-lama",
    legal_entity_id: 1,
    region: "Томская обл.",
    supervisor_id: 3,
    lama_synced_at: daysAgo(0),
    active: true,
    archived: false,
    geo: { lat: 56.4694, lng: 84.9807 },
  },
  // ── SPAR Новосибирск ────────────────────────────────────────────────
  {
    id: 4,
    name: "СПАР Новосибирск, ул. Ленина 55",
    external_code: "SPAR-NSK-001",
    address: "ул. Ленина, 55",
    city: "Новосибирск",
    store_type: "Гипермаркет",
    object_type: "STORE",
    object_format: "HYPERMARKET",
    organization_id: "org-lama",
    legal_entity_id: 2,
    region: "Новосибирская обл.",
    manager_id: 7,   // Сидоров К. М.
    supervisor_id: 3,
    lama_synced_at: daysAgo(0),
    active: true,
    archived: false,
    geo: { lat: 54.9893, lng: 82.9201 },
  },
  {
    /** lama_synced_at 2 дня назад → overdue indicator в UI */
    id: 5,
    name: "СПАР Новосибирск, Красный пр. 200",
    external_code: "SPAR-NSK-002",
    address: "Красный проспект, 200",
    city: "Новосибирск",
    store_type: "Супермаркет",
    object_type: "STORE",
    object_format: "SUPERMARKET",
    organization_id: "org-lama",
    legal_entity_id: 2,
    region: "Новосибирская обл.",
    manager_id: 8,   // Васильев Д. О.
    supervisor_id: 3,
    lama_synced_at: daysAgo(2),
    active: true,
    archived: false,
    geo: { lat: 55.0302, lng: 82.9204 },
  },
  // ── SPAR Кемерово — нужен для EXTERNAL-заявок из freelance-mock ──
  {
    id: 6,
    name: "СПАР Кемерово, пр. Советский 50",
    external_code: "SPAR-KEM-001",
    address: "пр. Советский, 50",
    city: "Кемерово",
    store_type: "Супермаркет",
    object_type: "STORE",
    object_format: "SUPERMARKET",
    organization_id: "org-lama",
    legal_entity_id: 1,
    region: "Кемеровская обл.",
    manager_id: 9,   // Никитин Б. С.
    supervisor_id: 3,
    lama_synced_at: daysAgo(0),
    active: true,
    archived: false,
    geo: { lat: 55.3544, lng: 86.0740 },
  },
  // ── Food City Томск (архив — старые тестовые, бренд не партнёрский) ─
  // Не отображаются в дропдаунах (archived: true), но ссылочные демки
  // (KPI рейтинги, freelance services, AI-chat) продолжают резолвить
  // store_id 7..9 → имя магазина.
  {
    id: 7,
    name: "Food City Томск Global Market, пр. Ленина 217",
    external_code: "FC-TOM-001",
    address: "пр. Ленина, 217",
    city: "Томск",
    store_type: "Гипермаркет",
    object_type: "STORE",
    object_format: "HYPERMARKET",
    organization_id: "org-lama",
    legal_entity_id: 3,
    region: "Томская обл.",
    manager_id: 10,
    supervisor_id: 4,
    lama_synced_at: daysAgo(0),
    active: false,
    archived: true,
    archive_reason: "OTHER",
    geo: { lat: 56.4977, lng: 84.9945 },
  },
  {
    id: 8,
    name: "Food City Томск, ул. Учебная 39",
    external_code: "FC-TOM-002",
    address: "ул. Учебная, 39",
    city: "Томск",
    store_type: "Супермаркет",
    object_type: "STORE",
    object_format: "SUPERMARKET",
    organization_id: "org-lama",
    legal_entity_id: 3,
    region: "Томская обл.",
    supervisor_id: 4,
    lama_synced_at: daysAgo(1),
    active: false,
    archived: true,
    archive_reason: "OTHER",
    geo: { lat: 56.4613, lng: 84.9518 },
  },
  {
    /** Архивирован — закрыт. Демо archive_reason=CLOSED */
    id: 9,
    name: "Food City Томск, ул. Иркутский тракт 122",
    external_code: "FC-TOM-003",
    address: "ул. Иркутский тракт, 122",
    city: "Томск",
    store_type: "Магазин у дома",
    object_type: "STORE",
    object_format: "CONVENIENCE",
    organization_id: "org-lama",
    legal_entity_id: 3,
    region: "Томская обл.",
    supervisor_id: 4,
    active: false,
    archived: true,
    archive_reason: "CLOSED",
    geo: { lat: 56.4401, lng: 85.0011 },
  },
  // ── Fashion Alfa — обязательный для AI fashion-кейса ─────────────
  {
    /**
     * Обязателен для: демо AI-кейса (сарафан), маркетинг-канал, сценарий «малый бизнес».
     * 3000 SKU. Владелец/директор = Никитина А. Н. (NETWORK_OPS, id=11).
     */
    id: 10,
    name: "Магазин одежды Альфа, Томск, пр. Ленина 50",
    external_code: "ALFA-TOM-001",
    address: "пр. Ленина, 50",
    city: "Томск",
    store_type: "Магазин одежды",
    object_type: "STORE",
    object_format: "SMALL_SHOP",
    organization_id: "org-levas",
    legal_entity_id: 4,
    region: "Томская обл.",
    manager_id: 11,  // Никитина А. Н. — NETWORK_OPS (малый бизнес, без STORE_DIRECTOR)
    lama_synced_at: daysAgo(0),
    active: true,
    archived: false,
    geo: { lat: 56.4812, lng: 84.9563 },
  },
  // ── Workshop — демо production ───────────────────────────────────
  {
    /** Опциональный: work_type 21-25 видны только если в org есть WORKSHOP */
    id: 11,
    name: "Швейный цех №1, Томск, ул. Карташова 25",
    external_code: "WORKSHOP-TOM-001",
    address: "ул. Карташова, 25",
    city: "Томск",
    store_type: "Производственный цех",
    object_type: "WORKSHOP",
    object_format: "SEWING_WORKSHOP",
    organization_id: "org-levas",
    legal_entity_id: 4,
    region: "Томская обл.",
    manager_id: 11,
    active: true,
    archived: false,
    geo: { lat: 56.4723, lng: 84.9632 },
  },
  // ── СПАР Северск ────────────────────────────────────────────────
  {
    id: 12,
    name: "СПАР Северск, ул. Курчатова 5",
    external_code: "SPAR-SEV-001",
    address: "ул. Курчатова, 5",
    city: "Северск",
    store_type: "Супермаркет",
    object_type: "STORE",
    object_format: "SUPERMARKET",
    organization_id: "org-lama",
    legal_entity_id: 1,
    region: "Томская обл.",
    supervisor_id: 3,
    lama_synced_at: daysAgo(0),
    active: true,
    archived: false,
    geo: { lat: 56.5996, lng: 84.8819 },
  },
  {
    id: 13,
    name: "СПАР Северск, пр. Коммунистический 41",
    external_code: "SPAR-SEV-002",
    address: "пр. Коммунистический, 41",
    city: "Северск",
    store_type: "Магазин у дома",
    object_type: "STORE",
    object_format: "CONVENIENCE",
    organization_id: "org-lama",
    legal_entity_id: 1,
    region: "Томская обл.",
    supervisor_id: 3,
    lama_synced_at: daysAgo(1),
    active: true,
    archived: false,
    geo: { lat: 56.6024, lng: 84.8758 },
  },
  // ── Abricos (бренд Lama) ────────────────────────────────────────
  {
    id: 14,
    name: "Abricos Томск, пр. Кирова 51",
    external_code: "ABR-TOM-001",
    address: "пр. Кирова, 51",
    city: "Томск",
    store_type: "Супермаркет",
    object_type: "STORE",
    object_format: "SUPERMARKET",
    organization_id: "org-lama",
    legal_entity_id: 1,
    region: "Томская обл.",
    supervisor_id: 3,
    lama_synced_at: daysAgo(0),
    active: true,
    archived: false,
    geo: { lat: 56.4729, lng: 84.9512 },
  },
  {
    id: 15,
    name: "Abricos Томск, ул. Сибирская 81",
    external_code: "ABR-TOM-002",
    address: "ул. Сибирская, 81",
    city: "Томск",
    store_type: "Магазин у дома",
    object_type: "STORE",
    object_format: "CONVENIENCE",
    organization_id: "org-lama",
    legal_entity_id: 1,
    region: "Томская обл.",
    supervisor_id: 3,
    lama_synced_at: daysAgo(0),
    active: true,
    archived: false,
    geo: { lat: 56.4892, lng: 84.9743 },
  },
  {
    id: 16,
    name: "Abricos Кемерово, пр. Ленина 80А",
    external_code: "ABR-KEM-001",
    address: "пр. Ленина, 80А",
    city: "Кемерово",
    store_type: "Супермаркет",
    object_type: "STORE",
    object_format: "SUPERMARKET",
    organization_id: "org-lama",
    legal_entity_id: 1,
    region: "Кемеровская обл.",
    supervisor_id: 3,
    lama_synced_at: daysAgo(2),
    active: true,
    archived: false,
    geo: { lat: 55.3479, lng: 86.0826 },
  },
  // ── Первоцвет (бренд Lama в Томске) ─────────────────────────────
  {
    id: 17,
    name: "Первоцвет Томск, пр. Мира 76",
    external_code: "PRV-TOM-001",
    address: "пр. Мира, 76",
    city: "Томск",
    store_type: "Магазин у дома",
    object_type: "STORE",
    object_format: "CONVENIENCE",
    organization_id: "org-lama",
    legal_entity_id: 1,
    region: "Томская обл.",
    supervisor_id: 3,
    lama_synced_at: daysAgo(0),
    active: true,
    archived: false,
    geo: { lat: 56.5078, lng: 85.0142 },
  },
  {
    id: 18,
    name: "Первоцвет Томск, ул. Учебная 7А",
    external_code: "PRV-TOM-002",
    address: "ул. Учебная, 7А",
    city: "Томск",
    store_type: "Магазин у дома",
    object_type: "STORE",
    object_format: "CONVENIENCE",
    organization_id: "org-lama",
    legal_entity_id: 1,
    region: "Томская обл.",
    supervisor_id: 3,
    lama_synced_at: daysAgo(1),
    active: true,
    archived: false,
    geo: { lat: 56.4634, lng: 84.9491 },
  },

  // ═════════════════════════════════════════════════════════════════
  // ТехПродЗдрав — швейный цех в Томске. Источник Excel.
  // 1 объект type=WORKSHOP. 9 сотрудников из списка операций.
  // ═════════════════════════════════════════════════════════════════
  {
    id: 100,
    name: "ТехПродЗдрав, швейный цех",
    external_code: "TPZ-WORKSHOP-001",
    address: "пр. Кирова, 56",
    city: "Томск",
    store_type: "Швейный цех",
    object_type: "WORKSHOP",
    object_format: "SEWING_WORKSHOP",
    organization_id: "org-tehprod",
    legal_entity_id: 1,
    region: "Томская обл.",
    supervisor_id: 3,
    lama_synced_at: daysAgo(0),
    active: true,
    archived: false,
    geo: { lat: 56.4842, lng: 84.9711 },
  },

  // ─── ЛАМА реальный магазин (id 200) — fetched через GET
  // /api/employee/?shop_code=0120 — «С-12 Некрасова, 41 (ИР)», Томск.
  ...REAL_LAMA_STORES,
];
