import type { Task } from "@/lib/types";

/**
 * @endpoint GET /api/tasks
 * 30 tasks — realistic FMCG retail mix.
 *
 * Source distribution:
 *   ~60% PLANNED  — из планировщика (LAMA для SPAR, generic DataConnector)
 *   ~25% MANAGER  — созданы вручную SUPERVISOR / REGIONAL / NETWORK_OPS
 *   ~15% AI       — приняты из AISuggestion (ai_suggestion_id заполнен)
 *
 * State distribution:
 *   5  NEW       (1 без assignee через permission, 1 CASHIER permission, 3 с assignee)
 *   7  IN_PROGRESS
 *   4  PAUSED    (1 REJECTED — отправлена назад с review_comment)
 *   9  COMPLETED (3 ON_REVIEW, 4 ACCEPTED, 2 ON_REVIEW + requires_photo=true + report_image_url)
 *   3  ARCHIVED  (archive_reason: DUPLICATE / WRONG_DATA / OBSOLETE, один с archived_by+archived_at)
 *   2  BONUS type (type=BONUS, bonus_points, goal_id)
 *
 * Edge-cases:
 *   - Одна задача assigned_to_permission='CASHIER' (без personal assignee)
 *   - Одна задача requires_photo=true, НО без report_image_url (валидационный кейс)
 *   - Одна задача kind='CHAIN' с next_assignee_id (передача конвейером)
 *   - Один ARCHIVED task с archived_by + archived_at (для audit-восстановления)
 *   - Одна AI задача fashion-кейс «Уценить сарафан» с marketing_channel_target
 */

const now = new Date("2026-05-01T10:00:00+07:00");
const hoursAgo = (h: number) =>
  new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const minutesAgo = (m: number) =>
  new Date(now.getTime() - m * 60 * 1000).toISOString();

export const MOCK_TASKS: Task[] = [
  // ─────────────────────────────────────────────────────────────────
  // NEW (5)
  // ─────────────────────────────────────────────────────────────────

  /** NEW-1: Назначена на permission CASHIER, без личного assignee */
  {
    id: "task-001",
    title: "Закрытие смены, кассовый отчёт",
    description: "Сформировать Z-отчёт, передать инкассацию, закрыть кассовый журнал за 30 апр.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 20,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 3,
    zone_name: "Касса",
    work_type_id: 2,
    work_type_name: "Касса",
    priority: 1,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: null,
    assignee_name: null,
    assigned_to_permission: "CASHIER",
    state: "NEW",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: false,
    time_start: "21:30:00",
    time_end: "22:00:00",
    archived: false,
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
  },

  /** NEW-2: Без assignee — ещё не распределена (через permission), ждёт назначения */
  {
    id: "task-002",
    title: "Утренняя проверка зала",
    description: "Обойти все зоны до открытия: внешний вид, ценники, чистота, холодильники. Фиксировать замечания.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 30,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 1,
    work_type_name: "Менеджерские операции",
    priority: 1,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: null,
    assignee_name: null,
    assigned_to_permission: null,
    state: "NEW",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: false,
    time_start: "08:00:00",
    time_end: "08:30:00",
    archived: false,
    created_at: hoursAgo(12),
    updated_at: hoursAgo(12),
  },

  /** NEW-3: С назначенным исполнителем */
  {
    id: "task-003",
    title: "Заказ расходников на кассу",
    description: "Оформить заявку на кассовую ленту (57×40мм), чернила для принтера чеков, перчатки. Срок — до 15:00.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 15,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 3,
    zone_name: "Касса",
    work_type_id: 7,
    work_type_name: "Другие работы",
    priority: 100,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 5,
    creator_name: "Иванов Александр Сергеевич",
    assignee_id: 15,
    assignee_name: "Козлова Дарья Андреевна",
    assigned_to_permission: null,
    state: "NEW",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: false,
    time_start: "14:00:00",
    time_end: "14:15:00",
    archived: false,
    created_at: hoursAgo(5),
    updated_at: hoursAgo(5),
  },

  /** NEW-4: Планируемая приёмка товара */
  {
    id: "task-004",
    title: "Приёмка молочки от ООО «Деревенское молочко» (Томск)",
    description: "Приём молочной продукции по накладной №ДМТ-2026-0430. Контроль температуры и сроков. Количество по��иций: 42.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 45,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 2,
    zone_name: "Склад",
    work_type_id: 13,
    work_type_name: "Складские работы",
    priority: 13,
    editable_by_store: false,
    product_category_id: 1,
    product_category_name: "Молочка",
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: 18,
    assignee_name: "Федоров Алексей Николаевич",
    assigned_to_permission: null,
    state: "NEW",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    time_start: "06:00:00",
    time_end: "06:45:00",
    archived: false,
    created_at: hoursAgo(6),
    updated_at: hoursAgo(6),
  },

  /** NEW-5: Ручная задача супервайзера */
  {
    id: "task-005",
    title: "Проверка сроков годности молочки",
    description: "Плановый обход холодильников 1–4 с проверкой сроков годности молочных продуктов. Товары с остатком ≤2 дня — на стол возврата.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "MANAGER",
    planned_minutes: 40,
    store_id: 4,
    store_name: "СПАР Новосибирск, ул. Ленина 55",
    zone_id: 6,
    zone_name: "��о����одильники",
    work_type_id: 11,
    work_type_name: "Контроль качества",
    priority: 11,
    editable_by_store: false,
    product_category_id: 1,
    product_category_name: "Молочка",
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: 23,
    assignee_name: "Волкова Марина Олеговна",
    assigned_to_permission: null,
    state: "NEW",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    time_start: "09:00:00",
    time_end: "09:40:00",
    archived: false,
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1),
  },

  // ─────────────────────────────────────────────────────────────────
  // IN_PROGRESS (7)
  // ─────────────────────────────────────────────────────────────────

  /** IN_PROGRESS-1 */
  {
    id: "task-006",
    title: "Выкладка молочной полки в холодильнике 3",
    description: "Полная перевыкладка молочки по утверждённой планограмме от 28 апр. Фронт строго к покупателю.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 35,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 6,
    zone_name: "Холодильники",
    work_type_id: 4,
    work_type_name: "Выкладка",
    priority: 5,
    editable_by_store: false,
    product_category_id: 1,
    product_category_name: "Молочка",
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: 15,
    assignee_name: "Козлова Дарья Андреевна",
    assigned_to_permission: null,
    state: "IN_PROGRESS",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    time_start: "09:00:00",
    time_end: "09:35:00",
    archived: false,
    history_brief: {
      opened_at: minutesAgo(22),
      paused_intervals: [],
      work_intervals: [{ from: minutesAgo(22), to: now.toISOString() }],
      completed_at: undefined,
    },
    created_at: hoursAgo(4),
    updated_at: minutesAgo(22),
  },

  /** IN_PROGRESS-2 */
  {
    id: "task-007",
    title: "Выкладка пива по планограмме",
    description: "Перевыкладка пивного стеллажа согласно планограмме ПП-06/2026. Лицевой ряд, ротация сроков.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 45,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 4,
    work_type_name: "Выкладка",
    priority: 5,
    editable_by_store: false,
    product_category_id: 6,
    product_category_name: "Пиво",
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: 16,
    assignee_name: "Новиков Максим Юрьевич",
    assigned_to_permission: null,
    state: "IN_PROGRESS",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    time_start: "10:00:00",
    time_end: "10:45:00",
    archived: false,
    history_brief: {
      opened_at: minutesAgo(35),
      paused_intervals: [],
      work_intervals: [{ from: minutesAgo(35), to: now.toISOString() }],
      completed_at: undefined,
    },
    created_at: hoursAgo(5),
    updated_at: minutesAgo(35),
  },

  /** IN_PROGRESS-3 */
  {
    id: "task-008",
    title: "Переоценка кондитерки по выгрузке от 27 апр",
    description: "Заменить ценники согласно выгрузке из 1С от 27 апреля. Приоритет — front-line полки. Старые ценники складывать отдельно.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 50,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 5,
    work_type_name: "Переоценка",
    priority: 3,
    editable_by_store: false,
    product_category_id: 7,
    product_category_name: "Кондитерка",
    creator_id: 5,
    creator_name: "Иванов Александр Сергеевич",
    assignee_id: 19,
    assignee_name: "Захарова Наталья Петровна",
    assigned_to_permission: null,
    state: "IN_PROGRESS",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: false,
    time_start: "10:30:00",
    time_end: "11:20:00",
    archived: false,
    history_brief: {
      opened_at: minutesAgo(18),
      paused_intervals: [],
      work_intervals: [{ from: minutesAgo(18), to: now.toISOString() }],
      completed_at: undefined,
    },
    created_at: hoursAgo(3),
    updated_at: minutesAgo(18),
  },

  /** IN_PROGRESS-4: AI-источник */
  {
    id: "task-009",
    title: "Замена ценников на спецпредложения",
    description: "Актуализировать ценники к акции «Майские скидки» на выделенных стеллажах 7, 9, 12. Обязательно проверить соответствие с промо-листом.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "AI",
    ai_suggestion_id: "ai-sug-003",
    planned_minutes: 30,
    store_id: 4,
    store_name: "СПАР Новосибирск, ул. Ленина 55",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 10,
    work_type_name: "Ценообразование",
    priority: 3,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: 22,
    assignee_name: "Степанов Андрей Борисович",
    assigned_to_permission: null,
    state: "IN_PROGRESS",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: false,
    time_start: "11:00:00",
    time_end: "11:30:00",
    archived: false,
    history_brief: {
      opened_at: minutesAgo(12),
      paused_intervals: [],
      work_intervals: [{ from: minutesAgo(12), to: now.toISOString() }],
      completed_at: undefined,
    },
    created_at: hoursAgo(2),
    updated_at: minutesAgo(12),
  },

  /** IN_PROGRESS-5: Открытие зоны самообслуживания */
  {
    id: "task-010",
    title: "Открытие зоны самообслуживания",
    description: "Включить и проверить все самокассы (12 единиц), загрузить рулоны чеков, протестировать сканеры. Готовность к 09:00.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 20,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 4,
    zone_name: "Самокассы",
    work_type_id: 3,
    work_type_name: "КСО (самокассы)",
    priority: 1,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 5,
    creator_name: "Иванов Александр Сергеевич",
    assignee_id: 20,
    assignee_name: "Попов Владимир Сергеевич",
    assigned_to_permission: null,
    state: "IN_PROGRESS",
    review_state: "NONE",
    acceptance_policy: "AUTO",
    requires_photo: false,
    time_start: "08:40:00",
    time_end: "09:00:00",
    archived: false,
    history_brief: {
      opened_at: minutesAgo(8),
      paused_intervals: [],
      work_intervals: [{ from: minutesAgo(8), to: now.toISOString() }],
      completed_at: undefined,
    },
    created_at: hoursAgo(2),
    updated_at: minutesAgo(8),
  },

  /** IN_PROGRESS-6: Food City */
  {
    id: "task-011",
    title: "Подготовка зоны выпечки",
    description: "Расставить лотки, проверить ценники на выпечку собственного производства, протереть витрину. Включить подогрев к 08:30.",
    type: "PLANNED",
    kind: "CHAIN",
    source: "PLANNED",
    planned_minutes: 25,
    store_id: 7,
    store_name: "Food City Томск Global Market, пр. Ленина 217",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 4,
    work_type_name: "Выкладка",
    priority: 5,
    editable_by_store: false,
    product_category_id: 2,
    product_category_name: "Хлебобулочка",
    creator_id: 12,
    creator_name: "Тарасова Ольга Викторовна",
    assignee_id: 25,
    assignee_name: "Соловьева Ирина Дмитриевна",
    assigned_to_permission: null,
    next_assignee_id: 27,
    next_assignee_name: "Белова Юлия Сергеевна",
    chain_position: 1,
    state: "IN_PROGRESS",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: false,
    time_start: "08:00:00",
    time_end: "08:25:00",
    archived: false,
    history_brief: {
      opened_at: minutesAgo(15),
      paused_intervals: [],
      work_intervals: [{ from: minutesAgo(15), to: now.toISOString() }],
      completed_at: undefined,
    },
    created_at: hoursAgo(3),
    updated_at: minutesAgo(15),
  },

  /** IN_PROGRESS-7: SPAR NSK, AI-источник */
  {
    id: "task-012",
    title: "Инвентаризация заморозки",
    description: "Пересчёт и сверка остатков замороженной продукции в морозильных лари 1–8. Оформить акт разногласий при расхождении ≥ 2%.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "AI",
    ai_suggestion_id: "ai-sug-007",
    planned_minutes: 90,
    store_id: 4,
    store_name: "СПАР Новосибирск, ул. Ленина 55",
    zone_id: 2,
    zone_name: "Склад",
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    priority: 4,
    editable_by_store: false,
    product_category_id: 11,
    product_category_name: "Заморозка",
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: 21,
    assignee_name: "Кириллова Светлана Васильевна",
    assigned_to_permission: null,
    state: "IN_PROGRESS",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    time_start: "07:00:00",
    time_end: "08:30:00",
    archived: false,
    history_brief: {
      opened_at: minutesAgo(45),
      paused_intervals: [],
      work_intervals: [{ from: minutesAgo(45), to: now.toISOString() }],
      completed_at: undefined,
    },
    created_at: hoursAgo(8),
    updated_at: minutesAgo(45),
  },

  // ─────────────────────────────────────────────────────────────────
  // PAUSED (4)
  // ─────────────────────────────────────────────────────────────────

  /** PAUSED-1: Обычная пауза */
  {
    id: "task-013",
    title: "Уборка прикассовой зоны",
    description: "Влажная уборка прикассовой зоны, очистка лент, дезинфекция ручек тележек и корзин.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 20,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 5,
    zone_name: "Прикассовая зона",
    work_type_id: 12,
    work_type_name: "Уборка",
    priority: 12,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 5,
    creator_name: "Иванов Александр Сергеевич",
    assignee_id: 17,
    assignee_name: "Медведева Татьяна Ивановна",
    assigned_to_permission: null,
    state: "PAUSED",
    review_state: "NONE",
    acceptance_policy: "AUTO",
    requires_photo: false,
    comment: "Ждёт поставки чистящего средства со склада",
    time_start: "12:00:00",
    time_end: "12:20:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(2),
      paused_intervals: [{ from: minutesAgo(80), to: now.toISOString() }],
      work_intervals: [{ from: hoursAgo(2), to: minutesAgo(80) }],
      completed_at: undefined,
    },
    created_at: hoursAgo(4),
    updated_at: minutesAgo(80),
  },

  /** PAUSED-2 */
  {
    id: "task-014",
    title: "Приёмка алкоголя от Сибирского винного дома",
    description: "Приём алкоголя по накладной №СВД-0430. Проверить документы ЕГАИС, акцизные марки. Количество позиций: 28.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 60,
    store_id: 2,
    store_name: "СПАР Томск, ул. Красноармейская 99",
    zone_id: 2,
    zone_name: "Склад",
    work_type_id: 13,
    work_type_name: "Складские работы",
    priority: 13,
    editable_by_store: false,
    product_category_id: 4,
    product_category_name: "Алкоголь крепкий",
    creator_id: 6,
    creator_name: "Петрова Елена Владимировна",
    assignee_id: 24,
    assignee_name: "Лебедев Роман Александрович",
    assigned_to_permission: null,
    state: "PAUSED",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    comment: "Водитель задержался, ожидание ТС",
    time_start: "10:00:00",
    time_end: "11:00:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(3),
      paused_intervals: [{ from: minutesAgo(110), to: now.toISOString() }],
      work_intervals: [{ from: hoursAgo(3), to: minutesAgo(110) }],
      completed_at: undefined,
    },
    created_at: hoursAgo(5),
    updated_at: minutesAgo(110),
  },

  /** PAUSED-3 */
  {
    id: "task-015",
    title: "Заказ на расходники РЦ Новосибирск",
    description: "Оформить заявку на расходные материалы для РЦ Новосибирск: стрейч-плёнка, паллетные ленты, маркеры. Дедлайн до 16:00.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "MANAGER",
    planned_minutes: 15,
    store_id: 4,
    store_name: "СПАР Новосибирск, ул. Ленина 55",
    zone_id: 2,
    zone_name: "Склад",
    work_type_id: 7,
    work_type_name: "Другие работы",
    priority: 100,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 7,
    creator_name: "Сидоров Константин Михайлович",
    assignee_id: 21,
    assignee_name: "Кириллова Светлана Васильевна",
    assigned_to_permission: null,
    state: "PAUSED",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: false,
    comment: "Ожидает подтверждения бюджета от регионального",
    time_start: "14:30:00",
    time_end: "14:45:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(1),
      paused_intervals: [{ from: minutesAgo(40), to: now.toISOString() }],
      work_intervals: [{ from: hoursAgo(1), to: minutesAgo(40) }],
      completed_at: undefined,
    },
    created_at: hoursAgo(2),
    updated_at: minutesAgo(40),
  },

  /** PAUSED-4: REJECTED — отправлена назад с review_comment */
  {
    id: "task-016",
    title: "Инвентаризация бакалеи",
    description: "Пересчёт и сверка с остатками в системе: крупы, макароны, консервация, масло. Участки 3, 4, 5.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 120,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    priority: 4,
    editable_by_store: false,
    product_category_id: 3,
    product_category_name: "Бакалея",
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: 17,
    assignee_name: "Медведева Татьяна Ивановна",
    assigned_to_permission: null,
    state: "PAUSED",
    review_state: "REJECTED",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    review_comment: "Отчёт неполный — не хватает скан-листа участка 5. Пересчитать и приложить фото.",
    time_start: "06:00:00",
    time_end: "08:00:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(5),
      paused_intervals: [{ from: hoursAgo(2), to: now.toISOString() }],
      work_intervals: [{ from: hoursAgo(5), to: hoursAgo(2) }],
      completed_at: undefined,
    },
    created_at: hoursAgo(8),
    updated_at: hoursAgo(2),
  },

  // ─────────────────────────────────────────────────────────────────
  // COMPLETED (9)
  // ─────────────────────────────────────────────────────────────────

  /** COMPLETED-1: ON_REVIEW */
  {
    id: "task-017",
    title: "Проверка холодильников 5–8",
    description: "Контрольный обход холодильных агрегатов 5–8: температурный режим, чистота конденсатора, сроки продуктов.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 30,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 6,
    zone_name: "Холодильники",
    work_type_id: 11,
    work_type_name: "Контроль качества",
    priority: 11,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 5,
    creator_name: "Иванов Александр Сергеевич",
    assignee_id: 18,
    assignee_name: "Федоров Алексей Николаевич",
    assigned_to_permission: null,
    state: "COMPLETED",
    review_state: "ON_REVIEW",
    acceptance_policy: "MANUAL",
    requires_photo: false,
    report_text: "Холодильники 5–8 в норме. t° −1…+3°C. Конденсатор чист. Сроки ОК. Замечаний нет.",
    time_start: "07:00:00",
    time_end: "07:30:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(4),
      paused_intervals: [],
      completed_at: hoursAgo(3),
      work_intervals: [{ from: hoursAgo(4), to: hoursAgo(3) }],
    },
    created_at: hoursAgo(6),
    updated_at: hoursAgo(3),
  },

  /** COMPLETED-2: ON_REVIEW */
  {
    id: "task-018",
    title: "Выкладка молочной полки в холодильнике 1",
    description: "Перевыкладка молочных продуктов по планограмме ПГ-МЛ-01. Первичный фронт, ротация по сроку.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 35,
    store_id: 2,
    store_name: "СПАР Томск, ул. Красноармейская 99",
    zone_id: 6,
    zone_name: "Холодильники",
    work_type_id: 4,
    work_type_name: "Выкладка",
    priority: 5,
    editable_by_store: false,
    product_category_id: 1,
    product_category_name: "Молочка",
    creator_id: 6,
    creator_name: "Петрова Елена Владимировна",
    assignee_id: 26,
    assignee_name: "Гусев Павел Михайлович",
    assigned_to_permission: null,
    state: "COMPLETED",
    review_state: "ON_REVIEW",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    report_text: "Выкладка выполнена по планограмме. 3 позиции вынесено в возврат (срок 01 мая). Фото приложено.",
    report_image_url: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800",
    time_start: "07:30:00",
    time_end: "08:05:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(5),
      paused_intervals: [],
      completed_at: hoursAgo(4),
      work_intervals: [{ from: hoursAgo(5), to: hoursAgo(4) }],
    },
    created_at: hoursAgo(7),
    updated_at: hoursAgo(4),
  },

  /** COMPLETED-3: ON_REVIEW + requires_photo=true + report_image_url */
  {
    id: "task-019",
    title: "Выкладка пива по планограмме в SPAR NSK",
    description: "Перевыкладка пивного стеллажа 3 по планограмме ПП-06/2026. Фотофиксация до/после обязательна.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 45,
    store_id: 4,
    store_name: "СПАР Новосибирск, ул. Ленина 55",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 4,
    work_type_name: "Выкладка",
    priority: 5,
    editable_by_store: false,
    product_category_id: 6,
    product_category_name: "Пиво",
    creator_id: 7,
    creator_name: "Сидоров Константин Михайлович",
    assignee_id: 22,
    assignee_name: "Степанов Андрей Борисович",
    assigned_to_permission: null,
    state: "COMPLETED",
    review_state: "ON_REVIEW",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    report_text: "Выкладка выполнена. Стеллаж перестроен по планограмме. Фото после выкладки приложено.",
    report_image_url: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800",
    time_start: "09:00:00",
    time_end: "09:45:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(7),
      paused_intervals: [],
      completed_at: hoursAgo(6),
      work_intervals: [{ from: hoursAgo(7), to: hoursAgo(6) }],
    },
    created_at: hoursAgo(10),
    updated_at: hoursAgo(6),
  },

  /** COMPLETED-4: ACCEPTED */
  {
    id: "task-020",
    title: "Уборка прикассовой зоны (утренняя)",
    description: "Утренняя уборка зоны касс и прикассовой зоны перед открытием магазина.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 20,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 5,
    zone_name: "Прикассовая зона",
    work_type_id: 12,
    work_type_name: "Уборка",
    priority: 12,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 5,
    creator_name: "Иванов Алекс��ндр Сергеевич",
    assignee_id: 17,
    assignee_name: "Медведева Татьяна Ивановна",
    assigned_to_permission: null,
    state: "COMPLETED",
    review_state: "ACCEPTED",
    acceptance_policy: "AUTO",
    requires_photo: false,
    time_start: "07:30:00",
    time_end: "07:50:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(10),
      paused_intervals: [],
      completed_at: hoursAgo(9),
      work_intervals: [{ from: hoursAgo(10), to: hoursAgo(9) }],
    },
    created_at: hoursAgo(12),
    updated_at: hoursAgo(9),
  },

  /** COMPLETED-5: ACCEPTED */
  {
    id: "task-021",
    title: "Переоценка спецпредложений к майским",
    description: "Замена ценников по промо-листу №МАЙ-2026. Касается: напитки, снеки, кондитерка на торцах.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 40,
    store_id: 4,
    store_name: "СПАР Новосибирск, ул. Ленина 55",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 5,
    work_type_name: "Переоценка",
    priority: 3,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 7,
    creator_name: "Сидоров Константин Михайлович",
    assignee_id: 23,
    assignee_name: "Волкова Марина Олеговна",
    assigned_to_permission: null,
    state: "COMPLETED",
    review_state: "ACCEPTED",
    acceptance_policy: "MANUAL",
    requires_photo: false,
    report_text: "Все 86 позиций переоценены. Расхождений с промо-листом нет.",
    time_start: "06:30:00",
    time_end: "07:10:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(11),
      paused_intervals: [],
      completed_at: hoursAgo(10),
      work_intervals: [{ from: hoursAgo(11), to: hoursAgo(10) }],
    },
    created_at: hoursAgo(13),
    updated_at: hoursAgo(10),
  },

  /** COMPLETED-6: ACCEPTED */
  {
    id: "task-022",
    title: "Мерчендайзинг выкладки снеков по планограмме",
    description: "Реализация планограммы ПГ-СНК-04 по снековому стеллажу. Все позиции выставить согласно схеме.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 60,
    store_id: 7,
    store_name: "Food City Томск Global Market, пр. Ленина 217",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 9,
    work_type_name: "Мерчендайзинг (планограммы)",
    priority: 5,
    editable_by_store: false,
    product_category_id: 19,
    product_category_name: "Снеки солёные",
    creator_id: 12,
    creator_name: "Тарасова Ольга Викторовна",
    assignee_id: 27,
    assignee_name: "Белова Юлия Сергеевна",
    assigned_to_permission: null,
    state: "COMPLETED",
    review_state: "ACCEPTED",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    report_text: "Планограмма реализована полностью. Фото приложено.",
    report_image_url: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800",
    time_start: "08:00:00",
    time_end: "09:00:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(15),
      paused_intervals: [],
      completed_at: hoursAgo(14),
      work_intervals: [{ from: hoursAgo(15), to: hoursAgo(14) }],
    },
    created_at: hoursAgo(18),
    updated_at: hoursAgo(14),
  },

  /** COMPLETED-7: ACCEPTED */
  {
    id: "task-023",
    title: "Контроль качества молочной продукции",
    description: "Плановая проверка сроков годности молочки во всех холодильниках. Занести отклонения в журнал.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 40,
    store_id: 2,
    store_name: "СПАР Томск, ул. Красноармейская 99",
    zone_id: 6,
    zone_name: "Холодильники",
    work_type_id: 11,
    work_type_name: "Контроль качества",
    priority: 11,
    editable_by_store: false,
    product_category_id: 1,
    product_category_name: "Молочка",
    creator_id: 6,
    creator_name: "Петрова Елена Владимировна",
    assignee_id: 19,
    assignee_name: "Захарова Наталья Петровна",
    assigned_to_permission: null,
    state: "COMPLETED",
    review_state: "ACCEPTED",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    report_text: "Проверено 94 позиции. 4 единицы списаны — срок истёк 30 апр. Остальные в норме.",
    report_image_url: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800",
    time_start: "07:00:00",
    time_end: "07:40:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(12),
      paused_intervals: [],
      completed_at: hoursAgo(11),
      work_intervals: [{ from: hoursAgo(12), to: hoursAgo(11) }],
    },
    created_at: hoursAgo(14),
    updated_at: hoursAgo(11),
  },

  /**
   * COMPLETED-8: requires_photo=true БЕЗ report_image_url.
   * Валидационный edge-case — исполнитель завершил задачу без фото.
   */
  {
    id: "task-024",
    title: "Мерчендайзинг зоны выпечки",
    description: "Выкладка хлебобулочных изделий по схеме ПГ-ВП-01 в зоне выпечки.",
    type: "PLANNED",
    kind: "CHAIN",
    source: "PLANNED",
    planned_minutes: 20,
    store_id: 7,
    store_name: "Food City Томск Global Market, пр. Ленина 217",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 4,
    work_type_name: "Выкладка",
    priority: 5,
    editable_by_store: false,
    product_category_id: 2,
    product_category_name: "Хлебобулочка",
    creator_id: 12,
    creator_name: "Тарасова Ольга Викторовна",
    assignee_id: 27,
    assignee_name: "Белова Юлия Сергеевна",
    assigned_to_permission: null,
    chain_position: 2,
    state: "COMPLETED",
    review_state: "ON_REVIEW",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    report_text: "Выкладка выполнена по схеме.",
    // report_image_url намеренно отсутствует — валидационный кейс
    time_start: "08:25:00",
    time_end: "08:45:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(9),
      paused_intervals: [],
      completed_at: hoursAgo(8),
      work_intervals: [{ from: hoursAgo(9), to: hoursAgo(8) }],
    },
    created_at: hoursAgo(10),
    updated_at: hoursAgo(8),
  },

  /** COMPLETED-9: AI-источник, fashion, marketing_channel_target */
  {
    id: "task-025",
    title: "Уценить сарафан — промо через «Канал распродаж»",
    description: "AI-предложение: снизить цену на сарафан арт. ALF-SAR-0412 до 1490 ₽ (−34%). Добавить стикер уценки, разместить на акционном торце, опубликовать в Канале распродаж Telegram.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "AI",
    ai_suggestion_id: "ai-sug-012",
    planned_minutes: 20,
    store_id: 10,
    store_name: "Магазин одежды Альфа, Томск, пр. Ленина 50",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 5,
    work_type_name: "Переоценка",
    priority: 3,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 11,
    creator_name: "Никитина Анна Николаевна",
    assignee_id: 15,
    assignee_name: "Козлова Дарья Андреевна",
    assigned_to_permission: null,
    marketing_channel_target: "Канал распродаж",
    state: "COMPLETED",
    review_state: "ACCEPTED",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    report_text: "Стикер уценки наклеен. Торец оформлен. Пост опубликован в канале распродаж — 1 247 просмотров за час.",
    report_image_url: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800",
    time_start: "13:00:00",
    time_end: "13:20:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(20),
      paused_intervals: [],
      completed_at: hoursAgo(19),
      work_intervals: [{ from: hoursAgo(20), to: hoursAgo(19) }],
    },
    created_at: hoursAgo(22),
    updated_at: hoursAgo(19),
  },

  // ─────────────────────────────────────────────────────────────────
  // BONUS (2)
  // ─────────────────────────────────────────────────────────────────

  /**
   * BONUS-1: OOS_REDUCTION, 500 баллов
   * goal_id ссылается на goal-oos-001 (в goals.ts).
   */
  {
    id: "task-026",
    title: "БОНУС: Снижение OOS в молочке за смену",
    description: "Бонусная задача: выявить и устранить все «дыры» в выкладке молочки в течение смены. Контрольная точка — 0 пустых фейсингов к 14:00. Бонус начисляется при подтверждении супервайзером.",
    type: "BONUS",
    kind: "SINGLE",
    source: "AI",
    ai_suggestion_id: "ai-sug-015",
    planned_minutes: 60,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 6,
    zone_name: "Холодильники",
    work_type_id: 4,
    work_type_name: "Выкладка",
    priority: 5,
    editable_by_store: false,
    product_category_id: 1,
    product_category_name: "Молочка",
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: 15,
    assignee_name: "Козлова Дарья Андреевна",
    assigned_to_permission: null,
    goal_id: "goal-oos-001",
    bonus_points: 500,
    state: "IN_PROGRESS",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    time_start: "09:00:00",
    time_end: "14:00:00",
    archived: false,
    history_brief: {
      opened_at: minutesAgo(50),
      paused_intervals: [],
      work_intervals: [{ from: minutesAgo(50), to: now.toISOString() }],
      completed_at: undefined,
    },
    created_at: hoursAgo(2),
    updated_at: minutesAgo(50),
  },

  /**
   * BONUS-2: Промо-выкладка, 300 баллов
   * goal_id ссылается на goal-promo-001 (в goals.ts).
   */
  {
    id: "task-027",
    title: "БОНУС: Промо-выкладка к майским",
    description: "Оформить 4 торцевых стеллажа под акцию «Майские скидки». Товарные группы: безалкогольные напитки, снеки, кондитерка. Фотоотчёт обязателен. 300 бонусных баллов за качественное исполнение.",
    type: "BONUS",
    kind: "SINGLE",
    source: "MANAGER",
    planned_minutes: 90,
    store_id: 4,
    store_name: "СПАР Новосибирск, ул. Ленина 55",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 9,
    work_type_name: "Мерчендайзинг (планограммы)",
    priority: 5,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: 22,
    assignee_name: "Степанов Андрей Борисович",
    assigned_to_permission: null,
    goal_id: "goal-promo-001",
    bonus_points: 300,
    state: "NEW",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    time_start: "13:00:00",
    time_end: "14:30:00",
    archived: false,
    created_at: hoursAgo(4),
    updated_at: hoursAgo(4),
  },

  // ─────────────────────────────────────────────────────────────────
  // ARCHIVED (3)
  // ─────────────────────────────────────────────────────────────────

  /** ARCHIVED-1: DUPLICATE */
  {
    id: "task-028",
    title: "Выкладка молочной полки (дубль)",
    description: "Дубликат задачи task-006 — создан ошибочно при повторном импорте из планировщика.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 35,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 6,
    zone_name: "Холодильники",
    work_type_id: 4,
    work_type_name: "Выкладка",
    priority: 5,
    editable_by_store: false,
    product_category_id: 1,
    product_category_name: "Молочка",
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: 15,
    assignee_name: "Козлова Дарья Андреевна",
    assigned_to_permission: null,
    state: "NEW",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    time_start: "09:00:00",
    time_end: "09:35:00",
    archived: true,
    archive_reason: "DUPLICATE",
    archived_at: hoursAgo(1),
    archived_by: 4,
    created_at: hoursAgo(5),
    updated_at: hoursAgo(1),
  },

  /** ARCHIVED-2: WRONG_DATA */
  {
    id: "task-029",
    title: "Переоценка вина по выгрузке (ошибочные данные)",
    description: "Задача содержала некорректные цены из выгрузки с ошибкой курса. Аннулирована до начала исполнения.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 30,
    store_id: 2,
    store_name: "СПАР Томск, ул. Красноармейская 99",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 5,
    work_type_name: "Переоценка",
    priority: 3,
    editable_by_store: false,
    product_category_id: 5,
    product_category_name: "Вино",
    creator_id: 6,
    creator_name: "Петрова Елена Владимировна",
    assignee_id: 26,
    assignee_name: "Гусев Павел Михайлович",
    assigned_to_permission: null,
    state: "NEW",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: false,
    time_start: "11:00:00",
    time_end: "11:30:00",
    archived: true,
    archive_reason: "WRONG_DATA",
    archived_at: hoursAgo(3),
    archived_by: 4,
    created_at: hoursAgo(6),
    updated_at: hoursAgo(3),
  },

  // ─────────────────────────────────────────────────────────────────
  // REVIEW QUEUE — additional ON_REVIEW tasks (for /tasks/review)
  // ─────────────────────────────────────────────────────────────────

  /** ON_REVIEW-5: Уборка склада, без фото */
  {
    id: "task-rv-001",
    title: "Уборка складских проходов перед приёмкой",
    description: "Очистить проходы 1–4 на складе перед утренней приёмкой. Убрать поддоны, промаркировать зоны.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 25,
    store_id: 2,
    store_name: "СПАР Томск, ул. Красноармейская 99",
    zone_id: 2,
    zone_name: "Склад",
    work_type_id: 12,
    work_type_name: "Уборка",
    priority: 12,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 6,
    creator_name: "Петрова Елена Владимировна",
    assignee_id: 24,
    assignee_name: "Лебедев Роман Александрович",
    assigned_to_permission: null,
    state: "COMPLETED",
    review_state: "ON_REVIEW",
    acceptance_policy: "MANUAL",
    requires_photo: false,
    report_text: "Проходы 1–4 очищены. Поддоны убраны в стеллажную зону. Зоны промаркированы.",
    time_start: "06:00:00",
    time_end: "06:25:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(6),
      paused_intervals: [],
      completed_at: hoursAgo(5),
      work_intervals: [{ from: hoursAgo(6), to: hoursAgo(5) }],
    },
    created_at: hoursAgo(8),
    updated_at: hoursAgo(5),
  },

  /** ON_REVIEW-6: Переоценка алкоголя с фото */
  {
    id: "task-rv-002",
    title: "Переоценка алкоголя по акции «Майские»",
    description: "Замена ценников в алкогольном отделе согласно промо-листу МАЙ-АЛК-2026. Приоритет — витринные позиции.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 30,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 5,
    work_type_name: "Переоценка",
    priority: 3,
    editable_by_store: false,
    product_category_id: 4,
    product_category_name: "Алкоголь крепкий",
    creator_id: 5,
    creator_name: "Иванов Александр Сергеевич",
    assignee_id: 16,
    assignee_name: "Новиков Максим Юрьевич",
    assigned_to_permission: null,
    state: "COMPLETED",
    review_state: "ON_REVIEW",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    report_text: "Переоценка выполнена. 54 ценника заменены. Все витринные позиции обновлены по промо-листу.",
    report_image_url: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=800",
    time_start: "07:00:00",
    time_end: "07:30:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(5),
      paused_intervals: [],
      completed_at: hoursAgo(4),
      work_intervals: [{ from: hoursAgo(5), to: hoursAgo(4) }],
    },
    created_at: hoursAgo(7),
    updated_at: hoursAgo(4),
  },

  /** ON_REVIEW-7: Инвентаризация бакалеи (длинный report_text) */
  {
    id: "task-rv-003",
    title: "Инвентаризация бакалейного отдела (участки 1–3)",
    description: "Пересчёт остатков по бакалее: крупы, макароны, консервы, масло растительное. Участки 1, 2, 3 торгового зала. Сверить с данными 1С, зафиксировать расхождения в листе инвентаризации.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "MANAGER",
    planned_minutes: 90,
    store_id: 4,
    store_name: "СПАР Новосибирск, ул. Ленина 55",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    priority: 4,
    editable_by_store: false,
    product_category_id: 3,
    product_category_name: "Бакалея",
    creator_id: 7,
    creator_name: "Сидоров Константин Михайлович",
    assignee_id: 22,
    assignee_name: "Степанов Андрей Борисович",
    assigned_to_permission: null,
    state: "COMPLETED",
    review_state: "ON_REVIEW",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    report_text: "Инвентаризация участков 1–3 завершена. Итоги: пересчитано 847 позиций из 863 по реестру. Расхождений выявлено 14 единиц: 6 по крупам (недостача макарон «Barilla» 400г — 3 шт., «Makfa» 900г — 3 шт.), 4 по консервам (излишек «Сайра» 250г — 4 шт.), 4 по маслу (недостача «Sloboda» 1л — 2 шт., «Олейна» 0.85л — 2 шт.). Лист инвентаризации подписан, акт разногласий составлен и передан товароведу. Участок 4 не проверен — зона была занята выкладкой, перенесено на завтра.",
    report_image_url: "https://images.unsplash.com/photo-1588964895597-cfccd6e2dbf9?w=800",
    time_start: "06:00:00",
    time_end: "07:30:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(8),
      paused_intervals: [{ from: hoursAgo(7), to: hoursAgo(6.5) }],
      completed_at: hoursAgo(5.5),
      work_intervals: [
        { from: hoursAgo(8), to: hoursAgo(7) },
        { from: hoursAgo(6.5), to: hoursAgo(5.5) },
      ],
    },
    created_at: hoursAgo(10),
    updated_at: hoursAgo(5.5),
  },

  /** ON_REVIEW-8: requires_photo=true НО без report_image_url (валидационный кейс для review) */
  {
    id: "task-rv-004",
    title: "Контроль ценников на торцах (акционная зона)",
    description: "Проверить наличие и соответствие ценников на всех 6 акционных торцах. Несоответствия исправить на месте.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 20,
    store_id: 7,
    store_name: "Food City Томск Global Market, пр. Ленина 217",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 11,
    work_type_name: "Контроль качества",
    priority: 11,
    editable_by_store: false,
    product_category_id: null,
    product_category_name: null,
    creator_id: 12,
    creator_name: "Тарасова Ольга Викторовна",
    assignee_id: 25,
    assignee_name: "Соловьева Ирина Дмитриевна",
    assigned_to_permission: null,
    state: "COMPLETED",
    review_state: "ON_REVIEW",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    // report_image_url намеренно отсутствует — валидационный кейс для review queue
    report_text: "Проверено 6 торцов. Найдено 2 несоответствия — исправлено на месте.",
    time_start: "08:30:00",
    time_end: "08:50:00",
    archived: false,
    history_brief: {
      opened_at: hoursAgo(3),
      paused_intervals: [],
      completed_at: hoursAgo(2.5),
      work_intervals: [{ from: hoursAgo(3), to: hoursAgo(2.5) }],
    },
    created_at: hoursAgo(4),
    updated_at: hoursAgo(2.5),
  },

  // ─────────────────────────────────────────────────────────────────
  // DEMO DETAIL TASK — t-1042
  // ─────���───────────────────────────────────────────────────────────

  /**
   * t-1042: «Выкладка молочной полки» — полный кейс для TaskDetail.
   * state=COMPLETED, review_state=ON_REVIEW, is_overdue=true
   * requires_photo=true, report_image_url задан, report_text задан.
   * Плановое время: 45 мин (09:30–10:15), фактическое 52 мин.
   * Дедлайн: 09:30 28 апр — просрочка ~68 мин.
   */
  {
    id: "t-1042",
    title: "Выкладка молочной полки",
    description: "Полная перевыкладка молочной секции холодильника 2 по утверждённой планограмме от 27 апр. Фронт строго к покупателю. Ротация сроков обязательна. Перед началом убедитесь, что температура в секции +2…+4°C.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 45,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 6,
    zone_name: "Холодильники",
    work_type_id: 4,
    work_type_name: "Выкладка",
    priority: 5,
    editable_by_store: false,
    product_category_id: 1,
    product_category_name: "Молочка",
    creator_id: 5,
    creator_name: "Иванов Александр Сергеевич",
    assignee_id: 15,
    assignee_name: "Козлова Дарья Андреевна",
    assigned_to_permission: null,
    state: "COMPLETED",
    review_state: "ON_REVIEW",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    is_overdue: true,
    comment: "Обратите внимание: в секции 2Б освободилось место после списания просрочки. Доложить оттуда в первую очередь.",
    report_text: "Выкладка выполнена полностью. Секция 2Б доложена после списания просрочки (8 позиций). Все этикетки обращены фронтом, ротация сроков соблюдена. Температура в секции при завершении +3°C. Обнаружено 2 позиции без ценников — передала на переоценку.",
    report_image_url: "https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=800&q=80",
    time_start: "09:30:00",
    time_end: "10:15:00",
    archived: false,
    history_brief: {
      opened_at: new Date("2026-04-28T09:38:00+07:00").toISOString(),
      paused_intervals: [
        {
          from: new Date("2026-04-28T10:05:00+07:00").toISOString(),
          to: new Date("2026-04-28T10:12:00+07:00").toISOString(),
        },
      ],
      work_intervals: [
        {
          from: new Date("2026-04-28T09:38:00+07:00").toISOString(),
          to: new Date("2026-04-28T10:05:00+07:00").toISOString(),
        },
        {
          from: new Date("2026-04-28T10:12:00+07:00").toISOString(),
          to: new Date("2026-04-28T10:30:00+07:00").toISOString(),
        },
      ],
      completed_at: new Date("2026-04-28T10:30:00+07:00").toISOString(),
    },
    created_at: new Date("2026-04-28T07:00:00+07:00").toISOString(),
    updated_at: new Date("2026-04-28T10:32:00+07:00").toISOString(),
  },

  /**
   * ARCHIVED-3: OBSOLETE — с archived_by + archived_at.
   * Полный audit-кейс для демо восстановления (Restore button).
   */
  {
    id: "task-030",
    title: "Инвентаризация бакалеи (старая смена)",
    description: "Задача осталась открытой с прошлой смены. Закрыта как устаревшая после того, как инвентаризация была проведена по другой заявке.",
    type: "PLANNED",
    kind: "SINGLE",
    source: "PLANNED",
    planned_minutes: 120,
    store_id: 1,
    store_name: "СПАР Томск, пр. Ленина 80",
    zone_id: 1,
    zone_name: "Торговый зал",
    work_type_id: 6,
    work_type_name: "Инвентаризация",
    priority: 4,
    editable_by_store: false,
    product_category_id: 3,
    product_category_name: "Бакалея",
    creator_id: 4,
    creator_name: "Романов Игорь Алексеевич",
    assignee_id: 16,
    assignee_name: "Новиков Максим Юрьевич",
    assigned_to_permission: null,
    state: "NEW",
    review_state: "NONE",
    acceptance_policy: "MANUAL",
    requires_photo: true,
    time_start: "06:00:00",
    time_end: "08:00:00",
    archived: true,
    archive_reason: "OBSOLETE",
    archived_at: hoursAgo(10),
    archived_by: 4,
    created_at: hoursAgo(30),
    updated_at: hoursAgo(10),
  },
];
