import type { User } from "@/lib/types";

/**
 * @endpoint GET /api/users
 * 30 users:
 *   1  PLATFORM_ADMIN (Beyond Violet staff)
 *   1  AGENT (ИП Захарова М.С., login → /agent)
 *   1  NETWORK_OPS (Соколова А.В., totp_enabled=true, Europe/London — демо таймзоны)
 *   1  HR_MANAGER
 *   1  OPERATOR (preferred_locale='en' — демо english-режима)
 *   2  SUPERVISOR
 *   6  STORE_DIRECTOR
 *   14 WORKER (mix of permissions; один в архиве)
 *   3  FREELANCE (базовый демо, полный список — в freelance-freelancers.ts)
 *
 * Functional roles и scope — в functional-roles.ts.
 * Hired_at — даты за последние 18 месяцев относительно мая 2026.
 */

const d = (iso: string) => iso; // readability helper

export const MOCK_USERS: User[] = [
  // ── 1. PLATFORM_ADMIN ─────────────────────────────────────────────
  {
    id: 1,
    sso_id: "sso-platform-admin-001",
    phone: "+7 (900) 100-00-01",
    email: "s.ivanov@beyondviolet.io",
    first_name: "Сергей",
    last_name: "Иванов",
    middle_name: "Константинович",
    type: "STAFF",
    hired_at: d("2024-01-15"),
    archived: false,
    preferred_locale: "en",
    preferred_timezone: "Europe/Moscow",
    totp_enabled: false,
  },

  // ── 2. AGENT ──────────────────────────────────────────────────────
  {
    /** Login → редиректит на /agent. Привязан к agent-001 (из freelance-agents.ts) */
    id: 2,
    sso_id: "sso-agent-zakharova",
    phone: "+7 (913) 200-11-22",
    email: "m.zakharova@ipzakharova.ru",
    first_name: "Марина",
    last_name: "Захарова",
    middle_name: "Сергеевна",
    type: "STAFF",
    hired_at: d("2024-06-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    agent_id: "agent-001",
  },

  // ── 3. NETWORK_OPS (СPAR Сибирь) — totp enabled, Europe/London ──
  {
    id: 3,
    sso_id: "sso-network-ops-sokolova",
    phone: "+7 (913) 300-22-33",
    email: "a.sokolova@spar-sibir.ru",
    first_name: "Анна",
    last_name: "Соколова",
    middle_name: "Викторовна",
    type: "STAFF",
    hired_at: d("2023-09-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Europe/London",
    totp_enabled: true,
    rating: 4.9,
  },

  // ── 4. SUPERVISOR (СПАР Томск + Новосибирск) ─────────────────────
  {
    id: 4,
    sso_id: "sso-supervisor-romanov",
    phone: "+7 (913) 401-33-44",
    email: "i.romanov@spar-sibir.ru",
    first_name: "Игорь",
    last_name: "Романов",
    middle_name: "Алексеевич",
    type: "STAFF",
    hired_at: d("2023-11-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.7,
  },

  // ── 5. STORE_DIRECTOR — SPAR-TOM-001 ────────────────────────────
  {
    id: 5,
    sso_id: "sso-sd-ivanov-as",
    phone: "+7 (913) 501-44-55",
    email: "a.ivanov@spar-sibir.ru",
    first_name: "Александр",
    last_name: "Иванов",
    middle_name: "Сергеевич",
    type: "STAFF",
    hired_at: d("2024-02-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.5,
  },

  // ── 6. STORE_DIRECTOR — SPAR-TOM-002 ────────────────────────────
  {
    id: 6,
    sso_id: "sso-sd-petrova",
    phone: "+7 (913) 601-55-66",
    email: "e.petrova@spar-sibir.ru",
    first_name: "Елена",
    last_name: "Петрова",
    middle_name: "Владимировна",
    type: "STAFF",
    hired_at: d("2024-03-15"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.6,
  },

  // ── 7. STORE_DIRECTOR — SPAR-NSK-001 ────────────────────────────
  {
    id: 7,
    sso_id: "sso-sd-sidorov",
    phone: "+7 (923) 701-66-77",
    email: "k.sidorov@spar-sibir.ru",
    first_name: "Константин",
    last_name: "Сидоров",
    middle_name: "Михайлович",
    type: "STAFF",
    hired_at: d("2023-12-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 4.4,
  },

  // ── 8. STORE_DIRECTOR — SPAR-NSK-002 ────────────────────────────
  {
    id: 8,
    sso_id: "sso-sd-vasiliev",
    phone: "+7 (923) 801-77-88",
    email: "d.vasiliev@spar-sibir.ru",
    first_name: "Дмитрий",
    last_name: "Васильев",
    middle_name: "Олегович",
    type: "STAFF",
    hired_at: d("2024-01-10"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 4.3,
  },

  // ── 9. STORE_DIRECTOR — SPAR-KEM-001 ────────────────────────────
  {
    id: 9,
    sso_id: "sso-sd-nikitin",
    phone: "+7 (384) 901-88-99",
    email: "b.nikitin@spar-sibir.ru",
    first_name: "Борис",
    last_name: "Никитин",
    middle_name: "Сергеевич",
    type: "STAFF",
    hired_at: d("2024-04-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 4.2,
  },

  // ── 10. STORE_DIRECTOR — FC-TOM-001 ─────────────────────────────
  {
    id: 10,
    sso_id: "sso-sd-smirnova",
    phone: "+7 (913) 100-99-88",
    email: "o.smirnova@foodcity.ru",
    first_name: "Ольга",
    last_name: "Смирнова",
    middle_name: "Игоревна",
    type: "STAFF",
    hired_at: d("2023-10-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.8,
  },

  // ── 11. NETWORK_OPS — org-fashion-alfa (малый бизнес, владелец) ─
  {
    id: 11,
    sso_id: "sso-network-ops-nikitina",
    phone: "+7 (913) 111-00-11",
    email: "a.nikitina@alfa-fashion.ru",
    first_name: "Анна",
    last_name: "Никитина",
    middle_name: "Николаевна",
    type: "STAFF",
    hired_at: d("2024-05-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.9,
  },

  // ── 12. SUPERVISOR — Food City (3 магазина) ──────────────────────
  {
    id: 12,
    sso_id: "sso-supervisor-tarasova",
    phone: "+7 (913) 120-22-33",
    email: "o.tarasova@foodcity.ru",
    first_name: "Ольга",
    last_name: "Тарасова",
    middle_name: "Викторовна",
    type: "STAFF",
    hired_at: d("2024-01-20"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.6,
  },

  // ── 13. HR_MANAGER ──────────────────────────────────────────────
  {
    id: 13,
    sso_id: "sso-hr-morozova",
    phone: "+7 (913) 130-33-44",
    email: "e.morozova@spar-sibir.ru",
    first_name: "Елена",
    last_name: "Морозова",
    middle_name: "Сергеевна",
    type: "STAFF",
    hired_at: d("2024-02-15"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
  },

  // ── 14. OPERATOR (preferred_locale='en' — демо EN-режима) ────────
  {
    id: 14,
    sso_id: "sso-operator-kuznetsov",
    phone: "+7 (913) 140-44-55",
    email: "n.kuznetsov@spar-sibir.ru",
    first_name: "Никита",
    last_name: "Кузнецов",
    middle_name: "Павлович",
    type: "STAFF",
    hired_at: d("2024-03-01"),
    archived: false,
    preferred_locale: "en",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
  },

  // ── 15-28. WORKERS ───────────────────────────────────────────────
  {
    id: 15,
    sso_id: "sso-worker-001",
    phone: "+7 (913) 150-55-01",
    first_name: "Дарья",
    last_name: "Козлова",
    middle_name: "Андреевна",
    type: "STAFF",
    hired_at: d("2024-06-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.1,
  },
  {
    id: 16,
    sso_id: "sso-worker-002",
    phone: "+7 (913) 150-55-02",
    first_name: "Максим",
    last_name: "Новиков",
    middle_name: "Юрьевич",
    type: "STAFF",
    hired_at: d("2024-07-15"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 3.9,
  },
  {
    id: 17,
    sso_id: "sso-worker-003",
    phone: "+7 (913) 150-55-03",
    first_name: "Татьяна",
    last_name: "Медведева",
    middle_name: "Ивановна",
    type: "STAFF",
    hired_at: d("2024-08-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.3,
  },
  {
    id: 18,
    sso_id: "sso-worker-004",
    phone: "+7 (913) 150-55-04",
    first_name: "Алексей",
    last_name: "Федоров",
    middle_name: "Николаевич",
    type: "STAFF",
    hired_at: d("2024-09-10"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.0,
  },
  {
    id: 19,
    sso_id: "sso-worker-005",
    phone: "+7 (913) 150-55-05",
    first_name: "Наталья",
    last_name: "Захарова",
    middle_name: "Петровна",
    type: "STAFF",
    hired_at: d("2024-10-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.4,
  },
  {
    id: 20,
    sso_id: "sso-worker-006",
    phone: "+7 (913) 150-55-06",
    first_name: "Владимир",
    last_name: "Попов",
    middle_name: "Сергеевич",
    type: "STAFF",
    hired_at: d("2024-11-15"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 3.8,
  },
  {
    id: 21,
    sso_id: "sso-worker-007",
    phone: "+7 (923) 150-55-07",
    first_name: "Светлана",
    last_name: "Кириллова",
    middle_name: "Васильевна",
    type: "STAFF",
    hired_at: d("2024-12-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    rating: 4.2,
  },
  {
    id: 22,
    sso_id: "sso-worker-008",
    phone: "+7 (923) 150-55-08",
    first_name: "Андрей",
    last_name: "Степанов",
    middle_name: "Борисович",
    type: "STAFF",
    hired_at: d("2025-01-10"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    rating: 3.7,
  },
  {
    id: 23,
    sso_id: "sso-worker-009",
    phone: "+7 (923) 150-55-09",
    first_name: "Марина",
    last_name: "Волкова",
    middle_name: "Олеговна",
    type: "STAFF",
    hired_at: d("2025-02-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    rating: 4.5,
  },
  {
    id: 24,
    sso_id: "sso-worker-010",
    phone: "+7 (913) 150-55-10",
    first_name: "Роман",
    last_name: "Лебедев",
    middle_name: "Александрович",
    type: "STAFF",
    hired_at: d("2025-03-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.0,
  },
  {
    id: 25,
    sso_id: "sso-worker-011",
    phone: "+7 (913) 150-55-11",
    first_name: "Ирина",
    last_name: "Соловьева",
    middle_name: "Дмитриевна",
    type: "STAFF",
    hired_at: d("2025-04-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.6,
  },
  {
    id: 26,
    sso_id: "sso-worker-012",
    phone: "+7 (913) 150-55-12",
    first_name: "Павел",
    last_name: "Гусев",
    middle_name: "Михайлович",
    type: "STAFF",
    hired_at: d("2025-05-01"),
    archived: false,
    preferred_locale: "en",
    preferred_timezone: "Asia/Tomsk",
    rating: 3.9,
  },
  {
    id: 27,
    sso_id: "sso-worker-013",
    phone: "+7 (913) 150-55-13",
    first_name: "Юлия",
    last_name: "Белова",
    middle_name: "Сергеевна",
    type: "STAFF",
    hired_at: d("2025-06-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.3,
  },
  {
    /** Архивирован — уволен. archive_reason=OBSOLETE. Демо EmployeeFilter archived */
    id: 28,
    sso_id: "sso-worker-014",
    phone: "+7 (913) 150-55-14",
    first_name: "Игорь",
    last_name: "Тихонов",
    middle_name: "Васильевич",
    type: "STAFF",
    hired_at: d("2024-05-01"),
    archived: true,
    archive_reason: "OBSOLETE",
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 3.5,
  },

  // ── 29-31. FREELANCE (базовые примеры; полный список — freelance-freelancers.ts) ──
  {
    /** FREELANCE — активен, оферта подписана */
    id: 29,
    sso_id: "sso-freelance-001",
    phone: "+7 (913) 200-01-11",
    first_name: "Виктор",
    last_name: "Орлов",
    middle_name: "Павлович",
    type: "FREELANCE",
    hired_at: d("2025-01-15"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-001",
    oferta_accepted_at: d("2025-01-15"),
    rating: 4.7,
    source: "MANUAL",
  },
  {
    /** FREELANCE — в проверке (VERIFICATION) */
    id: 30,
    sso_id: "sso-freelance-002",
    phone: "+7 (913) 200-02-22",
    first_name: "Ксения",
    last_name: "Фролова",
    middle_name: "Андреевна",
    type: "FREELANCE",
    hired_at: d("2025-03-20"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "VERIFICATION",
    agent_id: "agent-001",
    oferta_accepted_at: null,
    rating: undefined,
    source: "MANUAL",
  },
  {
    /** FREELANCE — пришёл из внешней HR-системы SPAR (source=EXTERNAL_SYNC) */
    id: 31,
    sso_id: "sso-freelance-003",
    phone: "+7 (913) 200-03-33",
    first_name: "Евгений",
    last_name: "Мельников",
    middle_name: "Игоревич",
    type: "FREELANCE",
    hired_at: d("2025-04-10"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: null,
    oferta_accepted_at: d("2025-04-10"),
    rating: 4.5,
    source: "EXTERNAL_SYNC",
  },
];
