import type { User } from "@/lib/types";

/**
 * @endpoint GET /api/users
 * 100+ users:
 *   1  PLATFORM_ADMIN (Beyond Violet staff)
 *   1  AGENT (ИП Захарова М.С., login → /agent)
 *   1  NETWORK_OPS (Соколова А.В., totp_enabled=true, Europe/London — демо таймзоны)
 *   1  HR_MANAGER
 *   1  OPERATOR (preferred_locale='en' — демо english-режима)
 *   2  SUPERVISOR
 *   6  STORE_DIRECTOR
 *   14 WORKER (mix of permissions; один в архиве)
 *   3  FREELANCE (базовый демо, полный список — в freelance-freelancers.ts)
 *
 * Functional roles и scope — в functional-roles.ts.
 * Hired_at — даты за последние 18 месяцев относительно мая 2026.
 */

const d = (iso: string) => iso; // readability helper

export const MOCK_USERS: User[] = [
  // ── 1. PLATFORM_ADMIN ─────────────────────────────────────────────
  {
    id: 1,
    sso_id: "sso-platform-admin-001",
    phone: "+7 (900) 100-00-01",
    email: "s.ivanov@beyondviolet.io",
    first_name: "Сергей",
    last_name: "Иванов",
    middle_name: "Константинович",
    type: "STAFF",
    hired_at: d("2024-01-15"),
    archived: false,
    preferred_locale: "en",
    preferred_timezone: "Europe/Moscow",
    totp_enabled: false,
  },

  // ── 2. AGENT ──────────────────────────────────────────────────────
  {
    /** Login → редиректит на /agent. Привязан к agent-001 (из freelance-agents.ts) */
    id: 2,
    sso_id: "sso-agent-zakharova",
    phone: "+7 (913) 200-11-22",
    email: "m.zakharova@ipzakharova.ru",
    first_name: "Марина",
    last_name: "Захарова",
    middle_name: "Сергеевна",
    type: "STAFF",
    hired_at: d("2024-06-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    agent_id: "agent-001",
  },

  // ── 3. NETWORK_OPS (СPAR Сибирь) — totp enabled, Europe/London ──
  {
    id: 3,
    sso_id: "sso-network-ops-sokolova",
    phone: "+7 (913) 300-22-33",
    email: "a.sokolova@spar-sibir.ru",
    first_name: "Анна",
    last_name: "Соколова",
    middle_name: "Викторовна",
    type: "STAFF",
    hired_at: d("2023-09-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Europe/London",
    totp_enabled: true,
    rating: 4.9,
  },

  // ── 4. SUPERVISOR (СПАР Томск + Новосибирск) ─────────────────────
  {
    id: 4,
    sso_id: "sso-supervisor-romanov",
    phone: "+7 (913) 401-33-44",
    email: "i.romanov@spar-sibir.ru",
    first_name: "Игорь",
    last_name: "Романов",
    middle_name: "Алексеевич",
    type: "STAFF",
    hired_at: d("2023-11-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.7,
  },

  // ── 5. STORE_DIRECTOR — SPAR-TOM-001 ────────────────────────────
  {
    id: 5,
    sso_id: "sso-sd-ivanov-as",
    phone: "+7 (913) 501-44-55",
    email: "a.ivanov@spar-sibir.ru",
    first_name: "Александр",
    last_name: "Иванов",
    middle_name: "Сергеевич",
    type: "STAFF",
    hired_at: d("2024-02-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.5,
  },

  // ── 6. STORE_DIRECTOR — SPAR-TOM-002 ────────────────────────────
  {
    id: 6,
    sso_id: "sso-sd-petrova",
    phone: "+7 (913) 601-55-66",
    email: "e.petrova@spar-sibir.ru",
    first_name: "Елена",
    last_name: "Петрова",
    middle_name: "Владимировна",
    type: "STAFF",
    hired_at: d("2024-03-15"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.6,
  },

  // ── 7. STORE_DIRECTOR — SPAR-NSK-001 ────────────────────────────
  {
    id: 7,
    sso_id: "sso-sd-sidorov",
    phone: "+7 (923) 701-66-77",
    email: "k.sidorov@spar-sibir.ru",
    first_name: "Константин",
    last_name: "Сидоров",
    middle_name: "Михайлович",
    type: "STAFF",
    hired_at: d("2023-12-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 4.4,
  },

  // ── 8. STORE_DIRECTOR — SPAR-NSK-002 ────────────────────────────
  {
    id: 8,
    sso_id: "sso-sd-vasiliev",
    phone: "+7 (923) 801-77-88",
    email: "d.vasiliev@spar-sibir.ru",
    first_name: "Дмитрий",
    last_name: "Васильев",
    middle_name: "Олегович",
    type: "STAFF",
    hired_at: d("2024-01-10"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 4.3,
  },

  // ── 9. STORE_DIRECTOR — SPAR-KEM-001 ────────────────────────────
  {
    id: 9,
    sso_id: "sso-sd-nikitin",
    phone: "+7 (384) 901-88-99",
    email: "b.nikitin@spar-sibir.ru",
    first_name: "Борис",
    last_name: "Никитин",
    middle_name: "Сергеевич",
    type: "STAFF",
    hired_at: d("2024-04-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 4.2,
  },

  // ── 10. STORE_DIRECTOR — FC-TOM-001 ─────────────────────────────
  {
    id: 10,
    sso_id: "sso-sd-smirnova",
    phone: "+7 (913) 100-99-88",
    email: "o.smirnova@foodcity.ru",
    first_name: "Ольга",
    last_name: "Смирнова",
    middle_name: "Игоревна",
    type: "STAFF",
    hired_at: d("2023-10-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.8,
  },

  // ── 11. NETWORK_OPS — org-fashion-alfa (малый бизнес, владелец) ─
  {
    id: 11,
    sso_id: "sso-network-ops-nikitina",
    phone: "+7 (913) 111-00-11",
    email: "a.nikitina@alfa-fashion.ru",
    first_name: "Анна",
    last_name: "Никитина",
    middle_name: "Николаевна",
    type: "STAFF",
    hired_at: d("2024-05-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.9,
  },

  // ── 12. SUPERVISOR — Food City (3 магазина) ──────────────────────
  {
    id: 12,
    sso_id: "sso-supervisor-tarasova",
    phone: "+7 (913) 120-22-33",
    email: "o.tarasova@foodcity.ru",
    first_name: "Ольга",
    last_name: "Тарасова",
    middle_name: "Викторовна",
    type: "STAFF",
    hired_at: d("2024-01-20"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.6,
  },

  // ── 13. HR_MANAGER ──────────────────────────────────────────────
  {
    id: 13,
    sso_id: "sso-hr-morozova",
    phone: "+7 (913) 130-33-44",
    email: "e.morozova@spar-sibir.ru",
    first_name: "Елена",
    last_name: "Морозова",
    middle_name: "Сергеевна",
    type: "STAFF",
    hired_at: d("2024-02-15"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
  },

  // ── 14. OPERATOR (preferred_locale='en' — демо EN-режима) ────────
  {
    id: 14,
    sso_id: "sso-operator-kuznetsov",
    phone: "+7 (913) 140-44-55",
    email: "n.kuznetsov@spar-sibir.ru",
    first_name: "Никита",
    last_name: "Кузнецов",
    middle_name: "Павлович",
    type: "STAFF",
    hired_at: d("2024-03-01"),
    archived: false,
    preferred_locale: "en",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
  },

  // ── 15-28. WORKERS ───────────────────────────────────────────────
  {
    id: 15,
    sso_id: "sso-worker-001",
    phone: "+7 (913) 150-55-01",
    first_name: "Дарья",
    last_name: "Козлова",
    middle_name: "Андреевна",
    type: "STAFF",
    hired_at: d("2024-06-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.1,
  },
  {
    id: 16,
    sso_id: "sso-worker-002",
    phone: "+7 (913) 150-55-02",
    first_name: "Максим",
    last_name: "Новиков",
    middle_name: "Юрьевич",
    type: "STAFF",
    hired_at: d("2024-07-15"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 3.9,
  },
  {
    id: 17,
    sso_id: "sso-worker-003",
    phone: "+7 (913) 150-55-03",
    first_name: "Татьяна",
    last_name: "Медведева",
    middle_name: "Ивановна",
    type: "STAFF",
    hired_at: d("2024-08-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.3,
  },
  {
    id: 18,
    sso_id: "sso-worker-004",
    phone: "+7 (913) 150-55-04",
    first_name: "Алексей",
    last_name: "Федоров",
    middle_name: "Николаевич",
    type: "STAFF",
    hired_at: d("2024-09-10"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.0,
  },
  {
    id: 19,
    sso_id: "sso-worker-005",
    phone: "+7 (913) 150-55-05",
    first_name: "Наталья",
    last_name: "Захарова",
    middle_name: "Петровна",
    type: "STAFF",
    hired_at: d("2024-10-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.4,
  },
  {
    id: 20,
    sso_id: "sso-worker-006",
    phone: "+7 (913) 150-55-06",
    first_name: "Владимир",
    last_name: "Попов",
    middle_name: "Сергеевич",
    type: "STAFF",
    hired_at: d("2024-11-15"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 3.8,
  },
  {
    id: 21,
    sso_id: "sso-worker-007",
    phone: "+7 (923) 150-55-07",
    first_name: "Светлана",
    last_name: "Кириллова",
    middle_name: "Васильевна",
    type: "STAFF",
    hired_at: d("2024-12-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    rating: 4.2,
  },
  {
    id: 22,
    sso_id: "sso-worker-008",
    phone: "+7 (923) 150-55-08",
    first_name: "Андрей",
    last_name: "Степанов",
    middle_name: "Борисович",
    type: "STAFF",
    hired_at: d("2025-01-10"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    rating: 3.7,
  },
  {
    id: 23,
    sso_id: "sso-worker-009",
    phone: "+7 (923) 150-55-09",
    first_name: "Марина",
    last_name: "Волкова",
    middle_name: "Олеговна",
    type: "STAFF",
    hired_at: d("2025-02-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    rating: 4.5,
  },
  {
    id: 24,
    sso_id: "sso-worker-010",
    phone: "+7 (913) 150-55-10",
    first_name: "Роман",
    last_name: "Лебедев",
    middle_name: "Александрович",
    type: "STAFF",
    hired_at: d("2025-03-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.0,
  },
  {
    id: 25,
    sso_id: "sso-worker-011",
    phone: "+7 (913) 150-55-11",
    first_name: "Ирина",
    last_name: "Соловьева",
    middle_name: "Дмитриевна",
    type: "STAFF",
    hired_at: d("2025-04-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.6,
  },
  {
    id: 26,
    sso_id: "sso-worker-012",
    phone: "+7 (913) 150-55-12",
    first_name: "Павел",
    last_name: "Гусев",
    middle_name: "Михайлович",
    type: "STAFF",
    hired_at: d("2025-05-01"),
    archived: false,
    preferred_locale: "en",
    preferred_timezone: "Asia/Tomsk",
    rating: 3.9,
  },
  {
    id: 27,
    sso_id: "sso-worker-013",
    phone: "+7 (913) 150-55-13",
    first_name: "Юлия",
    last_name: "Белова",
    middle_name: "Сергеевна",
    type: "STAFF",
    hired_at: d("2025-06-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 4.3,
  },
  {
    /** Архивирован — уволен. archive_reason=OBSOLETE. Демо EmployeeFilter archived */
    id: 28,
    sso_id: "sso-worker-014",
    phone: "+7 (913) 150-55-14",
    first_name: "Игорь",
    last_name: "Тихонов",
    middle_name: "Васильевич",
    type: "STAFF",
    hired_at: d("2024-05-01"),
    archived: true,
    archive_reason: "OBSOLETE",
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    rating: 3.5,
  },

  // ── 29-31. FREELANCE (базовые примеры; полный список — freelance-freelancers.ts) ──
  {
    /** FREELANCE — активен, оферта подписана */
    id: 29,
    sso_id: "sso-freelance-001",
    phone: "+7 (913) 200-01-11",
    first_name: "Виктор",
    last_name: "Орлов",
    middle_name: "Павлович",
    type: "FREELANCE",
    hired_at: d("2025-01-15"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: "agent-001",
    oferta_accepted_at: d("2025-01-15"),
    rating: 4.7,
    source: "MANUAL",
  },
  {
    /** FREELANCE — в проверке (VERIFICATION) */
    id: 30,
    sso_id: "sso-freelance-002",
    phone: "+7 (913) 200-02-22",
    first_name: "Ксения",
    last_name: "Фролова",
    middle_name: "Андреевна",
    type: "FREELANCE",
    hired_at: d("2025-03-20"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "VERIFICATION",
    agent_id: "agent-001",
    oferta_accepted_at: null,
    rating: undefined,
    source: "MANUAL",
  },
  {
    /** FREELANCE — пришёл из внешней HR-системы SPAR (source=EXTERNAL_SYNC) */
    id: 31,
    sso_id: "sso-freelance-003",
    phone: "+7 (913) 200-03-33",
    first_name: "Евгений",
    last_name: "Мельников",
    middle_name: "Игоревич",
    type: "FREELANCE",
    hired_at: d("2025-04-10"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "ACTIVE",
    agent_id: null,
    oferta_accepted_at: d("2025-04-10"),
    rating: 4.5,
    source: "EXTERNAL_SYNC",
  },
  {
    /** FREELANCE — новый, оферта не подписана, agent-002 */
    id: 32,
    sso_id: "sso-freelance-004",
    phone: "+7 (913) 200-04-44",
    first_name: "Дарья",
    last_name: "Коваленко",
    middle_name: "Артёмовна",
    type: "FREELANCE",
    hired_at: d("2026-04-20"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "NEW",
    agent_id: "agent-002",
    oferta_accepted_at: null,
    rating: undefined,
    source: "MANUAL",
  },
  {
    /** FREELANCE — заблокирован */
    id: 33,
    sso_id: "sso-freelance-005",
    phone: "+7 (913) 200-05-55",
    first_name: "Артём",
    last_name: "Громов",
    middle_name: "Олегович",
    type: "FREELANCE",
    hired_at: d("2025-07-01"),
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    freelancer_status: "BLOCKED",
    agent_id: "agent-002",
    oferta_accepted_at: d("2025-07-01"),
    rating: 2.8,
    source: "MANUAL",
  },

  // ── 101. DEMO — Иванова Мария Петровна (employeeDetail demo) ──────
  {
    /** Demo user for /employees/101 — штатный кассир SPAR-TOM-001, активный */
    id: 101,
    sso_id: "sso-worker-101",
    phone: "+7 (913) 101-22-33",
    email: "m.ivanova@spar-sibir.ru",
    first_name: "Мария",
    last_name: "Иванова",
    middle_name: "Петровна",
    type: "STAFF",
    hired_at: "2024-03-15",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.6,
  },
  {
    id: 35,
    sso_id: "sso-worker-035",
    phone: "+7 (912) 000-00-35",
    first_name: "Марина",
    last_name: "Иванова",
    middle_name: "Михайловна",
    type: "STAFF",
    hired_at: "2026-01-22",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.3,
  },
  {
    id: 36,
    sso_id: "sso-worker-036",
    phone: "+7 (980) 000-00-36",
    first_name: "Евгений",
    last_name: "Сидоров",
    middle_name: "Михайлович",
    type: "STAFF",
    hired_at: "2024-09-07",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.8,
  },
  {
    id: 37,
    sso_id: "sso-worker-037",
    phone: "+7 (960) 000-00-37",
    first_name: "Анна",
    last_name: "Романова",
    middle_name: "Дмитриевна",
    type: "STAFF",
    hired_at: "2025-03-07",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.6,
  },
  {
    id: 38,
    sso_id: "sso-worker-038",
    phone: "+7 (965) 000-00-38",
    first_name: "Михаил",
    last_name: "Волков",
    middle_name: "Николаевич",
    type: "STAFF",
    hired_at: "2025-09-04",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.6,
  },
  {
    id: 39,
    sso_id: "sso-worker-039",
    phone: "+7 (930) 000-00-39",
    first_name: "Виталий",
    last_name: "Белов",
    middle_name: "Сергеевич",
    type: "STAFF",
    hired_at: "2024-01-22",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.6,
  },
  {
    id: 40,
    sso_id: "sso-worker-040",
    phone: "+7 (963) 000-00-40",
    first_name: "Маргарита",
    last_name: "Сергеева",
    middle_name: "Викторовна",
    type: "STAFF",
    hired_at: "2025-11-27",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.7,
  },
  {
    id: 41,
    sso_id: "sso-worker-041",
    phone: "+7 (986) 000-00-41",
    first_name: "Илья",
    last_name: "Комаров",
    middle_name: "Андреевич",
    type: "STAFF",
    hired_at: "2026-02-06",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Krasnoyarsk",
    totp_enabled: false,
    rating: 4.0,
  },
  {
    id: 42,
    sso_id: "sso-worker-042",
    phone: "+7 (951) 000-00-42",
    first_name: "Алёна",
    last_name: "Белова",
    middle_name: "Михайловна",
    type: "STAFF",
    hired_at: "2024-01-26",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.1,
  },
  {
    id: 43,
    sso_id: "sso-worker-043",
    phone: "+7 (985) 000-00-43",
    first_name: "Юрий",
    last_name: "Павлов",
    middle_name: "Петрович",
    type: "STAFF",
    hired_at: "2025-07-21",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.7,
  },
  {
    id: 44,
    sso_id: "sso-worker-044",
    phone: "+7 (918) 000-00-44",
    first_name: "Степан",
    last_name: "Николаев",
    middle_name: "Николаевич",
    type: "STAFF",
    hired_at: "2025-06-08",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.2,
  },
  {
    id: 45,
    sso_id: "sso-worker-045",
    phone: "+7 (966) 000-00-45",
    first_name: "Артём",
    last_name: "Петров",
    middle_name: "Владимирович",
    type: "STAFF",
    hired_at: "2025-10-03",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Krasnoyarsk",
    totp_enabled: false,
    rating: 4.0,
  },
  {
    id: 46,
    sso_id: "sso-worker-046",
    phone: "+7 (960) 000-00-46",
    first_name: "Марина",
    last_name: "Фёдорова",
    middle_name: "Александровна",
    type: "STAFF",
    hired_at: "2026-03-25",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 3.7,
  },
  {
    id: 47,
    sso_id: "sso-worker-047",
    phone: "+7 (939) 000-00-47",
    first_name: "Александр",
    last_name: "Орлов",
    middle_name: "Николаевич",
    type: "STAFF",
    hired_at: "2026-01-28",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.7,
  },
  {
    id: 48,
    sso_id: "sso-worker-048",
    phone: "+7 (952) 000-00-48",
    first_name: "Елена",
    last_name: "Попова",
    middle_name: "Сергеевна",
    type: "STAFF",
    hired_at: "2026-01-20",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Krasnoyarsk",
    totp_enabled: false,
    rating: 4.2,
  },
  {
    id: 49,
    sso_id: "sso-worker-049",
    phone: "+7 (989) 000-00-49",
    first_name: "Кирилл",
    last_name: "Волков",
    middle_name: "Михайлович",
    type: "STAFF",
    hired_at: "2026-01-03",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.6,
  },
  {
    id: 50,
    sso_id: "sso-worker-050",
    phone: "+7 (981) 000-00-50",
    first_name: "Елена",
    last_name: "Михайлова",
    middle_name: "Владимировна",
    type: "STAFF",
    hired_at: "2024-05-17",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.9,
  },
  {
    id: 51,
    sso_id: "sso-worker-051",
    phone: "+7 (984) 000-00-51",
    first_name: "Ксения",
    last_name: "Григорьева",
    middle_name: "Олеговна",
    type: "STAFF",
    hired_at: "2026-03-15",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.7,
  },
  {
    id: 52,
    sso_id: "sso-worker-052",
    phone: "+7 (908) 000-00-52",
    first_name: "Александр",
    last_name: "Морозов",
    middle_name: "Михайлович",
    type: "STAFF",
    hired_at: "2024-12-21",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.8,
  },
  {
    id: 53,
    sso_id: "sso-worker-053",
    phone: "+7 (928) 000-00-53",
    first_name: "Наталья",
    last_name: "Сергеева",
    middle_name: "Андреевна",
    type: "STAFF",
    hired_at: "2025-11-16",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.3,
  },
  {
    id: 54,
    sso_id: "sso-worker-054",
    phone: "+7 (913) 000-00-54",
    first_name: "Вероника",
    last_name: "Зайцева",
    middle_name: "Кирилловна",
    type: "STAFF",
    hired_at: "2025-04-04",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.4,
  },
  {
    id: 55,
    sso_id: "sso-worker-055",
    phone: "+7 (914) 000-00-55",
    first_name: "Павел",
    last_name: "Крылов",
    middle_name: "Алексеевич",
    type: "STAFF",
    hired_at: "2025-12-11",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 3.8,
  },
  {
    id: 56,
    sso_id: "sso-worker-056",
    phone: "+7 (910) 000-00-56",
    first_name: "Владимир",
    last_name: "Орлов",
    middle_name: "Викторович",
    type: "STAFF",
    hired_at: "2025-04-28",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Krasnoyarsk",
    totp_enabled: false,
    rating: 4.1,
  },
  {
    id: 57,
    sso_id: "sso-worker-057",
    phone: "+7 (989) 000-00-57",
    first_name: "Екатерина",
    last_name: "Михайлова",
    middle_name: "Алексеевна",
    type: "STAFF",
    hired_at: "2024-03-14",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.2,
  },
  {
    id: 58,
    sso_id: "sso-worker-058",
    phone: "+7 (985) 000-00-58",
    first_name: "Виктория",
    last_name: "Зайцева",
    middle_name: "Дмитриевна",
    type: "STAFF",
    hired_at: "2025-05-26",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.9,
  },
  {
    id: 59,
    sso_id: "sso-worker-059",
    phone: "+7 (908) 000-00-59",
    first_name: "Алёна",
    last_name: "Николаева",
    middle_name: "Кирилловна",
    type: "STAFF",
    hired_at: "2025-04-02",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 4.5,
  },
  {
    id: 60,
    sso_id: "sso-worker-060",
    phone: "+7 (909) 000-00-60",
    first_name: "Роман",
    last_name: "Беляев",
    middle_name: "Дмитриевич",
    type: "STAFF",
    hired_at: "2024-03-03",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.4,
  },
  {
    id: 61,
    sso_id: "sso-worker-061",
    phone: "+7 (951) 000-00-61",
    first_name: "Юрий",
    last_name: "Кузнецов",
    middle_name: "Михайлович",
    type: "STAFF",
    hired_at: "2024-07-22",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.8,
  },
  {
    id: 62,
    sso_id: "sso-worker-062",
    phone: "+7 (939) 000-00-62",
    first_name: "Максим",
    last_name: "Степанов",
    middle_name: "Михайлович",
    type: "STAFF",
    hired_at: "2024-11-21",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.1,
  },
  {
    id: 63,
    sso_id: "sso-worker-063",
    phone: "+7 (928) 000-00-63",
    first_name: "Дарья",
    last_name: "Павлова",
    middle_name: "Александровна",
    type: "STAFF",
    hired_at: "2026-01-03",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.2,
  },
  {
    id: 64,
    sso_id: "sso-worker-064",
    phone: "+7 (939) 000-00-64",
    first_name: "Андрей",
    last_name: "Волков",
    middle_name: "Михайлович",
    type: "STAFF",
    hired_at: "2024-08-27",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.4,
  },
  {
    id: 65,
    sso_id: "sso-worker-065",
    phone: "+7 (918) 000-00-65",
    first_name: "Анастасия",
    last_name: "Белова",
    middle_name: "Александровна",
    type: "STAFF",
    hired_at: "2025-11-04",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.9,
  },
  {
    id: 66,
    sso_id: "sso-worker-066",
    phone: "+7 (960) 000-00-66",
    first_name: "Алёна",
    last_name: "Николаева",
    middle_name: "Владимировна",
    type: "STAFF",
    hired_at: "2026-02-23",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.8,
  },
  {
    id: 67,
    sso_id: "sso-worker-067",
    phone: "+7 (936) 000-00-67",
    first_name: "Анастасия",
    last_name: "Козлова",
    middle_name: "Кирилловна",
    type: "STAFF",
    hired_at: "2024-11-14",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.6,
  },
  {
    id: 68,
    sso_id: "sso-worker-068",
    phone: "+7 (901) 000-00-68",
    first_name: "Илья",
    last_name: "Смирнов",
    middle_name: "Дмитриевич",
    type: "STAFF",
    hired_at: "2026-04-18",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.7,
  },
  {
    id: 69,
    sso_id: "sso-worker-069",
    phone: "+7 (917) 000-00-69",
    first_name: "Елена",
    last_name: "Степанова",
    middle_name: "Алексеевна",
    type: "STAFF",
    hired_at: "2026-02-14",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.6,
  },
  {
    id: 70,
    sso_id: "sso-worker-070",
    phone: "+7 (962) 000-00-70",
    first_name: "Алексей",
    last_name: "Павлов",
    middle_name: "Сергеевич",
    type: "STAFF",
    hired_at: "2024-11-04",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 4.6,
  },
  {
    id: 71,
    sso_id: "sso-worker-071",
    phone: "+7 (923) 000-00-71",
    first_name: "Полина",
    last_name: "Крылова",
    middle_name: "Владимировна",
    type: "STAFF",
    hired_at: "2024-07-01",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 4.5,
  },
  {
    id: 72,
    sso_id: "sso-worker-072",
    phone: "+7 (904) 000-00-72",
    first_name: "Олег",
    last_name: "Павлов",
    middle_name: "Михайлович",
    type: "STAFF",
    hired_at: "2026-01-13",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.7,
  },
  {
    id: 73,
    sso_id: "sso-worker-073",
    phone: "+7 (925) 000-00-73",
    first_name: "Павел",
    last_name: "Воробьёв",
    middle_name: "Сергеевич",
    type: "STAFF",
    hired_at: "2024-01-22",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.1,
  },
  {
    id: 74,
    sso_id: "sso-worker-074",
    phone: "+7 (953) 000-00-74",
    first_name: "Илья",
    last_name: "Сидоров",
    middle_name: "Сергеевич",
    type: "STAFF",
    hired_at: "2025-11-27",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.8,
  },
  {
    id: 75,
    sso_id: "sso-worker-075",
    phone: "+7 (951) 000-00-75",
    first_name: "Дмитрий",
    last_name: "Козлов",
    middle_name: "Николаевич",
    type: "STAFF",
    hired_at: "2026-04-12",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.1,
  },
  {
    id: 76,
    sso_id: "sso-worker-076",
    phone: "+7 (926) 000-00-76",
    first_name: "Светлана",
    last_name: "Кузнецова",
    middle_name: "Игоревна",
    type: "STAFF",
    hired_at: "2026-04-01",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.0,
  },
  {
    id: 77,
    sso_id: "sso-worker-077",
    phone: "+7 (950) 000-00-77",
    first_name: "Максим",
    last_name: "Комаров",
    middle_name: "Петрович",
    type: "STAFF",
    hired_at: "2026-03-17",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.4,
  },
  {
    id: 78,
    sso_id: "sso-worker-078",
    phone: "+7 (923) 000-00-78",
    first_name: "Кирилл",
    last_name: "Степанов",
    middle_name: "Владимирович",
    type: "STAFF",
    hired_at: "2026-04-22",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 4.4,
  },
  {
    id: 79,
    sso_id: "sso-worker-079",
    phone: "+7 (952) 000-00-79",
    first_name: "Александр",
    last_name: "Михайлов",
    middle_name: "Олегович",
    type: "STAFF",
    hired_at: "2025-10-20",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.2,
  },
  {
    id: 80,
    sso_id: "sso-worker-080",
    phone: "+7 (953) 000-00-80",
    first_name: "Сергей",
    last_name: "Попов",
    middle_name: "Кириллович",
    type: "STAFF",
    hired_at: "2024-05-17",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 3.6,
  },
  {
    id: 81,
    sso_id: "sso-worker-081",
    phone: "+7 (987) 000-00-81",
    first_name: "Мария",
    last_name: "Лебедева",
    middle_name: "Михайловна",
    type: "STAFF",
    hired_at: "2024-01-08",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.4,
  },
  {
    id: 82,
    sso_id: "sso-worker-082",
    phone: "+7 (900) 000-00-82",
    first_name: "София",
    last_name: "Орлова",
    middle_name: "Игоревна",
    type: "STAFF",
    hired_at: "2025-04-05",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.7,
  },
  {
    id: 83,
    sso_id: "sso-worker-083",
    phone: "+7 (932) 000-00-83",
    first_name: "Екатерина",
    last_name: "Зайцева",
    middle_name: "Иванoвна",
    type: "STAFF",
    hired_at: "2026-04-02",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.8,
  },
  {
    id: 84,
    sso_id: "sso-worker-084",
    phone: "+7 (984) 000-00-84",
    first_name: "Павел",
    last_name: "Смирнов",
    middle_name: "Петрович",
    type: "STAFF",
    hired_at: "2026-04-27",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Krasnoyarsk",
    totp_enabled: false,
    rating: 4.8,
  },
  {
    id: 85,
    sso_id: "sso-worker-085",
    phone: "+7 (931) 000-00-85",
    first_name: "Татьяна",
    last_name: "Богданова",
    middle_name: "Николаевна",
    type: "STAFF",
    hired_at: "2025-09-16",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.9,
  },
  {
    id: 86,
    sso_id: "sso-worker-086",
    phone: "+7 (920) 000-00-86",
    first_name: "Игорь",
    last_name: "Новиков",
    middle_name: "Николаевич",
    type: "STAFF",
    hired_at: "2026-01-05",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.8,
  },
  {
    id: 87,
    sso_id: "sso-worker-087",
    phone: "+7 (980) 000-00-87",
    first_name: "Ксения",
    last_name: "Степанова",
    middle_name: "Андреевна",
    type: "STAFF",
    hired_at: "2025-09-15",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.6,
  },
  {
    id: 88,
    sso_id: "sso-worker-088",
    phone: "+7 (962) 000-00-88",
    first_name: "Вероника",
    last_name: "Алексеева",
    middle_name: "Александровна",
    type: "STAFF",
    hired_at: "2025-08-01",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.9,
  },
  {
    id: 89,
    sso_id: "sso-worker-089",
    phone: "+7 (903) 000-00-89",
    first_name: "Олег",
    last_name: "Зайцев",
    middle_name: "Михайлович",
    type: "STAFF",
    hired_at: "2025-07-16",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.0,
  },
  {
    id: 90,
    sso_id: "sso-worker-090",
    phone: "+7 (903) 000-00-90",
    first_name: "Светлана",
    last_name: "Романова",
    middle_name: "Дмитриевна",
    type: "STAFF",
    hired_at: "2026-01-13",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.6,
  },
  {
    id: 91,
    sso_id: "sso-worker-091",
    phone: "+7 (985) 000-00-91",
    first_name: "Павел",
    last_name: "Сергеев",
    middle_name: "Дмитриевич",
    type: "STAFF",
    hired_at: "2025-06-07",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.0,
  },
  {
    id: 92,
    sso_id: "sso-worker-092",
    phone: "+7 (906) 000-00-92",
    first_name: "Марина",
    last_name: "Алексеева",
    middle_name: "Иванoвна",
    type: "STAFF",
    hired_at: "2025-01-24",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Novosibirsk",
    totp_enabled: false,
    rating: 4.9,
  },
  {
    id: 93,
    sso_id: "sso-worker-093",
    phone: "+7 (920) 000-00-93",
    first_name: "Андрей",
    last_name: "Белов",
    middle_name: "Алексеевич",
    type: "STAFF",
    hired_at: "2024-01-20",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.8,
  },
  {
    id: 94,
    sso_id: "sso-worker-094",
    phone: "+7 (915) 000-00-94",
    first_name: "Вероника",
    last_name: "Кузнецова",
    middle_name: "Игоревна",
    type: "STAFF",
    hired_at: "2025-06-06",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Krasnoyarsk",
    totp_enabled: false,
    rating: 4.6,
  },
  {
    id: 95,
    sso_id: "sso-worker-095",
    phone: "+7 (926) 000-00-95",
    first_name: "Артём",
    last_name: "Новиков",
    middle_name: "Александрович",
    type: "STAFF",
    hired_at: "2026-04-13",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.6,
  },
  {
    id: 96,
    sso_id: "sso-worker-096",
    phone: "+7 (905) 000-00-96",
    first_name: "Маргарита",
    last_name: "Белова",
    middle_name: "Викторовна",
    type: "STAFF",
    hired_at: "2026-01-26",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.0,
  },
  {
    id: 97,
    sso_id: "sso-worker-097",
    phone: "+7 (963) 000-00-97",
    first_name: "Андрей",
    last_name: "Волков",
    middle_name: "Петрович",
    type: "STAFF",
    hired_at: "2025-02-14",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.4,
  },
  {
    id: 98,
    sso_id: "sso-worker-098",
    phone: "+7 (988) 000-00-98",
    first_name: "Елена",
    last_name: "Степанова",
    middle_name: "Иванoвна",
    type: "STAFF",
    hired_at: "2026-03-20",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.2,
  },
  {
    id: 99,
    sso_id: "sso-worker-099",
    phone: "+7 (986) 000-00-99",
    first_name: "Марина",
    last_name: "Беляева",
    middle_name: "Петровна",
    type: "STAFF",
    hired_at: "2025-08-08",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.3,
  },
  {
    id: 100,
    sso_id: "sso-worker-100",
    phone: "+7 (934) 000-01-00",
    first_name: "Анна",
    last_name: "Морозова",
    middle_name: "Кирилловна",
    type: "STAFF",
    hired_at: "2025-04-12",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.0,
  },
  {
    id: 101,
    sso_id: "sso-worker-101",
    phone: "+7 (989) 000-01-01",
    first_name: "Марина",
    last_name: "Степанова",
    middle_name: "Александровна",
    type: "STAFF",
    hired_at: "2024-12-14",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.3,
  },
  {
    id: 102,
    sso_id: "sso-worker-102",
    phone: "+7 (932) 000-01-02",
    first_name: "Роман",
    last_name: "Богданов",
    middle_name: "Иванович",
    type: "STAFF",
    hired_at: "2025-04-13",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.9,
  },
  {
    id: 103,
    sso_id: "sso-worker-103",
    phone: "+7 (985) 000-01-03",
    first_name: "Алёна",
    last_name: "Богданова",
    middle_name: "Сергеевна",
    type: "STAFF",
    hired_at: "2026-03-12",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 3.9,
  },
  {
    id: 104,
    sso_id: "sso-worker-104",
    phone: "+7 (928) 000-01-04",
    first_name: "Евгений",
    last_name: "Кузнецов",
    middle_name: "Петрович",
    type: "STAFF",
    hired_at: "2026-02-07",
    archived: false,
    preferred_locale: "ru",
    preferred_timezone: "Asia/Tomsk",
    totp_enabled: false,
    rating: 4.5,
  },

  // ═════════════════════════════════════════════════════════════════
  // ТехПродЗдрав — 9 сотрудников швейного цеха (источник: Excel,
  // колонки ФИО + Тел). IDs 200+ чтобы не пересекаться с LAMA.
  // Каждому ниже соответствует position 10-18 (см. positions.ts) и
  // assignment в assignments.ts.
  // ═════════════════════════════════════════════════════════════════
  { id: 200, sso_id: "sso-tpz-cutter", phone: "+7 (904) 026-29-73", first_name: "Ольга", last_name: "Болтушкина", middle_name: "Викторовна", type: "STAFF", hired_at: "2024-03-15", archived: false, preferred_locale: "ru", preferred_timezone: "Asia/Tomsk", totp_enabled: false, rating: 4.7 },
  { id: 201, sso_id: "sso-tpz-embroiderer", phone: "+7 (919) 059-52-52", first_name: "Зухра", last_name: "Сахибаева", middle_name: "Маратовна", type: "STAFF", hired_at: "2024-08-20", archived: false, preferred_locale: "ru", preferred_timezone: "Asia/Tomsk", totp_enabled: false, rating: 4.8 },
  { id: 202, sso_id: "sso-tpz-complect", phone: "+7 (960) 718-72-17", first_name: "Алина", last_name: "Терещенко", middle_name: "Игоревна", type: "STAFF", hired_at: "2025-01-12", archived: false, preferred_locale: "ru", preferred_timezone: "Asia/Tomsk", totp_enabled: false, rating: 4.5 },
  { id: 203, sso_id: "sso-tpz-seamstress", phone: "+7 (904) 027-37-12", first_name: "Анна", last_name: "Топоровски", middle_name: "Сергеевна", type: "STAFF", hired_at: "2023-11-05", archived: false, preferred_locale: "ru", preferred_timezone: "Asia/Tomsk", totp_enabled: false, rating: 4.9 },
  { id: 204, sso_id: "sso-tpz-handsewer", phone: "+7 (904) 004-67-92", first_name: "Надежда", last_name: "Львова", middle_name: "Александровна", type: "STAFF", hired_at: "2024-06-01", archived: false, preferred_locale: "ru", preferred_timezone: "Asia/Tomsk", totp_enabled: false, rating: 4.6 },
  { id: 205, sso_id: "sso-tpz-glueop", phone: "+7 (900) 017-04-09", first_name: "Юлия", last_name: "Новикова", middle_name: "Андреевна", type: "STAFF", hired_at: "2024-09-10", archived: false, preferred_locale: "ru", preferred_timezone: "Asia/Tomsk", totp_enabled: false, rating: 4.7 },
  { id: 206, sso_id: "sso-tpz-doserop", phone: "+7 (952) 063-16-53", first_name: "Екатерина", last_name: "Иванова", middle_name: "Михайловна", type: "STAFF", hired_at: "2025-02-20", archived: false, preferred_locale: "ru", preferred_timezone: "Asia/Tomsk", totp_enabled: false, rating: 4.4 },
  { id: 207, sso_id: "sso-tpz-binder", phone: "+7 (903) 034-27-43", first_name: "Александра", last_name: "Леднёва", middle_name: "Дмитриевна", type: "STAFF", hired_at: "2024-04-15", archived: false, preferred_locale: "ru", preferred_timezone: "Asia/Tomsk", totp_enabled: false, rating: 4.8 },
  { id: 208, sso_id: "sso-tpz-packer", phone: "+7 (904) 025-04-23", first_name: "Людмила", last_name: "Насурова", middle_name: "Олеговна", type: "STAFF", hired_at: "2025-05-01", archived: false, preferred_locale: "ru", preferred_timezone: "Asia/Tomsk", totp_enabled: false, rating: 4.3 },
];
