import type { WorkType } from "@/lib/types";

/**
 * @endpoint GET /api/work-types
 * 18 work types with explicit numeric IDs synced with hints CSV.
 * IDs 1-13: retail / FMCG. IDs 21-25: production (visible only when org has WORKSHOP/PRODUCTION_LINE).
 * group ≠ ProductCategory — these are operational groupings.
 */
export const MOCK_WORK_TYPES: WorkType[] = [
  // ── Retail / FMCG (id 1–13) ─────────────────────────────────────
  {
    id: 1,
    code: "MGR_OPS",
    name: "Менеджерские операции",
    description: "Административные и управленческие задачи руководителя магазина",
    group: "Управление",
    default_duration_min: 30,
    requires_photo_default: false,
    requires_report_default: false,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 1,
  },
  {
    id: 2,
    code: "CASHIER",
    name: "Касса",
    description: "Обслуживание покупателей на кассовом узле в течение смены",
    group: "Касса",
    default_duration_min: 480,
    requires_photo_default: false,
    requires_report_default: false,
    acceptance_policy_default: "AUTO",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 1,
  },
  {
    id: 3,
    code: "SELF_CHECKOUT",
    name: "КСО (самокассы)",
    description: "Обслуживание зоны самообслуживания и помощь покупателям",
    group: "Касса",
    default_duration_min: 60,
    requires_photo_default: false,
    requires_report_default: false,
    acceptance_policy_default: "AUTO",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 1,
  },
  {
    id: 4,
    code: "MERCH",
    name: "Выкладка",
    description: "Выкладка товара на полки согласно планограмме, фотофиксация результата",
    group: "Мерчендайзинг",
    default_duration_min: 30,
    requires_photo_default: true,
    requires_report_default: false,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 5,
  },
  {
    id: 5,
    code: "REPRICE",
    name: "Переоценка",
    description: "Замена ценников и электронных ценникодержателей при изменении цен",
    group: "Мерчендайзинг",
    default_duration_min: 45,
    requires_photo_default: false,
    requires_report_default: false,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 3,
  },
  {
    id: 6,
    code: "INVENTORY",
    name: "Инвентаризация",
    description: "Пересчёт и сверка остатков товаров, оформление актов",
    group: "Логистика",
    default_duration_min: 90,
    requires_photo_default: true,
    requires_report_default: true,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 4,
  },
  {
    id: 7,
    code: "OTHER_RETAIL",
    name: "Другие работы",
    description: "Прочие розничные операции, не вошедшие в стандартные категории",
    group: "Поддержка",
    default_duration_min: 30,
    requires_photo_default: false,
    requires_report_default: false,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 100,
  },
  {
    id: 8,
    code: "BREAK",
    name: "Перерыв",
    description: "Регламентированный перерыв сотрудника согласно трудовому законодательству",
    group: "Поддержка",
    default_duration_min: 30,
    requires_photo_default: false,
    requires_report_default: false,
    acceptance_policy_default: "AUTO",
    allow_new_subtasks: false,
    hints_count: 0,
    default_priority: 99,
  },
  {
    id: 9,
    code: "MERCH_PLAN",
    name: "Мерчендайзинг (планограммы)",
    description: "Реализация утверждённой планограммы расстановки и визуального мерчендайзинга",
    group: "Мерчендайзинг",
    default_duration_min: 60,
    requires_photo_default: true,
    requires_report_default: false,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 5,
  },
  {
    id: 10,
    code: "PRICING",
    name: "Ценообразование",
    description: "Актуализация ценовых карточек и контроль корректности ценников",
    group: "Мерчендайзинг",
    default_duration_min: 30,
    requires_photo_default: false,
    requires_report_default: false,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 3,
  },
  {
    id: 11,
    code: "QUALITY",
    name: "Контроль качества",
    description: "Проверка сроков годности, внешнего вида и хранения товаров",
    group: "Качество",
    default_duration_min: 25,
    requires_photo_default: true,
    requires_report_default: true,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 3,
  },
  {
    id: 12,
    code: "CLEANING",
    name: "Уборка",
    description: "Поддержание чистоты торгового зала и служебных помещений",
    group: "Поддержка",
    default_duration_min: 20,
    requires_photo_default: false,
    requires_report_default: false,
    acceptance_policy_default: "AUTO",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 12,
  },
  {
    id: 13,
    code: "WAREHOUSE",
    name: "Складские работы",
    description: "Приёмка, размещение и отпуск товаров на складе с фотофиксацией",
    group: "Логистика",
    default_duration_min: 60,
    requires_photo_default: true,
    requires_report_default: false,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 13,
  },

  // ── Производство (id 21–25) ── видны только при object_type=WORKSHOP/PRODUCTION_LINE ──
  {
    id: 21,
    code: "SEWING",
    name: "Машинный пошив",
    description: "Пошив изделий на промышленных швейных машинах по техническому заданию",
    group: "Производство",
    default_duration_min: 60,
    requires_photo_default: false,
    requires_report_default: false,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
    default_priority: 11,
  },
  {
    id: 22,
    code: "EMBROIDERY",
    name: "Вышивка и маркировка",
    description: "Нанесение вышивки, термотрансфера или прямой маркировки на готовые изделия",
    group: "Производство",
    default_duration_min: 45,
    requires_photo_default: false,
    requires_report_default: false,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
  },
  {
    id: 23,
    code: "FILLING",
    name: "Наполнение",
    description: "Набивка и наполнение изделий (подушки, мягкие игрушки, мягкая мебель)",
    group: "Производство",
    default_duration_min: 30,
    requires_photo_default: false,
    requires_report_default: false,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
  },
  {
    id: 24,
    code: "SEALING",
    name: "Герметизация",
    description: "Герметизация швов и соединений в производстве водоотталкивающих изделий",
    group: "Производство",
    default_duration_min: 20,
    requires_photo_default: false,
    requires_report_default: false,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
  },
  {
    id: 25,
    code: "FINISHING",
    name: "Ручная отделка",
    description: "Финальная ручная отделка, контроль качества и упаковка готовых изделий",
    group: "Производство",
    default_duration_min: 40,
    requires_photo_default: true,
    requires_report_default: false,
    acceptance_policy_default: "MANUAL",
    allow_new_subtasks: true,
    hints_count: 0,
  },
];
