location = /download {
    if ($http_user_agent ~* "android") {
        return 302 market://details?id=com.beyondviolet.wfm;
    }
    if ($http_user_agent ~* "(iphone|ipad|ipod)") {
        return 302 https://apps.apple.com/us/app/%D1%83%D0%BC%D0%BD%D1%8B%D0%B9-%D1%81%D0%BE%D1%82%D1%80%D1%83%D0%B4%D0%BD%D0%B8%D0%BA/id6762371137;
    }
    return 302 https://wfm.beyondviolet.com/;
}
